Repository spatialos/gdk-for-unity, pull requests merged in 2018-11, with the labels that each got.

#587 Fix docs build verification script
  ci/docs-build-verification.sh
Labels: size/S

#592 Add AuthorityLossImminent acknowledgement docs
  docs/content/gameobject/readers-writers.md
Labels: size/XS

#594 updating worker connector docs
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
Labels: size/S

#596 updating docs for unity update
  docs/content/get-started/set-up.md
  docs/setup-and-installing.md
Labels: size/S

#563 entity queries now work
  docs/content/ecs/world-commands.md
  docs/content/gameobject/world-commands.md
  docs/known-issues.md
Labels: size/S

#595 updating to latest unity
  ci/UnityEditorHash.txt
  workers/unity/ProjectSettings/ProjectVersion.txt
Labels: size/XS

#597 update release version in guide
  docs/content/get-started/set-up.md
Labels: size/XS

#599 Release 0.1.2 prep
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: size/S

#603 ToC formatting tidy-up and standardize
  docs/toc.md
Labels: size/M

#601 Add Blank starter project to docs
  docs/projects/blank/overview.md
  docs/toc.md
  docs/welcome.md
Labels: size/S

#604 Add blank project to README
  CHANGELOG.md
  README.md
Labels: size/XS

#610 add blank project to index page
  docs/index.md
  docs/welcome.md
Labels: size/XS

#612 UTY-1060: Prepend warning to copied schema files
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Labels: size/XS

#615 Temporarily stop building AndroidClient
  ci/build-test.sh
Labels: size/XS

#608 Cleaned up unused asset
  workers/unity/Assets/Config/GdkToolsConfiguration.asset
  workers/unity/Assets/Config/GdkToolsConfiguration.asset.meta
Labels: size/S

#617 Add ISnapshottable interface to generated components
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ISnapshottable.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ISnapshottable.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Labels: size/XXL

#616 Reinstate android builds
  ci/build-test.sh
Labels: size/XS

#619 Bugfix - Code generation with fields called value
  CHANGELOG.md
  test-project/Assets/.Schema/improbable/gdk/tests/alternate_schema_syntax.schema
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/RandomDataType.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Labels: size/L

#620 Some misc improvements
  CHANGELOG.md
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderDataTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/M

#621 Docs/troubleshooting
  docs/content/troubleshooting.md
Labels: size/M

#613 Add Partials to Codegen
  CHANGELOG.md
  workers/unity/Assets/Playground/Config/CubeTemplate.cs
  workers/unity/Assets/Playground/Improbable.Playground.asmdef
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/CoordinatesExtensions.cs
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/CoordinatesExtensions.cs.meta
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/Improbable.Gdk.StandardLibraryUtils.asmdef
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/Improbable.Gdk.StandardLibraryUtils.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/Vector3dExtensions.cs
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/Vector3dExtensions.cs.meta
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/Vector3fExtensions.cs
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/Vector3fExtensions.cs.meta
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json.meta
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/GdkCodeGenerator.csproj
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.Coordinates
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.Vector3d
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.Vector3f
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityTypeDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/PartialDatabase.cs
Labels: size/XL

#624 UTY-1067: Add enum to test schema
  test-project/Assets/.Schema/improbable/gdk/tests/exhaustive_test.schema
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyProviders.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueProviders.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalProviders.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedProviders.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/SomeEnum.cs
Labels: size/XXL

#622 Schema Bundle JSON Structure
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/CodeGeneration.csproj
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Bundle.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/ComponentDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/EnumDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/TypeDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/JsonParsingTests.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator.sln
Labels: size/XXL

#630 Kport updates week of 19/11/2018
  workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs/PrefabPreprocessor.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/LocatorConfigTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs
Labels: size/M

#633 Release 0.1.3 Prep
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: size/S

#634 update pinned hash
  docs/content/get-started/set-up.md
Labels: size/XS

#636 Welcome page improvements
  docs/welcome.md
Labels: size/S

#640 Add step 5 to set up
  docs/content/get-started/set-up.md
Labels: size/S

#639 "Clean all workers" now cleans worker configs
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: size/XS

#507 Docs: Add ToCs
  docs/projects/fps/tutorial.md
Labels: size/S

#518 Docs: Minor fixes external feedback
  docs/content/get-started/upload-launch.md
Labels: size/XS

#643 added warning regarding Unity version
  docs/content/get-started/set-up.md
  docs/setup-and-installing.md
Labels: size/XS

#641 Fromatting tweaks to welcome and index docs
  docs/index.md
  docs/welcome.md
Labels: size/M

#635 CopySchema now scans for nested package dependencies
  CHANGELOG.md
  test-project/Packages/com.improbable.gdk.dependencytest/Improbable.Gdk.DependencyTest.asmdef
  test-project/Packages/com.improbable.gdk.dependencytest/Improbable.Gdk.DependencyTest.asmdef.meta
  test-project/Packages/com.improbable.gdk.dependencytest/Schema.meta
  test-project/Packages/com.improbable.gdk.dependencytest/Schema/dependency_test.schema
  test-project/Packages/com.improbable.gdk.dependencytest/Schema/dependency_test.schema.meta
  test-project/Packages/com.improbable.gdk.dependencytest/package.json
  test-project/Packages/com.improbable.gdk.dependencytest/package.json.meta
  test-project/Packages/com.improbable.gdk.dependencytestchild/Improbable.Gdk.DependencyTestChild.asmdef
  test-project/Packages/com.improbable.gdk.dependencytestchild/Improbable.Gdk.DependencyTestChild.asmdef.meta
  test-project/Packages/com.improbable.gdk.dependencytestchild/Schema.meta
  test-project/Packages/com.improbable.gdk.dependencytestchild/Schema/dependency_test_child.schema
  test-project/Packages/com.improbable.gdk.dependencytestchild/Schema/dependency_test_child.schema.meta
  test-project/Packages/com.improbable.gdk.dependencytestchild/package.json
  test-project/Packages/com.improbable.gdk.dependencytestchild/package.json.meta
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/Improbable.Gdk.DependencyTestGrandchild.asmdef
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/Improbable.Gdk.DependencyTestGrandchild.asmdef.meta
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/Schema.meta
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/Schema/dependency_test_grandchild.schema
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/Schema/dependency_test_grandchild.schema.meta
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/package.json
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/package.json.meta
  test-project/Packages/manifest.json
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Labels: size/L
