Repository spatialos/gdk-for-unity, pull requests merged in 2018-10, with the labels that each got.

#422 simplify build system
  test-project/Packages/manifest.json
  workers/unity/Assets/Generated/Improbable.Gdk.Generated.asmdef
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset.meta
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGeneratorWindow.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/BuildSystemMenu.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/BuildSystemMenu.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildPaths.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildPaths.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/GUIColorScope.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/GUIColorScope.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/PlayerCompression.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/PlayerCompression.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SceneItem.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObjectLoader.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObjectLoader.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerPlatform.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerPlatform.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildConfigNames.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorPaths.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorPaths.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/PathUtil.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/UnityPathUtil.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/UnityPathUtil.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/GdkCodeGenerator.csproj
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/BuildSystemAssemblyGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityWorkerMenuGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGenerator.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGeneratorOptions.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/BuildSystemAssemblyGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityWorkerMenuGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/WorkerGenerationJob.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
  workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs.meta
  workers/unity/spatialos.UnityClient.worker.json
Labels: size/XXL

#442 Docs: Fixed wrong wordings in deploy.md
  docs/content/deploy.md
Labels: size/XS

#440 Added an OwningWorker component and helpers
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/owning_worker.schema
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/owning_worker.schema.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
Labels: size/M

#433 Update set-up-new-project.md
  docs/content/set-up-new-project.md
Labels: size/XS

#445 UTY-1181 Adding plugin directories compatibility logic
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/M

#446 Core Package in Code Documentation
  workers/unity/Packages/com.improbable.gdk.core/Authority/AuthorityChanges.cs
  workers/unity/Packages/com.improbable.gdk.core/Authority/AuthorityComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialComponentData.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialComponentUpdate.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/Option.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ReactiveComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/SpatialEntityId.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/WorkerEntityComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/LocatorConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ReceptionistConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/ConnectionFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/InvalidSpatialEntityStateException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/UnknownComponentIdException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/UnknownRequestIdException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs/PrefabPreprocessor.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectRepresentationHelper.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/AuthorityComponentNotFoundException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/IWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderDataGetFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/WriterDataUpdateFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerDisconnectCallbackSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/BlittableBool.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ViewCommandBuffer.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
Labels: size/XXL

#452 ensuring linux plugin is added to the built out worker
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/XS

#453 using our special singleton for build configurations
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObjectLoader.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObjectLoader.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: size/L

#455 UTY-1306: Game Client Crash Fix
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
Labels: size/S

#458 Make setup guide a table
  docs/setup-and-installing.md
Labels: size/M

#457 Add FPS Setup Guide (SUPER SECRET DON'T LOOK)
  docs/projects/template-fps/setup-and-installing.md
Labels: size/S

#454 Removes clientAttributeSet argument in CreatePlayerEntityTemplate
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
Labels: size/XS

#460 Revert "UTY-1181 Adding plugin directories compatibility logic (#445)"
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/M

#461 Update dotenv with new link
  .env
Labels: size/XS

#463 skipping unknown worker builds instead of failing the build
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: size/XS

#467 Feature/pinned pooling test
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Labels: size/L

#465 Screenshots in Setup/Installation Guide
  docs/assets/setup/mac/dotnetcoresdk.png
  docs/assets/setup/mac/rider.png
  docs/assets/setup/mac/spatialos.png
  docs/assets/setup/mac/unity.png
  docs/assets/setup/mac/visualstudio.png
  docs/assets/setup/windows/dotnetcoresdk.png
  docs/assets/setup/windows/rider.png
  docs/assets/setup/windows/spatialos.png
  docs/assets/setup/windows/unity.png
  docs/assets/setup/windows/visualstudio.png
  docs/setup-and-installing.md
Labels: size/S

#466 Fixup Testing Docs
  docs/content/testing/how-to-run-tests.md
  docs/content/testing/testing-guidelines.md
  docs/content/testing/testing-overview.md
  docs/content/testing/testing-systems.md
  docs/content/testing/writing-a-new-unit-test.md
Labels: size/M

#472 Fix improbadocs issues for first part of ecs content
  docs/content/ecs/accessing-worker-info.md
  docs/content/ecs/authority.md
  docs/content/ecs/commands.md
  docs/content/ecs/component-data.md
  docs/content/ecs/custom-replication-system.md
Labels: size/M

#471 Improbadoc formatting for ecs docs (second half)
  docs/content/ecs/core-and-feature-module-overview.md
  docs/content/ecs/ecs-component-generation.md
  docs/content/ecs/ecs-component-updates.md
  docs/content/ecs/ecs-system-update-order.md
  docs/content/ecs/ecs-world-commands.md
  docs/content/ecs/entity-contracts.md
  docs/content/ecs/events.md
  docs/content/ecs/logging.md
  docs/content/ecs/reactive-components.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/ecs/system-update-order.md
  docs/content/ecs/temporary-components.md
  docs/content/glossary.md
Labels: size/M

#469 Improbadoc formatting for gameobject docs
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/create-delete-spos-entries.md
  docs/content/gameobject/gomb-creating-workers-with-workerconnector.md
  docs/content/gameobject/gomb-world-commands.md
  docs/content/gameobject/interact-spos-monobehaviours.md
  docs/content/gameobject/linking-spos-entities-gameobjects.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/gameobject/readers-writers.md
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/sending-receiving-events.md
  docs/content/gameobject/spatialoscomponent.md
  docs/content/glossary.md
Labels: size/XL

#464 Fix all links in content\workers\*.md
  docs/content/glossary.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/api-worker.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
Labels: size/XL

#473 Update package authors and descriptions
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: size/S

#474 Remove old FakeClient doc
  docs/projects/template-fps/cloud-fake-clients.md
Labels: size/M

#476 Fix Broken Link
  docs/projects/template-fps/setup-and-installing.md
Labels: size/XS

#478 rename troubleshooting file
  docs/content/troubleshooting.md
Labels: size/XS

#477 Remove .md extension from links
  docs/content/ecs/accessing-worker-info.md
  docs/content/ecs/component-data.md
  docs/content/ecs/custom-replication-system.md
  docs/content/ecs/ecs-component-generation.md
  docs/content/ecs/ecs-component-updates.md
  docs/content/ecs/ecs-system-update-order.md
  docs/content/ecs/ecs-world-commands.md
  docs/content/ecs/entity-contracts.md
  docs/content/ecs/events.md
  docs/content/ecs/logging.md
  docs/content/ecs/reactive-components.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/ecs/temporary-components.md
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/create-delete-spos-entries.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/modules/transform-feature-module.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/api-worker.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
Labels: size/M

#481 Remove old worker doc
  docs/content/build.md
  docs/content/workers.md
  docs/toc.md
Labels: size/S

#479 Improbadoc fixes for entity-template
  docs/content/entity-templates.md
Labels: size/S

#482 Docs/fix intro workflows spos entities page
  docs/content/intro-workflows-spos-entities.md
Labels: size/S

#483 Docs/content conversion
  docs/content/build.md
  docs/content/connecting-to-spos.md
  docs/content/entity-lifecycle.md
  docs/content/set-up-new-project.md
  docs/content/snapshots.md
Labels: size/M

#484 Deleting another old worker doc
  docs/content/ecs/accessing-worker-info.md
  docs/content/workers/workers-in-the-gdk.md
Labels: size/M

#480 Fix WCCRR document for improbadoc
  docs/content/world-component-commands-requests-responses.md
Labels: size/M

#486 Add Shader Fix Part
  docs/assets/shader-fix.jpg
  docs/welcome.md
Labels: size/XS

#470 Docs formatting fixes
  docs/content/deploy.md
  docs/content/glossary.md
  docs/content/workers/api-worker.md
  docs/toc.md
Labels: size/L

#487 Clean up and renaming
  docs/content/entity-templates.md
  docs/content/gameobject/create-delete-spatialos-entities.md
  docs/content/gameobject/gomb-world-commands.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/transform-feature-module.md
Labels: size/M

#489 More .md fixes
  docs/content/ecs/authority.md
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/gomb-creating-workers-with-workerconnector.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/testing/testing-overview.md
  docs/content/troubleshooting.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
Labels: size/M

#491 Renaming all the files
  docs/content/api-entity-builder.md
  docs/content/connecting-to-spatialos.md
  docs/content/ecs/authority.md
  docs/content/ecs/component-data.md
  docs/content/ecs/component-generation.md
  docs/content/ecs/component-updates.md
  docs/content/ecs/custom-replication-system.md
  docs/content/ecs/entity-contracts.md
  docs/content/ecs/events.md
  docs/content/ecs/logging.md
  docs/content/ecs/reactive-components.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/ecs/system-update-order.md
  docs/content/ecs/temporary-components.md
  docs/content/ecs/world-commands.md
  docs/content/entity-lifecycle.md
  docs/content/entity-templates.md
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/create-delete-spatialos-entities.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
  docs/content/gameobject/interact-spatialos-monobehaviours.md
  docs/content/gameobject/linking-spatialos-entities.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/gameobject/readers-writers.md
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/sending-receiving-events.md
  docs/content/gameobject/spatialoscomponent.md
  docs/content/gameobject/world-commands.md
  docs/content/glossary.md
  docs/content/intro-workflows-spatialos-entities.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/modules/transform-feature-module.md
  docs/content/snapshots.md
  docs/content/troubleshooting.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/api-worker.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
  docs/content/world-component-commands-requests-responses.md
  docs/projects/template-fps/tutorial.md
Labels: size/L

#494 Remove the burst package as a requirement from Core
  workers/unity/Packages/com.improbable.gdk.core/package.json
Labels: size/XS

#493 Welcome page style and typo fixed
  docs/welcome.md
Labels: size/XS

#495 Docs dogfooding feedback fixes
  docs/setup-and-installing.md
  docs/welcome.md
Labels: size/XS

#475 Early out when cleaning sometimes
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/M

#497 Updating welcome page
  docs/assets/inspector-fake-players.jpg
  docs/assets/inspector-simulated-player.png
  docs/assets/logs-app.png
  docs/assets/metrics.png
  docs/assets/overview-page-inspector.png
  docs/assets/overview-page-share.png
  docs/assets/overview-page-worker-flags.png
  docs/assets/overview-page.png
  docs/assets/worker-flags-modification.png
  docs/welcome.md
Labels: size/M

#498 Rename Unity GDK -> SpatialOS GDK for Unity
  docs/content/ecs/authority.md
  docs/license.md
Labels: size/XS

#490 general fixes from dogfooding feedback
  docs/assets/setup/mac/dotnetcoresdk.png
  docs/assets/setup/mac/rider.png
  docs/assets/setup/mac/spatialos.png
  docs/assets/setup/mac/unity.png
  docs/assets/setup/mac/visualstudio.png
  docs/assets/setup/windows/dotnetcoresdk.png
  docs/assets/setup/windows/rider.png
  docs/assets/setup/windows/spatialos.png
  docs/assets/setup/windows/unity.png
  docs/assets/setup/windows/visualstudio.png
  docs/assets/setup/windows/visualstudioworkloads.png
  docs/setup-and-installing.md
  docs/welcome.md
Labels: size/S

#499 Improve the setup guide
  docs/setup-and-installing.md
Labels: size/S

#496 Welcome page: building workers notes
  docs/assets/unity-spatialos-menu.jpg
  docs/get-started.md
  docs/projects/template-fps/setup-and-installing.md
Labels: size/XS

#501 Rewrote sections to make getting started easier
  docs/assets/fps/unity-fps-starterproject.jpg
  docs/content/api-entity-builder.md
  docs/content/build.md
  docs/content/code-generator.md
  docs/content/connecting-to-spatialos.md
  docs/content/deploy.md
  docs/content/ecs/authority.md
  docs/content/ecs/commands.md
  docs/content/ecs/component-data.md
  docs/content/ecs/component-generation.md
  docs/content/ecs/component-updates.md
  docs/content/ecs/custom-replication-system.md
  docs/content/ecs/entity-contracts.md
  docs/content/ecs/events.md
  docs/content/ecs/reactive-components.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/ecs/system-update-order.md
  docs/content/ecs/temporary-components.md
  docs/content/ecs/world-commands.md
  docs/content/entity-lifecycle.md
  docs/content/entity-templates.md
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/create-delete-spatialos-entities.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
  docs/content/gameobject/interact-spatialos-monobehaviours.md
  docs/content/gameobject/linking-spatialos-entities.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/gameobject/readers-writers.md
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/sending-receiving-events.md
  docs/content/gameobject/spatialoscomponent.md
  docs/content/gameobject/world-commands.md
  docs/content/intro-reference.md
  docs/content/intro-workflows-spatialos-entities.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/modules/transform-feature-module.md
  docs/content/set-up-new-project.md
  docs/content/snapshots.md
  docs/content/troubleshooting.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/api-worker.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
  docs/content/world-component-commands-requests-responses.md
  docs/contributing.md
  docs/get-started.md
  docs/projects/template-fps/overview.md
  docs/projects/template-fps/setup-and-installing.md
  docs/projects/template-fps/tutorial.md
  docs/setup-and-installing.md
  docs/toc.md
Labels: size/XL

#503 Remove Hooks Folder
  hooks/pre-push
Labels: size/XS

#504 Bump Package Versions
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: size/S

#506 doc fixes and adding note to use the 0.1.0 tag
  docs/content/ecs/authority.md
  docs/content/ecs/entity-contracts.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/spatialoscomponent.md
  docs/content/glossary.md
  docs/content/intro-workflows-spatialos-entities.md
  docs/content/testing/testing-guidelines.md
  docs/content/testing/testing-systems.md
  docs/content/testing/writing-a-new-unit-test.md
  docs/get-started.md
  docs/projects/fps/tutorial.md
Labels: size/L

#510 Add Warning about flag
  docs/get-started.md
Labels: size/XS

#512 adding warning and fixing link
  docs/get-started.md
  docs/toc.md
  docs/welcome.md
Labels: size/XS

#511 update readme
  .github/CONTRIBUTING.md
  README.md
Labels: size/M

#513 Add bugfix for NavMesh import issue
  docs/assets/navmesh-fixed.png
  docs/get-started.md
Labels: size/S

#509 Replace usages of LogEvent default constructor
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/GameObjectDelegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
Labels: size/XS

#524 Add Placeholder Bootstrap
  ci/bootstrap.sh
Labels: size/XS

#525 Docs/setup links
  docs/get-started.md
  docs/setup-and-installing.md
Labels: size/S

#517 Mobile local dev: Plugin compatibility logic
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
  workers/unity/Packages/com.improbable.gdk.tools/PluginPostprocessor.cs
  workers/unity/Packages/com.improbable.gdk.tools/PluginPostprocessor.cs.meta
Labels: size/L

#515 Linux build support warning added
  docs/content/build.md
  docs/content/troubleshooting.md
  docs/get-started.md
  docs/setup-and-installing.md
Labels: size/L

#532 running gamelogic worker always in headless
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: size/XS

#534 Resolve syntax issues in snippets
  docs/content/ecs/commands.md
  docs/content/ecs/sending-receiving-component-commands.md
Labels: size/XS

#527 Migrate CI to the Shared Repo
  .gitignore
  ci/bootstrap.sh
  ci/build-client.sh
  ci/build-gamelogic.sh
  ci/build-test.sh
  ci/docs-build-verification.sh
  ci/docs-lint.sh
  ci/includes/pinned-tools.sh
  ci/includes/profiling.sh
  ci/lint-check.sh
  ci/lint.sh
  ci/prepare-unity.sh
  ci/test.sh
  tools/DocsLinter/DocsLinter.csproj
  tools/DocsLinter/DotenvLoader.cs
  tools/DocsLinter/Program.cs
  tools/DocsLinter/SimplifiedMarkdownDoc.cs
  tools/DocsLinter/Tests/LinkCheckingTests.cs
  tools/DocsLinter/Tests/SimplifiedMarkdownDocTests.cs
  tools/DocsLinter/ThirdPartyLicenses.md
  tools/RunUnity/Program.cs
  tools/RunUnity/RunUnity.csproj
  tools/Tools.sln
  tools/Tools.sln.DotSettings
  tools/UnityPaths/UnityPaths.cs
  tools/UnityPaths/UnityPaths.csproj
Labels: size/XXL

#535 Clarify optional step in the tutorial
  docs/projects/fps/tutorial.md
Labels: size/XS

#528 Docs/improbadoc conversion fixes
  docs/get-started.md
Labels: size/S

#536 Fix Clean All Workers menu button
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: size/XS

#540 Remove component data array from core
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentCleanupHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityEventDetails.cs
Labels: size/XXL

#542 Docs/update index page
  docs/index.md
Labels: size/XS

#543 Force Position to Replicate Last
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
Labels: size/XS

#545 Added warning notes on build dependencies
  docs/content/build.md
  docs/content/troubleshooting.md
  docs/get-started.md
  docs/setup-and-installing.md
Labels: size/M

#337 Rewrote parts of the heartbeat system to be more simplistic
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/AwaitingHeartbeatResponseTag.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/PlayerHeartbeatInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/PlayerHeartbeatInitializationSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
Labels: size/L

#531 Add error messages for platforms that miss support
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityWorkerMenuGenerator.tt
Labels: size/L

#546 Move to use generalised build script
  ci/build-client.sh
  ci/build-gamelogic.sh
  ci/build-test.sh
Labels: size/M

#514 Mobile local dev: Move Core SDK version + add iOS and Android artifacts download
  spatialos.json
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Labels: size/XS

#548 fixing link to worker.json
  docs/content/set-up-new-project.md
Labels: size/XS

#552 Bugfix/build support on mac
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
Labels: size/XS

#520 Mobile local dev: Adding mobile assemblies and DeviceInfo logic
  workers/unity/Packages/com.improbable.gdk.mobile/Android.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Improbable.Gdk.Android.asmdef
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Improbable.Gdk.Android.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/AndroidDeviceInfo.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/AndroidDeviceInfo.cs.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Improbable.Gdk.Mobile.asmdef
  workers/unity/Packages/com.improbable.gdk.mobile/Improbable.Gdk.Mobile.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.mobile/iOS.meta
  workers/unity/Packages/com.improbable.gdk.mobile/iOS/Improbable.Gdk.Ios.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.mobile/iOS/Improbable.Gdk.iOS.asmdef
  workers/unity/Packages/com.improbable.gdk.mobile/iOS/Utility.meta
  workers/unity/Packages/com.improbable.gdk.mobile/iOS/Utility/iOSDeviceInfo.cs
  workers/unity/Packages/com.improbable.gdk.mobile/iOS/Utility/iOSDeviceInfo.cs.meta
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json.meta
  workers/unity/Packages/manifest.json
Labels: size/L

#324 Use lists instead of hashsets for injectable caching
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableStore.cs
Labels: size/S

#521 Mobile local dev: Adding mobile connection workers
  snapshots/default.snapshot
  workers/unity/Assets/Playground/Improbable.Playground.asmdef
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Character.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Cube.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Cube.prefab.meta
  workers/unity/Assets/Playground/Resources/Prefabs/Common/MobileConnectionSplashScreen.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Common/MobileConnectionSplashScreen.prefab.meta
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Spinner.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/AndroidClientWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/AndroidClientWorker.prefab.meta
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/IosClientWorker.prefab.meta
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/iOSClientWorker.prefab
  workers/unity/Assets/Playground/Scenes/AndroidClientScene.unity
  workers/unity/Assets/Playground/Scenes/AndroidClientScene.unity.meta
  workers/unity/Assets/Playground/Scenes/IosClientScene.unity.meta
  workers/unity/Assets/Playground/Scenes/iOSClientScene.unity
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs.meta
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs.meta
  workers/unity/Assets/Playground/Scripts/Worker/IMobileConnectionController.cs
  workers/unity/Assets/Playground/Scripts/Worker/IMobileConnectionController.cs.meta
  workers/unity/Assets/Playground/Scripts/Worker/IosClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/IosClientWorkerConnector.cs.meta
  workers/unity/Assets/Playground/TransformStrategies/AndroidClientInterpolation.asset
  workers/unity/Assets/Playground/TransformStrategies/AndroidClientInterpolation.asset.meta
  workers/unity/Assets/Playground/TransformStrategies/AndroidClientSend.asset
  workers/unity/Assets/Playground/TransformStrategies/AndroidClientSend.asset.meta
  workers/unity/Assets/Playground/TransformStrategies/iOSClientInterpolation.asset
  workers/unity/Assets/Playground/TransformStrategies/iOSClientInterpolation.asset.meta
  workers/unity/Assets/Playground/TransformStrategies/iOSClientSend.asset
  workers/unity/Assets/Playground/TransformStrategies/iOSClientSend.asset.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs.meta
  workers/unity/ProjectSettings/EditorBuildSettings.asset
Labels: size/XXL

#549 Added Dynamic in for generic component functionality
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Dynamic.meta
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/Dynamic.cs
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/Dynamic.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/IDynamicInvokable.cs
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/IDynamicInvokable.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Labels: size/XXL

#559 update tag and image
  docs/assets/unity-spatialos-menu.jpg
  docs/assets/unity-spatialos-menu.png
  docs/content/get-started/build-workers.md
  docs/content/get-started/set-up.md
Labels: size/XS

#560 fixing naming in settings
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: size/XS

#556 Upgraded package numbers to 0.1.1
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.standardlibraryutils/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: size/S

#555 Replace shader-fix.jpg with PNG variant
  docs/assets/shader-fix.jpg
  docs/assets/shader-fix.png
  docs/content/get-started/open-project.md
Labels: size/XS

#564 UTY-1363: Use SchemaObject.IndexObject instead of GetObject to remove duplicate events
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XS

#566 Update name in LICENSE.md
  LICENSE.md
Labels: size/XS

#572 Fix PR template link to contributions
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  README.md
Labels: size/XS

#557 small mobile fixes
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/ClientWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/GameLogicWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/iOSClientWorker.prefab
  workers/unity/Assets/Playground/Scenes/ClientScene.unity
  workers/unity/Assets/Playground/Scenes/GameLogicScene.unity
  workers/unity/Assets/Playground/Scenes/SampleScene.unity
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
Labels: size/M

#575 link got outdated...
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/XS

#567 Don't modify build settings scene configuration
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs
Labels: size/S

#577 Rewriting plugin postprocessor
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/AndroidDeviceInfo.cs
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/PluginPostprocessor.cs
  workers/unity/Packages/com.improbable.gdk.tools/Plugins.meta
  workers/unity/Packages/com.improbable.gdk.tools/Plugins/PluginCompatibilitySetting.cs
  workers/unity/Packages/com.improbable.gdk.tools/Plugins/PluginCompatibilitySetting.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/Plugins/PluginPostprocessor.cs
  workers/unity/Packages/com.improbable.gdk.tools/Plugins/PluginPostprocessor.cs.meta
Labels: size/XL

#573 Soft handover - now 50% less soft
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Authority/AuthorityComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/AcknowledgeAuthorityLossHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/AcknowledgeAuthorityLossHandler.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/IWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/AcknowledgeAuthorityLossSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/AcknowledgeAuthorityLossSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XXL

#579 Docs/known issues
  docs/content/get-started/open-project.md
  docs/known-issues.md
Labels: size/S

#581 Add Open Inspector Button
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
Labels: size/XS

#582 Return EntityId when adding entity to snapshot
  workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs
Labels: size/XS

#438 UTY-1082 (formerly UTY-1192) Component updated per field
  test-project/Assets/EditmodeTests/Components/BlittableComponentTests.cs
  test-project/Assets/EditmodeTests/Components/ComponentWithNoFieldsTests.cs
  test-project/Assets/EditmodeTests/Components/ComponentWithNoFieldsTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/WriterSendUpdateTests.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialComponentData.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedTransformSendSystem.cs
Labels: size/XXL

#580 Fix some typos, formatting, links etc.
  docs/content/glossary.md
Labels: size/M

#584 adding all the mobile docs
  docs/content/mobile/android/local-deploy.md
  docs/content/mobile/android/setup.md
  docs/content/mobile/android/ways-to-test.md
  docs/content/mobile/ios/local-deploy.md
  docs/content/mobile/ios/setup.md
  docs/content/mobile/ios/ways-to-test.md
  docs/content/mobile/overview.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/toc.md
Labels: size/XL

#586 Add Changelog
  CHANGELOG.md
Labels: size/M

#583 UTY-1082: Removed known issue warning related to full component updates
  docs/known-issues.md
Labels: size/S

#574 Command closures in monobehaviours
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/RequirableBase.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/XXL

#585 Revert "Workaround iOS UI input crash"
  workers/unity/Assets/Playground/Resources/Prefabs/Common/MobileConnectionSplashScreen.prefab
  workers/unity/Assets/Playground/Scenes/AndroidClientScene.unity
  workers/unity/Assets/Playground/Scenes/iOSClientScene.unity
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/UI/ResizedGui.cs
  workers/unity/Assets/Playground/Scripts/UI/ResizedGui.cs.meta
Labels: size/XXL

#570 fixing up formatting and reword some headers
  docs/content/get-started/set-up.md
  docs/content/intro-reference.md
  docs/content/set-up-new-project.md
  docs/toc.md
Labels: size/S

#588 splitting worker connector into standalone and mobile
  CHANGELOG.md
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
Labels: size/L
