Repository spatialos/gdk-for-unity, pull requests merged in 2018-09, with the labels that each got.

#292 fixing reconnect and ensuring that worker type is set
  workers/unity/Assets/Playground/Scripts/Worker/WorkerConnectorBase.cs
Labels: size/XS

#294 Move initialization into Core and adding DisableAutoCreation tag
  workers/unity/Assets/Playground/Scripts/OneTimeInitialisation.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManagerInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerDisconnectCallbackSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/WorldsInitializationHelper.cs
  workers/unity/Packages/com.improbable.gdk.core/WorldsInitializationHelper.cs.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.testutils/DisableAutoCreationSystemsTests.cs
  workers/unity/Packages/com.improbable.gdk.testutils/DisableAutoCreationSystemsTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ApplyTransformUpdatesSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/LocalTransformSyncSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/PositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TransformSendSystem.cs
Labels: size/L

#298 Disable QOS timeout
  default_launch.json
Labels: size/XS

#297 Destroy game objects upon destroying the world
  workers/unity/Assets/Playground/Scripts/EntityInitialization/EntityGameObjectCreator.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
Labels: size/S

#300 fixing code example
  docs/content/temporary-components.md
Labels: size/XS

#302 Fixed log typo: create -> created a.
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: size/XS

#307 Added entities package version and shortened error message
  docs/README.md
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
Labels: size/XS

#306 removing CoreSystemHelper as its not used anymore
  workers/unity/Packages/com.improbable.gdk.core/CoreSystemHelper.cs
  workers/unity/Packages/com.improbable.gdk.core/CoreSystemHelper.cs.meta
Labels: size/S

#311 Remove Offset from Client Worker
  workers/unity/Assets/Playground/Scenes/ClientScene.unity
Labels: size/XS

#286 Make GDK Tool Paths Configurable
  workers/unity/Assets/Config.meta
  workers/unity/Assets/Config/GdkToolsConfiguration.asset
  workers/unity/Assets/Config/GdkToolsConfiguration.asset.meta
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/com.improbable.gdk.tools/ScriptableGdkToolsConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.tools/ScriptableGdkToolsConfiguration.cs.meta
Labels: size/XL

#319 UTY-1143: Make Monobehaviour Base Classes Public
  workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/IInjectableCreator.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableStore.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectionConditionAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiredFieldInjector.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/GameObjectDelegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
Labels: size/S

#288 UTY-835; Invalidate deinjected requirables
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManagerInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiredFieldInjector.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiresMonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiresMonoBehaviourActivationManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/RequirableBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/RequirableBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/EntityGameObjectLinkerTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/XXL

#313 moving prefab preprocessor from playground to GameObjectRepresentation
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Improbable.Gdk.Core.GameObjectRepresentation.Editor.asmdef
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Improbable.Gdk.Core.GameObjectRepresentation.Editor.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs/PrefabPreprocessor.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs/PrefabPreprocessor.cs.meta
Labels: size/S

#309 Updating the coding standards
  docs/contributions/unity-gdk-coding-standards.md
Labels: size/S

#312 Cleanup Legacy Package
  ci/build-client.sh
  ci/build-gamelogic.sh
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset.meta
  workers/unity/Assets/Playground/Editor/Improbable.Playground.Editor.asmdef
  workers/unity/Packages/com.improbable.gdk.buildsystem/BuildSystemMenu.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/BuildSystemMenu.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironment.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironment.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironmentConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironmentConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildPaths.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildPaths.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/GUIColorScope.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/GUIColorScope.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/PlayerCompression.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/PlayerCompression.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SceneItem.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SceneItem.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObjectLoader.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObjectLoader.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialBuildPlatforms.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialBuildPlatforms.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfiguration.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildConfiguration.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerPlatform.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerPlatform.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Improbable.Gdk.BuildSystem.asmdef
  workers/unity/Packages/com.improbable.gdk.buildsystem/Improbable.Gdk.BuildSystem.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildConfigNames.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildConfigNames.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorPaths.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorPaths.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/PathUtil.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/PathUtil.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/UnityPathUtil.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/UnityPathUtil.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json.meta
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem.meta
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Improbable.Gdk.Legacy.BuildSystem.asmdef
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Improbable.Gdk.Legacy.BuildSystem.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.legacy/Improbable.Gdk.Legacy.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.legacy/package.json
  workers/unity/Packages/manifest.json
Labels: size/M

#317 Added warning if local worker connection fails. Added mitigation advice to Core SDK download failure.
  workers/unity/Assets/Playground/Scripts/Worker/WorkerConnectorBase.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/XS

#315 Made Archetype init an optional feature - removed related error logs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/ArchetypeInitializationSystem.cs
Labels: size/S

#320 Add tags properly
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/L

#310 UTY-329: Stop the game in the editor during compilation.
  workers/unity/Assets/Playground/Editor/DisconnectOnCompilation.cs
  workers/unity/Assets/Playground/Editor/DisconnectOnCompilation.cs.meta
Labels: size/M

#308 changing name to SpatialOS GDK for Unity
  README.md
  docs/README.md
  docs/content/authority.md
  docs/content/code-generator.md
  docs/content/commands.md
  docs/content/component-data.md
  docs/content/create-entity.md
  docs/content/custom-replication-system.md
  docs/content/entity-checkout-process.md
  docs/content/events.md
  docs/content/faqs/key-features.md
  docs/content/logging.md
  docs/content/reactive-components.md
  docs/content/system-update-order.md
  docs/content/temporary-components.md
  docs/content/testing/how-to-run-tests.md
  docs/content/testing/testing-guidelines.md
  docs/content/testing/testing-overview.md
  docs/content/testing/writing-a-new-unit-test.md
  docs/contributions/unity-gdk-coding-standards.md
  docs/known-issues.md
  docs/setup-and-installing.md
Labels: size/XL

#285 adding known issue about il2cpp
  docs/known-issues.md
Labels: size/XS

#314 Implement world command sending
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableId.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: size/XL

#322 escape potential path
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
Labels: size/XS

#327 docs/TC93-licence-clarity
  README.md
Labels: size/XS

#318 Making set up of game object initialization simpler
  workers/unity/Assets/Playground/Scripts/EntityInitialization/ArchetypeInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Assets/Playground/Scripts/UpdateGroups.cs
  workers/unity/Assets/Playground/Scripts/UpdateGroups.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectReferenceHandle.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectReferenceHandle.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectRepresentationSystemHelper.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/EntityGameObjectLinkerTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreatorFromMetadata.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/IEntityGameObjectCreator.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/SpatialOSEntity.cs
Labels: size/XL

#325 removing EntityManager Extensions
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs.meta
Labels: size/M

#331 fixing update order of game object initialization
  workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
Labels: size/XS

#332 use TryGetValue instead of simple assign
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
Labels: size/XS

#329 Implement entity query sending and responses
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs
Labels: size/M

#333 Fix Short Circuiting Update
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/FieldTypes.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
Labels: size/XXL

#335 Fix a few problems I encountered during dogfooding
  workers/unity/Packages/com.improbable.gdk.buildsystem/BuildSystemMenu.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
Labels: size/S

#328 Add doc 'Building workers and deploying your game'
  docs/content/build-and-deploy.md
  docs/content/snapshots.md
Labels: size/M

#338 Added reading and writing component data
  docs/content/gameobject/reading-and-writing-component-data.md
Labels: size/L

#326 Add doc 'Setting up a new project'
  docs/content/set-up-new-project.md
Labels: size/M

#339 Added worker docs
  docs/content/ecs/accessing-worker-info.md
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/content/workers.md
Labels: size/M

#340 small fixes
  docs/README.md
  docs/content/set-up-new-project.md
Labels: size/XS

#341 Docs signposting quick fix: Don't recommend custom config for beginners
  docs/README.md
Labels: size/XS

#343 Fixed formatting issues with new .md docs
  docs/content/ecs/accessing-worker-info.md
  docs/content/gameobject/reading-and-writing-component-data.md
Labels: size/L

#342 UTY-1176: Code Generation Workflow Tweaks
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Labels: size/S

#348 Removing phrase about WIP GDocs links not autoupdating
  docs/content/ecs/entity-checkout-process.md
  docs/content/gameobject/logging-and-accessing-the-worker.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/sending-receiving-events.md
  docs/content/gameobject/set-up-gameobjects.md
  docs/content/gameobject/world-commands.md
Labels: size/S

#345 Renamed Requirables to Requirable
  test-project/Assets/EditmodeTests/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CheckForPlayerCollision.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CubeSpawnerInputBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/DeleteCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/RotationBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SyncBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/UpdateSpinnerColor.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandResponseHandler.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/L

#356 Formatting fixes
  docs/setup-and-installing.md
Labels: size/XS

#347 Docs - Rename SpatialOS[schemalangname] -> [schemalangname].Component
  docs/content/ecs/authority.md
  docs/content/ecs/component-data.md
  docs/content/ecs/custom-replication-system.md
  docs/content/ecs/reactive-components.md
  docs/content/ecs/system-update-order.md
Labels: size/M

#350 Made the Readme.md considerably terser.
  README.md
Labels: size/M

#357 More terse docs toc. Added link to main readme.
  README.md
  docs/README.md
Labels: size/M

#344 UTY-1121: Made a refinement pass over the component data read/write docs
  docs/content/gameobject/reading-and-writing-component-data.md
Labels: size/M

#351 Clients retry getting a player. Workers connecting one at a time is enforced
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/WorkerConnectorBase.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/ShouldRequestPlayerTag.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/ShouldRequestPlayerTag.cs.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Labels: size/M

#358 Fix creating entities doc
  docs/content/ecs/commands.md
  docs/content/ecs/create-entity.md
  docs/content/ecs/reactive-components.md
Labels: size/S

#353 UTY-1105: Refined error message
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiredFieldInjector.cs
Labels: size/XS

#352 UTY-1125: Renamed title from Logging and accessing the worker to SpatialOSComponent utility API
  docs/README.md
  docs/content/gameobject/logging-and-accessing-the-worker.md
  docs/content/gameobject/retrieving-your-entityid-and-accessing-the-worker.md
Labels: size/XS

#349 Fix logging docs
  docs/content/ecs/commands.md
  docs/content/ecs/create-entity.md
  docs/content/ecs/logging.md
  docs/content/ecs/reactive-components.md
Labels: size/S

#361 Add explicit save button to tools config
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
Labels: size/XS

#359 Prevent invalid game objects from breaking injection
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
Labels: size/S

#363 quick fix for warnings in transforms
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
Labels: size/XS

#364 Tidying
  workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/DisconnectSystem.cs
  workers/unity/Assets/Playground/Scripts/Metrics/MetricSendSystem.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/RotationBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs
  workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs
  workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs
  workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectWorldCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableFactory.cs
  workers/unity/Packages/com.improbable.gdk.core/WorldsInitializationHelper.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.testutils/DisableAutoCreationSystemsTests.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultTransformInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/PositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TakeRawTransformUpdateSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickRateEstimationSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TransformSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/UpdatePositionSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/UpdateTransformSystem.cs
Labels: size/L

#368 Updated docs to use command new syntax
  docs/content/ecs/commands.md
Labels: size/XS

#360 Adding iOS Worker SDK script support
  workers/unity/Assets/Plugins/Improbable/Sdk/Improbable.WorkerCoreStatic.dll
  workers/unity/Assets/Plugins/Improbable/Sdk/Improbable.WorkerCoreStatic.dll.meta
  workers/unity/Assets/Plugins/Improbable/Sdk/Improbable.WorkerCoreStatic.xml
  workers/unity/Assets/Plugins/Improbable/Sdk/Improbable.WorkerCoreStatic.xml.meta
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Labels: size/XXL

#374 Changed tick system dependencies
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
Labels: size/XS

#372 Convert command sending to use archetype chunks
  test-project/Assets/Generated/Improbable.Gdk.Generated.asmdef
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  test-project/ProjectSettings/EditorSettings.asset
  workers/unity/Assets/Generated/Improbable.Gdk.Generated.asmdef
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XXL

#373 Fixed bug of Writers not having callbacks for events, field updates
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterUpdateTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterUpdateTests.cs.meta
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/M

#378 Tweak Setup Guide for .NET Core
  docs/setup-and-installing.md
Labels: size/XS

#330 UTY-1098: Unit Tests for Receive System
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/InvalidSpatialEntityStateException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/InvalidSpatialEntityStateException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/UnknownComponentIdException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/UnknownComponentIdException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/UnknownRequestIdException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/UnknownRequestIdException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSReceiveSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSReceiveSystemTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.testutils/TestLogDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.testutils/TestLogDispatcher.cs.meta
  workers/unity/Packages/com.improbable.gdk.testutils/WorkerOpFactory.cs
  workers/unity/Packages/com.improbable.gdk.testutils/WorkerOpFactory.cs.meta
Labels: size/XXL

#367 UTY-1112: Fix List, Map, Option Serialization/Deserialization
  schema/playground/cube_spawner.schema
  spatialos.json
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CubeSpawnerInputBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/DeleteCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentDataGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/FieldTypes.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/PositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TransformSendSystem.cs
Labels: size/XXL

#379 Update commands docs take 2
  docs/README.md
  docs/content/ecs/commands.md
Labels: size/XS

#380 Upgrading to entities package 13
  docs/README.md
  docs/known-issues.md
  test-project/Packages/manifest.json
  workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Metrics/MetricSendSystem.cs
  workers/unity/Assets/link.xml
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickRateEstimationSystem.cs
  workers/unity/Packages/manifest.json
Labels: size/M

#383 UTY-1188: Cleanup the Cleanup System
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSReceiveSystemTests.cs
Labels: size/M

#385 UTY-1099: Add Unit Tests to SpatialOS Send System
  workers/unity/Packages/com.improbable.gdk.core/Attributes/DisableAutoRegisterAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/Attributes/DisableAutoRegisterAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs.meta
Labels: size/L

#388 Remove "Find Unity" csproj
  tools/FindUnity/FindUnity.csproj
  tools/FindUnity/Program.cs
  tools/Tools.sln
Labels: size/M

#375 Small clarification to logging docs
  docs/content/ecs/logging.md
Labels: size/XS

#389 Do not log empty lines from process outputs
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Labels: size/S

#381 test-project: Rename assembly and namespace to remove ".Generated" section
  test-project/Assets/EditmodeTests/GameObjectRepresentation/CommandSenders/CommandRequestHandlerTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderAuthorityTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderDataTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterUpdateTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/WriterSendUpdateTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
  test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef
  test-project/Assets/EditmodeTests/Improbable.Gdk.EditmodeTests.asmdef.meta
  test-project/Assets/Generated/AssemblyInfo.cs
Labels: size/S

#369 Separate create entity doc into entity template and world commands.
  docs/README.md
  docs/content/ecs/commands.md
  docs/content/ecs/create-entity.md
  docs/content/ecs/world-commands.md
  docs/content/entity-templates.md
Labels: size/XL

#390 small fix for UnlinkGameObjectFromEntity
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
Labels: size/S

#393 Known Issue: `bool` is not blittable.
  docs/known-issues.md
Labels: size/XS

#370 Add tests to validate authority effects on monobehaviours
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/AuthorityRequiredBehaviourActivationTestsBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/AuthorityRequiredBehaviourActivationTestsBase.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/CommandHandlerBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/CommandHandlerBehaviourActivationTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/MultipleBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/MultipleBehaviourActivationTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReaderBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReaderBehaviourActivationTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReadersAndWriterBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReadersAndWriterBehaviourActivationTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/RequestSenderBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/RequestSenderBehaviourActivationTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WriterBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WriterBehaviourActivationTests.cs.meta
  test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
Labels: size/XL

#396 UTY-1234: helper methods to determine if entity is on worker
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
Labels: size/XS

#402 UTY-1162: flattened op fields into world command response types
  docs/known-issues.md
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/DeleteCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorldCommandRequestSender.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSReceiveSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
Labels: size/M

#366 Reimplement `WorkerType` attribute from SDK
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WorkerTypeActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WorkerTypeActivationTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Editor/Prefabs/PrefabPreprocessor.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/RequiredFieldInjector.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorkerTypeAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/WorkerTypeAttribute.cs.meta
Labels: size/L

#404 UTY-1173: update the warning message on entity query request creation
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
Labels: size/XS

#384 Update Generated Code Logs and Exceptions
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XXL

#403 UTY-1102: Added way to link GameObject to the Worker entity
  workers/unity/Assets/Playground/Improbable.Playground.asmdef
  workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreationSystemHelper.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Improbable.Gdk.GameObjectCreation.asmdef
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/WorkerEntityLinkingTests.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/WorkerEntityLinkingTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/WorkerEntityGameObjectLinkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/WorkerEntityGameObjectLinkerSystem.cs.meta
Labels: size/L

#406 Moved the worker connection base to the core
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnectorBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnectorBase.cs.meta
Labels: size/S

#400 [WIP]Feature/uty 1063 shared common schema types
  schema/playground/collisions.schema
  schema/playground/cube_spawner.schema
  schema/playground/empty.schema
  schema/playground/spinner_rotation.schema
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CheckForPlayerCollision.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CubeSpawnerInputBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/DeleteCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Packages/com.improbable.gdk.core/Schema.meta
  workers/unity/Packages/com.improbable.gdk.core/Schema/common.schema
  workers/unity/Packages/com.improbable.gdk.core/Schema/common.schema.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/player_creator.schema
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/player_heartbeat.schema
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
Labels: do-not-merge/work-in-progress, size/M

#391 UTY-1166: Menu item for additional Unity clients
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
Labels: size/L

#397 UTY-1182: adding TryGetGameObjectForEntity to SpatialOSComponent
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSComponentTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSComponentTests.cs.meta
Labels: size/M

#392 Move the Configuring your project section higher.
  docs/README.md
Labels: size/S

#411 Upgrade to 2018.2.8f1
  ci/UnityEditorHash.txt
  test-project/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/ProjectVersion.txt
Labels: size/XS

#409 Add explanation of worker origin in worker prefabs
  docs/content/workers.md
Labels: size/XS

#413 Report correct load metric if target frame rate is -1.
  workers/unity/Assets/Playground/Scripts/Metrics/MetricSendSystem.cs
Labels: size/XS

#415 UTY-1174: Added missing commands parameters (context, timeout) to MonoBehavior API
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsMonoBehaviourCommandHandlers.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
Labels: size/M

#395 Removed deploy.sh & added info regarding cloud deployment
  deploy.sh
  docs/README.md
  docs/content/build-and-deploy.md
  docs/content/build.md
  docs/content/deploy.md
  docs/content/snapshots.md
Labels: size/L

#414 Moved all the fixed update systems to fixed update
  workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickRateEstimationSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
Labels: size/XS

#408 Replace `world.GetOrCreateManager<WorkerSystem>()` by `world.GetExistingManager<WorkerSystem>()`
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreationSystemHelper.cs
Labels: size/S

#412 adding TryGetSpatialOSEntityIdForGameObject
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSComponentTests.cs
Labels: size/L

#377 Add Profiling markers
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
Labels: size/XXL

#417 Fix empty command warning about unreachable code
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/L

#405 UTY-1215: entity builder helpers in feature modules
  docs/content/entity-templates.md
  snapshots/default.snapshot
  workers/unity/Assets/Playground/Config/CubeTemplate.cs
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Config/WorkerUtils.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectRepresentationHelper.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectRepresentationHelper.cs.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreationHelper.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreationHelper.cs.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/WorkerEntityLinkingTests.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs.meta
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Config.meta
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Config/TransformSynchronizationConfig.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Config/TransformSynchronizationConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/TransformSynchronizationHelper.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/TransformSynchronizationHelper.cs.meta
Labels: size/L

#336 Add WorkType is a well known field for LogEvents
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingUtils.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.testutils/TestLogDispatcher.cs
Labels: size/M

#418 Unify Test Namespaces
  .gitignore
  test-project/Assets/EditmodeTests/Components/BlittableComponentTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/CommandSenders/CommandRequestHandlerTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ActivationManagerTestBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/AuthorityRequiredBehaviourActivationTestsBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/CommandHandlerBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/MultipleBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReaderBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/ReadersAndWriterBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/RequestSenderBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WorkerTypeActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/MonoBehaviourActivationManager/WriterBehaviourActivationTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/EventTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderAuthorityTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderDataTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/ReaderWriterUpdateTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/WriterSendUpdateTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/RequiredFieldInjectorTests.cs
Labels: size/M

#427 mentioning entity logging
  docs/content/ecs/logging.md
Labels: size/XS

#430 Mac Osascript Regression Fix
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
Labels: size/XS

#432 the game logic worker didn't have the level prefab attached to it any…
  workers/unity/Assets/Playground/Scenes/GameLogicScene.unity
Labels: size/XS

#431 delete UpdateGroups.cs as it is unused
  workers/unity/Assets/Playground/Scripts/UpdateGroups.cs
  workers/unity/Assets/Playground/Scripts/UpdateGroups.cs.meta
Labels: size/XS

#434 Docfix: Added missing bracket
  docs/content/deploy.md
Labels: size/XS

#436 UTY-1231: Add known issue to componentupdated
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/known-issues.md
Labels: size/S

#437 Bugfix: Errors when destroying scene with linked worker entity
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/WorkerEntityGameObjectLinkerSystem.cs
Labels: size/XS

#435 Removed redundancy from EntityGameObjectLinker method signature
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/EntityGameObjectLinkerTests.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/WorkerEntityGameObjectLinkerSystem.cs
Labels: size/S
