Repository spatialos/gdk-for-unity, pull requests merged in 2018-12, with the labels that each got.

#644 Fixing launch configuration for OSX
  CHANGELOG.md
  workers/unity/spatialos.UnityClient.worker.json
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: size/XS

#647 UTY-1536: Upgrade Worker SDK version
  CHANGELOG.md
  spatialos.json
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/SomeType.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/TypeName.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/RandomDataType.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstEventPayload.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondEventPayload.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/Empty.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstEventPayload.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Dispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Labels: size/L

#645 Adding support for launching an android client over ADB from the editor
  workers/unity/Assets/Config/GdkToolsConfiguration.json
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/CommandLineUtility.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/LaunchArguments.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/LaunchArguments.cs.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Editor.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/Improbable.Gdk.Mobile.Editor.asmdef
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/Improbable.Gdk.Mobile.Editor.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
  workers/unity/ProjectSettings/GraphicsSettings.asset
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: size/L

#646 Refactored connection configuration & added alpha locator flow
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Config/LocatorConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/LocatorConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Config/ReceptionistConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ReceptionistConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/LocatorConfigTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/LocatorConfigTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/ReceptionistConfigTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/ReceptionistConfigTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
Labels: size/XXL

#650 Subscriptions fixes
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/EntitySubscriptionManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Subscription.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/RequireLifecycleSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/UpdateGroups.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/UpdateGroups.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt
Labels: size/M

#656 Add cmd option to choose il2cpp/mono in build tests
  ci/build-test.sh
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: size/M

#651 Adding script for distributable iOS builds
  ci/build-ios.sh
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: size/S

#659 add skills warning
  docs/content/get-started/get-started.md
  docs/content/get-started/set-up.md
  docs/get-started.md
Labels: size/M

#663 Removing unused CI scripts
  README.md
  ci/create-windows-image.ps1
  ci/prepare-unity.sh
Labels: size/M

#664 track link for zip dwnld
  docs/content/get-started/set-up.md
Labels: size/XS
