Repository spatialos/gdk-for-unity, pull requests merged in 2018-07, with the labels that each got.

#127 Merge latest master commits to experimental branch
  ci/UnityEditorHash.txt
  ci/codegen.sh
  ci/prepare-unity.sh
  ci/test.sh
  code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  code_generator/GdkCodeGenerator/src/CodeGenerator.cs
  code_generator/GdkCodeGenerator/src/CodeGeneratorOptions.cs
  docs/README.md
  docs/content/logging.md
  docs/setup-and-installing.md
  workers/unity/Assets/Playground/Scenes/SampleScene.unity
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/ArchetypeInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityClient.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityGameLogic.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Error/IdType.cs
  workers/unity/Packages/com.improbable.gdk.core/Error/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging.meta
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingUtils.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingUtils.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ViewCommandBuffer.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/WorkerBuilder.cs
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/ProjectVersion.txt
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: size/XL

#130 Rebase onto master
  code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  docs/README.md
  docs/content/logging.md
  workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/WorkerBuilder.cs
Labels: size/M

#120 UTY-590: SpatialOSBehaviourLibrary
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ComponentIdAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ComponentIdAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderInterfaceAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderInterfaceAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderWriterFactory.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderWriterFactory.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/RequireAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/RequireAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourLibrary.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourLibrary.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/WriterInterfaceAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/WriterInterfaceAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSBehaviourLibraryTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSBehaviourLibraryTests.cs.meta
Labels: size/XL

#132 Added IP caching to remember the last IP connected to
  workers/unity/Assets/Playground/Scripts/Player/ConnectButtonClickSystem.cs
Labels: size/XS

#131 fixing shell scripts
  ci/build-test.sh
  ci/test.sh
  tools/RunUnity/Program.cs
  workers/unity/Packages/manifest.json
Labels: size/XS

#133 UTY-709 Add interfaces to be used by MonoBehaviours
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialComponentUpdate.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Delegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Delegates.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReader.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReader.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderInternal.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderInternal.cs.meta
Labels: size/M

#128 [Experimental][CSharp Core SDK] Blittable list and map
  workers/unity/Packages/com.improbable.gdk.core/Collections.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableList.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableList.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableMap.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableMap.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableString.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableString.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/CollectionProvider.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/CollectionProvider.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/HandleProvider.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/HandleProvider.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/StringProvider.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/StringProvider.cs.meta
Labels: size/XL

#138 Minor doc fixes.
  docs/content/authority.md
  docs/content/commands.md
  docs/content/component-data.md
  docs/content/create-entity.md
  docs/content/custom-replication-system.md
  docs/content/events.md
  docs/content/logging.md
  docs/content/reactive-components.md
  docs/setup-and-installing.md
Labels: size/S

#137 UTY-700: Touch Screen Controls
  workers/unity/Assets/Playground/Scenes/SampleScene.unity
  workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs
  workers/unity/Assets/Playground/Scripts/Player/VirtualJoystick.cs
  workers/unity/Assets/Playground/Scripts/Player/VirtualJoystick.cs.meta
  workers/unity/ProjectSettings/ProjectSettings.asset
  workers/unity/ProjectSettings/TagManager.asset
Labels: size/XL

#129 [Core C# SDK] UTY-697 Part 1: Add Serialization Methods to Types and Components
  ci/codegen.sh
  code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  code_generator/GdkCodeGenerator/src/CodeGenerator.cs
  code_generator/GdkCodeGenerator/src/CodeGeneratorOptions.cs
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentConversionGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentDataGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityTypeContentPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/SchemaFunctionMappings.cs
  code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
Labels: size/XL

#148 Misc Cleanup
  .gitignore
  ci/download-core-sdk.sh
  tools/schema_compiler/macos/proto/google/protobuf/descriptor.proto
  tools/schema_compiler/macos/proto/improbable/entity_state.proto
  tools/schema_compiler/macos/protoc
  workers/unity/ProjectSettings/UnityConnectSettings.asset
Labels: size/XXL

#147 Fix small doc typos in commands.
  docs/content/commands.md
Labels: size/XS

#135 UTY-708: Add Scoring to the Playground
  schema/playground/launcher.schema
  schema/playground/score.schema
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Resources/Prefabs/Cube.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/CubeKinematic.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/UIGameObject.prefab
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs.meta
  workers/unity/Assets/Playground/Scripts/Cubes/ScoreCollision.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ScoreCollision.cs.meta
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs.meta
  workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs
  workers/unity/Assets/Playground/Scripts/UI/UIComponent.cs
  workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityGameLogic.cs
  workers/unity/ProjectSettings/TagManager.asset
Labels: size/XL

#144 Extract SetComponentObject into an extension method
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs.meta
Labels: size/M

#134 UTY-622 Enable alternative with no flag
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Worker/WorkerBaseTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: size/M

#123 UTY-622 Allow `spatial local worker launch` and reconnections
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityClient.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityGameLogic.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Worker/WorkerBaseTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerRegistry.cs
  workers/unity/spatialos.UnityClient.worker.json
  workers/unity/spatialos.UnityGameLogic.worker.json
Labels: size/M

#121 UTY-587: GameObjectComponentDispatchers
  code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj
  code_generator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityGameObjectComponentDispatcherGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs
  workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectReference.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectReferenceHandle.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectReferenceHandle.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/RequiresSpatialOSBehaviourManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/RequiresSpatialOSBehaviourManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManagerInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManagerInitializationSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/UpdateGroups.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/GameObjectDispatcherSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/GameObjectDispatcherSystemTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
Labels: size/XL

#152 UTY-792 Implement stubs for the reader classes
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentGenerator.tt
  workers/unity/Packages/com.improbable.gdk.core/AssemblyInfo.cs
Labels: size/M

#141 UTY-709 reader writer interfaces v2
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialComponentUpdate.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Delegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/Delegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/Delegates.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReader.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReader.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReaderInternal.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReaderInternal.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderInterfaceAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderInterfaceAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourLibrary.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/IWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/IWriter.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/WriterInterfaceAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/WriterInterfaceAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSBehaviourLibraryTests.cs
Labels: size/M

#149 Allow exception messages to be passed into Unity's logger properly
  docs/content/logging.md
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs.meta
Labels: size/L

#156 UTY-473: Fix Dotnet Path for Mac TC Agents
  ci/includes/pinned-tools.sh
Labels: size/XS

#161 Amend Setup Guide
  docs/setup-and-installing.md
Labels: size/XS

#160 UTY-831: Draw playground cubes in batches
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
Labels: size/S
