Repository spatialos/gdk-for-unity, pull requests merged in 2018-08, with the labels that each got.

#157 Remove unnecessary "for SpatialOS local deployment only" callout.
  docs/setup-and-installing.md
Labels: size/XS

#163 [Core C# SDK] UTY-719: Refactor Entity Builder
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityComponentDetails.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/UnityTypeMappings.cs
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityGameLogic.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs.meta
  workers/unity/Packages/com.improbable.gdk.legacy/EntityBuilder.cs
Labels: size/XL

#168 Add product name to title
  docs/content/faqs/faqs.md
Labels: size/XS

#164 Merge master into feature/monobehaviour-support-shared
  ci/includes/pinned-tools.sh
  docs/content/logging.md
  docs/setup-and-installing.md
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs.meta
Labels: size/L

#169 fix semantic merge
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityComponentDetails.cs
Labels: size/XS

#159 UTY-588: Reader/Writer injection logic (SpatialOSBehaviourManager)
  code_generator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderWriterFactory.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourLibrary.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManagerInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSBehaviourLibraryTests.cs
Labels: size/L

#170 [Core C# SDK] - Extra Parenthesis
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Labels: size/XS

#162 UTY-723: ReaderWriterFactory
  code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityReaderWriterGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ComponentIdAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderWriterCreator.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderWriterCreator.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderWriterFactory.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourLibrary.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManagerInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSBehaviourLibraryTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Worker/WorkerRegistryTest.cs
Labels: size/XXL

#158 Update setup-and-installing.md
  docs/setup-and-installing.md
Labels: size/XS

#172 Bugfix: Require Internet Access on Android
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: size/XS

#174 Removing functionality from the Mutable View
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ViewCommandBuffer.cs
Labels: size/L

#176 Fixed issues with our .gitignore
  .gitignore
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentEvents.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstEventPayload.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondEventPayload.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstEventPayload.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentEvents.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
Labels: size/XXL

#171 Remove references to DemoGame in docs.
  docs/content/commands.md
  docs/content/custom-replication-system.md
  docs/content/entity-checkout-process.md
  docs/content/events.md
Labels: size/S

#173 UTY-589: Invoking callbacks on the readers
  code_generator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
Labels: size/XXL

#179 Deleting Mutable View for good
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ConnectionConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/MutableView.meta
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ViewCommandBuffer.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/SpatialOSWorld.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/SpatialOSWorld.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerRegistry.cs
Labels: size/XXL

#175 UTY-792 Implement writer stubs and replace IReaderInternal interface …
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Assets/Generated/AssemblyInfo.cs
  workers/unity/Assets/Generated/AssemblyInfo.cs.meta
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/IReaderWriterCreator.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReaderWriterFactory.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReader.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReaderInternal.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReaderWriterInternal.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourLibrary.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManager.cs
Labels: size/L

#183 UTY-418: Add system update order docs.
  docs/README.md
  docs/assets/update-order.png
  docs/content/logging.md
  docs/content/system-update-order.md
Labels: size/L

#166 UTY-709 Implement base and tests for the component readers
  code_generator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/AuthorityComponentNotFoundException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/AuthorityComponentNotFoundException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/BlittableReaderBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/BlittableReaderBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReaderWriterInternal.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/NonBlittableReaderBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/NonBlittableReaderBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderDataGetFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderDataGetFailedException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderAuthorityTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderAuthorityTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderDataTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderDataTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderUpdateTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderUpdateTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Improbable.Gdk.Core.EditmodeTests.asmdef
  workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
Labels: size/XXL

#181 Add Known issues, remove Mac Support warnings
  README.md
  docs/content/faqs/faqs.md
  docs/known-issues.md
Labels: size/S

#182 UTY 838: Abstract controller systems
  workers/unity/Assets/Playground/Config/ArchetypeConfig.cs
  workers/unity/Assets/Playground/Scenes/SampleScene.unity
  workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/LocalInput.cs
  workers/unity/Assets/Playground/Scripts/Player/LocalInput.cs.meta
  workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs
  workers/unity/Assets/Playground/Scripts/Player/MobilePlayerInputSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/MobilePlayerInputSystem.cs.meta
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerInputSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerInputSystem.cs.meta
  workers/unity/Assets/Playground/Scripts/Workers/UnityClient.cs
  workers/unity/ProjectSettings/TagManager.asset
Labels: size/L

#185 UTY-765: Remove Blittable Types
  workers/unity/Packages/com.improbable.gdk.core/Collections.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableList.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableList.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableMap.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableMap.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableString.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/BlittableString.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/CollectionProvider.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/CollectionProvider.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/HandleProvider.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/HandleProvider.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Collections/StringProvider.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/StringProvider.cs.meta
Labels: size/L

#191 UTY-851: Use a mobile-friendly shader
  workers/unity/Assets/Playground/Resources/Materials/BlackMaterial.mat
  workers/unity/Assets/Playground/Resources/Materials/Cube.mat
  workers/unity/Assets/Playground/Resources/Materials/CubeKinematic.mat
  workers/unity/Assets/Playground/Resources/Shaders.meta
  workers/unity/Assets/Playground/Resources/Shaders/Simple-Diffuse.shader
  workers/unity/Assets/Playground/Resources/Shaders/Simple-Diffuse.shader.meta
Labels: size/M

#186 UTY-541: Codegen Readers handling component updates
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/BlittableReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReader.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/NonBlittableReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderAuthorityTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderDataTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderUpdateTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/ReaderWriterTestsBase.cs
Labels: size/XXL

#193 Always create update structs for all components even if they have no fields
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentGenerator.tt
  schema/improbable/gdk/tests/empty_component.schema
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsEvents.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/Empty.cs
Labels: size/XXL

#189 UTY-543: Implemented sending component updates through writers
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/BlittableReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/BlittableReaderWriterBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/NonBlittableReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/NonBlittableReaderWriterBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderDataGetFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderWriterBase.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/IWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/WriterDataUpdateFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/WriterDataUpdateFailedException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/WriterSendUpdateTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/Readers/WriterSendUpdateTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/SpatialOSBehaviourLibraryTests.cs
Labels: size/XXL

#195 Fixed bugs and added rotating slab to playground to test
  code_generator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  snapshots/default.snapshot
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Playground/Config/ArchetypeConfig.cs
  workers/unity/Assets/Playground/Config/PrefabConfig.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Resources/Prefabs/RotatingCuboid.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/RotatingCuboid.prefab.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/RotationBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/RotationBehaviour.cs.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SyncBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SyncBehaviour.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSBehaviourManager.cs
Labels: size/XXL

#198 Quickfix for playground monobehaviour prefab
  workers/unity/Assets/Playground/Resources/Prefabs/RotatingCuboid.prefab
Labels: size/XS

#196 Playground Mobile Controls: Increased virtual stick size
  workers/unity/Assets/Playground/Scenes/SampleScene.unity
Labels: size/XS

#187 UTY-541 Add event delegates into ReaderWriter Codegen
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderWriterBase.cs
Labels: size/XL

#200 UTY 845 snapshot generator upgrade
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  workers/unity/Assets/Playground/Config/ArchetypeConfig.cs
  workers/unity/Assets/Playground/Editor/Improbable.Playground.Editor.asmdef
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGeneratorWindow.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs.meta
Labels: size/XL

#199 Simplify reader/writer classes
  code_generator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/IReader.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Readers/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Writers/IWriter.cs
Labels: size/M

#203 Feature/gdk.core cleanup
  ReSharper2017.DotSettings
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Attributes/RemoveAtEndOfTickAttribute.cs
  workers/unity/Packages/com.improbable.gdk.core/Attributes/RemoveAtEndOfTickAttribute.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Components/CommandPayloads.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ComponentPool.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/MessageSenders.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/Option.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ReactiveComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ReceptionistConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/ScriptableWorkerConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LogEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingUtils.cs
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Components/BlittableComponentTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Components/NonBlittableComponentTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Components/OptionTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/LocatorConfigTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Config/ReceptionistConfigTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/EntityGameObjectLinkerTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/CommandLineUtilityTest.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/BlittableBool.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/CommandLineUtility.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ConnectionUtility.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityManagerExtensions.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerRegistry.cs
  workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/PositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TransformSendSystem.cs
Labels: size/XXL

#208 UTY-844 events in core
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityEventGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderContent.tt
  code_generator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
  code_generator/GdkCodeGenerator/dependencies/CodeGenerator.dll
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityReferenceTypeProviderGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityEventDetails.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/UnitySchemaFile.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentCleanupHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
Labels: size/L

#209 UTY-554: Local Android workflow docs
  README.md
  docs/content/mobile/android-local.md
  workers/unity/Packages/com.improbable.gdk.android/Editor/AndroidSpatialRunner.cs
Labels: size/M

#207 UTY-756: Commands API v2 Code Generation
  code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj
  code_generator/GdkCodeGenerator/Templates/UnityCommandComponentsGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityCommandStorageGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandComponentsGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandStorageGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityReferenceTypeProviderGeneratorPart.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityCommandDetails.cs
  code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentCleanupHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentDispatcherHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/ComponentReplicationHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/CommandStorage.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/CommandStorage.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandRequestTrackerSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
Labels: size/XXL

#211 UTY-938: Moved EntityGameObjectLinker out of WorkerBase
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
Labels: size/XS

#217 Pin to a specific version
  global.json
Labels: size/XS

#215 UTY-941 playground core
  schema/playground/launcher.schema
  workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/ArchetypeInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/EntityGameObjectCreator.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs
  workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs
  workers/unity/Assets/Playground/Scripts/Workers/UnityClient.cs
  workers/unity/Assets/Playground/Tests/Editmode/EntityInitialization/EntityGameObjectCreatorTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ComponentPool.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ComponentPool.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialEvent.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/ISpatialEvent.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Components/MessageSenders.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/MessageSenders.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Components/ReactiveComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/EntityGameObjectLinkerTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanReactiveComponentsSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ApplyTransformUpdatesSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/PositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TransformSendSystem.cs
Labels: size/XL

#206 Code cleanups
  .gitignore
  ReSharper2017.DotSettings
  ci/lint.sh
  code_generator/GdkCodeGenerator.sln.DotSettings
  workers/unity/Assets/Playground/Config/ArchetypeConfig.cs
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGeneratorWindow.cs
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
  workers/unity/Assets/Playground/Scripts/Camera/FollowCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ScoreCollision.cs
  workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/DisconnectSystem.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/ArchetypeInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/EntityGameObjectCreator.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/Metrics/MetricSendSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs
  workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs
  workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs
  workers/unity/Assets/Playground/Scripts/UI/UIComponent.cs
  workers/unity/Assets/Playground/Scripts/UI/UpdateUISystem.cs
  workers/unity/Assets/Playground/Tests/Editmode/EntityInitialization/EntityGameObjectCreatorTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/WorldCommandsTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CustomSpatialOSSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ViewCommandBuffer.cs
  workers/unity/Packages/com.improbable.gdk.testutils/HybridGdkSystemTestBase.cs
  workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
  workers/unity/unity.sln.DotSettings
Labels: size/XL

#213 UTY-764: World Commands Rewrite
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/MutableView/MutableView.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsCleanSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerBase.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
Labels: size/XXL

#218 codegen fixes
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/S

#219 Bugfixes - Serialization
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
  code_generator/GdkCodeGenerator/src/Generation/Model/SchemaFunctionMappings.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
Labels: size/M

#221 UTY-450: Collection<Bool> Schema Codegen Fix
  code_generator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
  schema/improbable/gdk/tests/exhaustive_test.schema
Labels: size/XS

#223 UTY-350: Fix Connection Namespace Bug
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XS

#224 UTY-424: Enable Use of Data Field in a Component
  code_generator/GdkCodeGenerator/src/Generation/Model/UnitySchemaFile.cs
  code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
  schema/improbable/gdk/tests/alternate_schema_syntax.schema
Labels: size/M

#212 UTY-879: MonoBehaviour events in playground
  schema/playground/collisions.schema
  snapshots/default.snapshot
  workers/unity/Assets/Playground/Config/ArchetypeConfig.cs
  workers/unity/Assets/Playground/Config/PrefabConfig.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Resources/Prefabs/Character.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CheckForPlayerCollision.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CheckForPlayerCollision.cs.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/FlashOnCollision.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/FlashOnCollision.cs.meta
Labels: size/L

#226 Store connection for all log dispatchers
  workers/unity/Packages/com.improbable.gdk.core/Logging/ForwardingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/ILogDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Logging/LoggingDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: size/S

#234 changing which library we download for mac
  ci/download-core-sdk.sh
  workers/unity/Assets/Plugins/Improbable/Core/OSX/libworker.dylib.meta
  workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle.meta
  workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents.meta
  workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/Info.plist
  workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/Info.plist.meta
  workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/MacOS.meta
  workers/unity/Assets/Plugins/Improbable/Core/OSX/worker.bundle/Contents/MacOS/worker.meta
  workers/unity/Packages/manifest.json
Labels: size/M

#231 Playground improvements + fixes
  .gitignore
  schema/playground/cube.schema
  snapshots/default.snapshot
  workers/unity/Assets/Config.meta
  workers/unity/Assets/Config/ScriptableWorkerConfiguration.asset
  workers/unity/Assets/Config/ScriptableWorkerConfiguration.asset.meta
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CubeMovementSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ScoreCollision.cs
  workers/unity/Assets/Playground/Scripts/Cubes/TriggerColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs
Labels: size/L

#230 Adding support for IL2CPP to GDK
  workers/unity/Assets/link.xml
  workers/unity/Assets/link.xml.meta
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanReactiveComponentsSystem.cs
Labels: size/M

#232 UTY-945: Post-Merge Cleanups
  code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/CommandPayloads.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/CommandPayloads.cs.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
Labels: size/XL

#233 Entity Builder Bugfix and Tests
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
Labels: size/M

#242 Correct ComponentType access tags
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/LocalTransformSyncSystem.cs
Labels: size/M

#248 Added +x
  ci/includes/pinned-tools.sh
  prepare-workspace.sh
Labels: size/XS

#249 Remove unneeded OpenSSH setup steps
  ci/create-windows-image.ps1
Labels: size/L

#245 UTY-1054: Resolve merge conflicts between master and feature branch
  code_generator/GdkCodeGenerator/GdkCodeGenerator.csproj
  code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  code_generator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
  snapshots/default.snapshot
  workers/unity/Assets/Generated/AssemblyInfo.cs.meta
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
  workers/unity/Assets/Playground/Config/SystemConfig.cs.meta
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs.meta
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/MoveLocalPlayerSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessRechargeSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessScoresSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Authority.meta
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters.meta
  workers/unity/Packages/com.improbable.gdk.core/Commands.meta
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/Components/CommandPayloads.cs
  workers/unity/Packages/com.improbable.gdk.core/CoreSystemHelper.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/LocalTransformSyncSystem.cs
Labels: size/XXL

#251 UTY-1054: Prepare feature branch for merge attempt 2
  ci/create-windows-image.ps1
Labels: size/L

#256 Serialization codegen fix for enum fields
  code_generator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
Labels: size/XS

#259 Fixed eager MPB creation
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/FlashOnCollision.cs
Labels: size/XS

#253 Bugfix: Fix Component Update Short Circuit Regression
  code_generator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
Labels: size/XL

#260 upgrading entities package
  workers/unity/Packages/manifest.json
Labels: size/XS

#204 Adding Testing Docs
  ci/test.sh
  docs/content/testing/how-to-run-tests.md
  docs/content/testing/testing-guidelines.md
  docs/content/testing/testing-overview.md
  docs/content/testing/writing-a-new-unit-test.md
Labels: size/XXL

#241 UTY-879: Testing component update callbacks on readers in Playground
  schema/playground/color.schema
  snapshots/default.snapshot
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab
  workers/unity/Assets/Playground/Scripts/Cubes/ColorTranslationUtil.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ColorTranslationUtil.cs.meta
  workers/unity/Assets/Playground/Scripts/Cubes/ProcessColorChangeSystem.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/FlashOnCollision.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/UpdateSpinnerColor.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/UpdateSpinnerColor.cs.meta
  workers/unity/Assets/Playground/Scripts/Player/LocalPlayerInputSync.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManager.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/SpatialOSComponent.cs
Labels: size/XL

#225 Preprocess prefabs before entering playmode or building
  workers/unity/Assets/Playground/Editor/Prefabs.meta
  workers/unity/Assets/Playground/Editor/Prefabs/PrefabPreprocessor.cs
  workers/unity/Assets/Playground/Editor/Prefabs/PrefabPreprocessor.cs.meta
  workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab
Labels: size/M

#266 Fixing Client when starting through Launcher
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
Labels: size/XS

#246 UTY-1051: Generated Type Constructors and Command Usability Improvements
  code_generator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  code_generator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  code_generator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityTypeContentPart.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/TypeName.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstEventPayload.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondEventPayload.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstEventPayload.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandRequest.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandResponse.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
  workers/unity/Assets/Playground/Scripts/Cubes/CollisionProcessSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Assets/Playground/Scripts/Player/ProcessLaunchCommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
Labels: size/XXL

#265 Removing WorldCommandRequesters from worker entity when disconnected
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
Labels: size/M

#267 Local development workflow
  workers/unity/Assets/Playground/Scripts/Bootstrap.cs
  workers/unity/Assets/Plugins/Improbable/Sdk/Improbable.WorkerCoreStatic.dll
  workers/unity/Packages/com.improbable.gdk.core/Config/ReceptionistConfig.cs
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: size/XS

#273 UTY-595: Upgrade to Bridge v2
  cloud_launch.json
  default_launch.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Components/BufferedTransform.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ApplyTransformUpdatesSystem.cs
Labels: size/S

#243 UTY-963: Core C# SDK Docs Changes
  docs/content/authority.md
  docs/content/commands.md
  docs/content/component-data.md
  docs/content/create-entity.md
  docs/content/custom-replication-system.md
  docs/content/entity-checkout-process.md
  docs/content/events.md
  docs/content/reactive-components.md
  docs/content/system-update-order.md
Labels: size/XL

#255 UTY-375: Always have a ReceivedUpdates on ComponentAdded
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/CoreSystemHelper.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XL

#276 Small optimization in SendCommands to decrease cpu usage.
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/L

#262 UTY-690, 691: Codegened CommandRequestSenders and RequestHandlers for MonoBehaviours
  schema/playground/spawner.schema
  schema/playground/spinner_rotation.schema
  snapshots/default.snapshot
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/RotationBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs.meta
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/InjectableId.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/XXL

#275 Feature/uty 950 kill prepare workspace
  docs/setup-and-installing.md
  prepare-workspace.sh
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/BuildSystemMenu.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Improbable.Gdk.Legacy.BuildSystem.asmdef
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/PathUtil.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/SpatialCommand.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/SpatialCommandRunner.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/SpatialCommandRunner.cs.meta
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/SpatialCommands.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/SpatialCommands.cs.meta
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/Util/SpatialRunner.cs
  workers/unity/Packages/com.improbable.gdk.legacy/Editor/BuildSystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/ShowProgressBarScope.cs
  workers/unity/Packages/com.improbable.gdk.tools/ShowProgressBarScope.cs.meta
Labels: size/XXL

#279 Fixed quoting
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/XS

#263 Some clean up and preparation for IL2CPP
  docs/content/entity-checkout-process.md
  workers/unity/Assets/Playground/Config/ArchetypeConfig.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/ArchetypeInitializationSystem.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Components/BufferedTransform.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ApplyTransformUpdatesSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/TransformSynchronizationConfig.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/TransformSynchronizationConfig.cs.meta
  workers/unity/Packages/manifest.json
Labels: size/L

#274 Pass in command contexts
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsTranslation.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentTranslation.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/CommandStorage.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/CommandRequestIdGenerator.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/CommandRequestIdGenerator.cs.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentConversionGenerator.tt
Labels: size/XL

#282 Stop the build configs from building twice when launching locally
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
Labels: size/XS

#281 UTY-1106: replace entity index with entity
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Playground/Scripts/EntityInitialization/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/Injection/MonoBehaviourActivationManagerInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
Labels: size/XXL

#284 Avoid leading/trailing blank lines
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Labels: size/XS

#283 adding more osx specific paths
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
Labels: size/S

#287 Move dependencies from manifest to the core package
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/manifest.json
Labels: size/XS

#269 Implement command response sending and receiving for MonoBehaviours
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/NestedComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsReaderWriter.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentMonoBehaviourCommandHandlers.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentReaderWriter.cs
  workers/unity/Assets/Playground/Resources/Prefabs/Spinner.prefab
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ToggleRotationCommandSender.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectComponentDispatcherBase.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/GameObjectDispatcherSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/Delegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/GameObjectDelegates.cs
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/GameObjectDelegates.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/GameObjectRepresentation/ReadersWriters/ReaderWriterBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders/CommandRequestHandlerTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders/CommandRequestHandlerTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: size/XXL

#289 Unbreak master
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsGameObjectComponentDispatcher.cs
  workers/unity/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentGameObjectComponentDispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/GameObjectRepresentation/CommandSenders/CommandResponseHandlerTests.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
Labels: size/S
