Repository spatialos/gdk-for-unity, pull requests merged in 2019-02, with the labels that each got.

#727 CI pipefail fix
  ci/build-ios.sh
  ci/build-test.sh
  ci/pack.sh
  ci/upload-launch.sh
Labels: A: maintenance, size/XS

#729 Run Build & Test in Parallel on Buildkite
  .buildkite/premerge.steps.yaml
  ci/build.sh
  ci/test.sh
Labels: size/M

#697 Deployment Launcher docs
  docs/assets/deployment-window.png
  docs/content/get-started/build-workers.md
  docs/content/get-started/get-playing.md
  docs/content/get-started/upload-launch.md
Labels: A: maintenance, T: documentation, size/M

#675 Add OWNERS files for automatic labeling
  ci/OWNERS
  schema/playground/OWNERS
  workers/unity/Assets/OWNERS
  workers/unity/Assets/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/OWNERS
  workers/unity/Packages/com.improbable.gdk.buildsystem/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.core/OWNERS
  workers/unity/Packages/com.improbable.gdk.core/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/OWNERS
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.mobile/OWNERS
  workers/unity/Packages/com.improbable.gdk.mobile/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/OWNERS
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.tools/OWNERS
  workers/unity/Packages/com.improbable.gdk.tools/OWNERS.meta
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/OWNERS
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/OWNERS.meta
Labels: A: maintenance, T: feature, size/M

#738 Subscription component check
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentReaderWriterGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentUpdateManagerGenerator.tt
Labels: size/XS

#723 Docs fixes arising from testing the local deployment workflow for mobile.
  docs/assets/setup/windows/visualstudioworkloads.png
  docs/content/build.md
  docs/content/code-generator.md
  docs/content/connecting-to-spatialos.md
  docs/content/deploy.md
  docs/content/ecs/component-data.md
  docs/content/ecs/component-generation.md
  docs/content/ecs/reactive-components.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/get-started/build-workers.md
  docs/content/get-started/open-project.md
  docs/content/get-started/set-up.md
  docs/content/get-started/upload-launch.md
  docs/content/glossary.md
  docs/content/initial-set-up.md
  docs/content/mobile/android/cloud-deploy.md
  docs/content/mobile/android/local-deploy.md
  docs/content/mobile/android/setup.md
  docs/content/mobile/android/ways-to-test.md
  docs/content/mobile/ios/cloud-deploy.md
  docs/content/mobile/ios/local-deploy.md
  docs/content/mobile/ios/setup.md
  docs/content/mobile/ios/ways-to-test.md
  docs/content/mobile/overview.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/set-up-new-project.md
  docs/content/snapshots.md
  docs/content/testing/how-to-run-tests.md
  docs/content/testing/testing-guidelines.md
  docs/content/testing/writing-a-new-unit-test.md
  docs/content/troubleshooting.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/api-worker.md
  docs/projects/fps/tutorial.md
  docs/setup-and-installing.md
Labels: A: mobile, T: documentation, size/XL

#740 fix the rendering of the numered list
  docs/content/mobile/ios/local-deploy.md
Labels: size/XS

#741 Remove overly specific network terminology.
  docs/content/mobile/android/local-deploy.md
  docs/content/mobile/ios/local-deploy.md
Labels: size/XS

#733 Add release QA pipeline for buildkite
  .buildkite/release-qa.definition.yaml
  .buildkite/release-qa.steps.yaml
  ci/build.sh
  ci/upload-launch.sh
Labels: A: maintenance, T: feature, size/M

#743 Add USB debugging accept step
  docs/content/mobile/android/cloud-deploy.md
Labels: size/XS

#742 Improve the local launch error message as per UTY-1275
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
Labels: A: tooling, T: enhancement, size/XS

#737 Schema Bundle Migration
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/CodeGeneration.csproj
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/BuiltInSchemaTypes.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Bundle.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/ComponentDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Utils/Formatting.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/GdkCodeGenerator.csproj
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEnumContent.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEnumGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectCommandHandlersGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityGameObjectComponentDispatcherGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/AggregateJob.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGenerator.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandComponentsGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandPayloadGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityCommandStorageGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentConversionGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentDataGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityEnumContentPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityEnumGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityEventGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityGameObjectCommandHandlersGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityGameObjectComponentDispatcherGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityReaderWriterGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityReferenceTypeProviderGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityTypeContentPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityTypeGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/CommonDetailsUtils.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/FieldTypes.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityCommandDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityComponentDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityEnumDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityEventDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityTypeDetails.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/SchemaFunctionMappings.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/UnitySchemaFile.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/UnityTypeMappings.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SchemaProcessing/BlittableFlagger.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SchemaProcessing/PayloadMarker.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SchemaProcessing/TypeReferences/UnityTypeReference.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SchemaProcessing/UnitySchemaProcessor.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/WorkerGenerationJob.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/MetaDataCompatibleFileSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Tests/BlittableFlaggerTests.cs
Labels: A: codegen, T: refactor, size/XXL

#749 Feature/command list consistency
  workers/unity/Packages/com.improbable.gdk.core/Collections/ReceivedMessageListExtensions.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/ReceivedMessagesSpan.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/CommandComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/CommandManagers.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands/CreateEntity.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands/DeleteEntity.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands/EntityQuery.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/WorldCommands/ReserveEntityIds.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/CommandRequestCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/CommandRequestCallbackManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/CommandResponseCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/CommandResponseCallbackManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/ComponentEventCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/ComponentUdpateCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/CommandCallbackSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ReactiveCommandComponentGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandManagerGenerator.tt
Labels: size/L

#746 Update Exhaustive Test Schema
  test-project/Assets/.Schema/improbable/gdk/tests/exhaustive_test.schema
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularData.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
Labels: A: codegen, A: maintenance, size/XXL

#745 Add Schema Annotations Support
  test-project/Assets/.Schema/improbable/gdk/tests/exhaustive_test.schema
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularData.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/AnnotationRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/ComponentDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/EnumDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/SchemaBundleV1/TypeDefinitionRaw.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
Labels: A: codegen, T: feature, size/XXL

#751 [WIP] Upgrade to Unity 2018.3.5f1
  .buildkite/premerge.steps.yaml
  CHANGELOG.md
  ci/UnityEditorHash.txt
  test-project/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/ProjectVersion.txt
Labels: A: maintenance, T: enhancement, do-not-merge/work-in-progress, size/XS

#758 Removed the NavMesh rebake step for getting started
  docs/assets/navmesh-fixed.png
  docs/content/get-started/build-workers.md
  docs/content/get-started/get-playing.md
  docs/content/get-started/open-project.md
  docs/content/get-started/set-up.md
  docs/content/get-started/upload-launch.md
  docs/content/get-started/view-game-world.md
  docs/toc.md
Labels: T: documentation, size/M

#756 Remove the transitional template from Playground, as the new runtime is now the default runtime.
  cloud_launch.json
  default_launch.json
  mobile_launch.json
Labels: A: maintenance, size/XS

#752 Enable worker entity linking
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectCreationHelper.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
Labels: A: core, T: enhancement, size/S

#754 Moved transforms off reactive components
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/DirectTransformUpdateSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedPositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedTransformSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/TickSystem.cs
Labels: A: transform-synchronization, T: refactor, size/XXL

#757 Remove UTY-1578 workaround
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: A: core, A: maintenance, T: enhancement, size/S

#762 Docs: Upgrade the documented Unity version to 2018.3.5
  docs/content/get-started/set-up.md
  docs/content/initial-set-up.md
  docs/setup-and-installing.md
Labels: size/S

#739 Lifecycle API validation
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/SendPlayerHeartbeatRequestSystem.cs
Labels: A: player-lifecycle, T: refactor, size/XL

#765 Check the correct boxes in BuildConfiguration.asset
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
Labels: A: playground, size/XS

#755 Feature/clean up reflection warnings
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CheckForPlayerCollision.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/ProcessSpinnerColorChange.cs
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/AcknowledgeAuthorityLossSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CommandSenderComponentSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveCommandComponentSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/WorldCommandsSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/RequireLifecycleSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerDisconnectCallbackSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerHeartbeat/HandlePlayerHeartbeatResponseSystem.cs
  workers/unity/Packages/com.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedPositionSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/RateLimitedTransformSendSystem.cs
Labels: A: game-object-creation, A: player-lifecycle, A: playground, A: transform-synchronization, T: refactor, size/L

#748 Docs/uty 1764
  docs/content/mobile/android/cloud-deploy.md
  docs/content/mobile/android/local-deploy.md
Labels: A: mobile, T: documentation, size/S

#769 Remove duplication when adding reactive component systems
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: size/XS

#759 Page surgery and remove to fixes to known issues
  docs/known-issues.md
Labels: size/XS

#761 `0.1.5` release pre-validation
  CHANGELOG.md
  packer.config.json
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: A: build-system, A: core, A: game-object-creation, A: mobile, A: player-lifecycle, A: playground, A: tooling, A: transform-synchronization, size/M

#772 remove component swaps
  workers/unity/Packages/com.improbable.gdk.core/Collections/ReceivedMessageList.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentUpdateSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/UpdatesAndEvents/ComponentManagers.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/DiffStorage.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ViewDiff.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/CommandDiffStorageGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffDeserializerGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffStorageGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentUpdateManagerGenerator.tt
Labels: size/XL

#775 Fix broken test
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanReactiveComponentsSystemTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanTemporaryComponentsSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/CleanTemporaryComponentsSystemTests.cs.meta
Labels: size/S

#779 Bugfix/fix tests
  ci/test.sh
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/FileHandling/MockFileSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Utils/FormattingTests.cs
Labels: A: maintenance, A: tooling, size/XS

#766 Remove progress blockers from iOS docs.
  docs/content/mobile/android/local-deploy.md
  docs/content/mobile/android/ways-to-test.md
  docs/content/mobile/ios/cloud-deploy.md
  docs/content/mobile/ios/local-deploy.md
  docs/content/mobile/ios/ways-to-test.md
  docs/projects/fps/tutorial.md
Labels: A: mobile, T: documentation, size/L

#744 Add pre exit hook for Buildkite
  .buildkite/hooks/pre-exit
  ci/purge.ps1
Labels: A: maintenance, T: feature, size/M

#784 Fix Codegen Regression
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/JobRunner.cs
Labels: A: tooling, T: bug, size/XS

#628 UI Pass
  .gitignore
  CHANGELOG.md
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/AssemblyInfo.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/AssemblyInfo.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditorStyle.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditorStyle.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironment.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironmentConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SceneItem.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SceneItem.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SingletonScriptableObject.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialBuildPlatforms.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialBuildPlatforms.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/SpatialOSBuildConfigurationEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerChoicePopup.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerChoicePopup.cs.meta
  workers/unity/Packages/com.improbable.gdk.buildsystem/Improbable.Gdk.BuildSystem.asmdef
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/EditorPaths.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/BuildSystemAssemblyGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityWorkerMenuGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/WorkerGenerationJob.cs
  workers/unity/Packages/com.improbable.gdk.tools/EditorConfig.cs
  workers/unity/Packages/com.improbable.gdk.tools/EditorConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/GUIColorScope.cs
  workers/unity/Packages/com.improbable.gdk.tools/GUIColorScope.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationEditorExtensions.cs
Labels: A: build-system, A: playground, A: tooling, T: enhancement, T: refactor, size/XXL

#763 Make Types, Enums, and Snapshots Serializable.
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEnumContent.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
Labels: A: codegen, A: tooling, T: enhancement, size/XS

#776 Add Some Subscription Tests
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/AggregateSubscriptionTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/AggregateSubscriptionTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/RequiredSubscriptionsInfoTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/RequiredSubscriptionsInfoTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/StandardSubscriptionTests.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/StandardSubscriptionTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/SubscriptionTestBase.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/SubscriptionTestBase.cs.meta
Labels: A: core, T: enhancement, size/L

#770 Separate View
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Subscriptions/SubscriptionTestBase.cs
  workers/unity/Packages/com.improbable.gdk.core/View.meta
  workers/unity/Packages/com.improbable.gdk.core/View/View.cs
  workers/unity/Packages/com.improbable.gdk.core/View/View.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/View/ViewStorage.cs
  workers/unity/Packages/com.improbable.gdk.core/View/ViewStorage.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/GdkCodeGenerator.csproj
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ViewStorageGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/ViewStorageGeneratorPart.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/SingleGenerationJob.cs
Labels: A: core, A: tooling, T: feature, size/L

#783 Add a callout that iOS Simulator is incombatible with the FPS Starter Project
  docs/content/mobile/ios/cloud-deploy.md
  docs/content/mobile/ios/local-deploy.md
Labels: size/XS

#785 Android docs workflow improvements
  docs/content/glossary.md
  docs/content/mobile/android/cloud-deploy.md
  docs/content/mobile/android/local-deploy.md
  docs/content/mobile/android/setup.md
  docs/content/mobile/ios/cloud-deploy.md
  docs/content/mobile/ios/local-deploy.md
  docs/content/mobile/ios/setup.md
Labels: size/M

#790 Correctly refer to the Project Settings window.
  docs/content/mobile/ios/cloud-deploy.md
  docs/content/mobile/ios/local-deploy.md
Labels: size/XS

#789 MockConnectionHandler & Reader/Writer tests
  CHANGELOG.md
  test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef
  test-project/Assets/EditmodeTests/Subscriptions.meta
  test-project/Assets/EditmodeTests/Subscriptions/ReaderWriter.meta
  test-project/Assets/EditmodeTests/Subscriptions/ReaderWriter/InjectionCriteriaTests.cs
  test-project/Assets/EditmodeTests/Subscriptions/ReaderWriter/InjectionCriteriaTests.cs.meta
  test-project/Packages/manifest.json
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/DynamicConverter.cs
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/DynamicConverter.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/DynamicSnapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/IDynamicInvokable.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityQuerySnapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityTemplate.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
Labels: A: core, A: tooling, size/XL

#786 Use new shared-ci script to build workers
  .buildkite/hooks/post-command
  .buildkite/hooks/pre-exit
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/build.sh
  ci/launch.sh
  ci/purge.ps1
Labels: A: maintenance, size/L

#794 Remove SpatialOS* > *Launch mobile client* > *iOS Device* flow from docs.
  docs/content/mobile/ios/cloud-deploy.md
Labels: size/XS

#795 Docs/cite correct snapshot
  docs/content/mobile/android/cloud-deploy.md
  docs/content/mobile/ios/cloud-deploy.md
Labels: size/XS

#796 Docs: Use `id` not `tokenSecret`.
  docs/content/mobile/android/cloud-deploy.md
  docs/content/mobile/ios/cloud-deploy.md
Labels: size/S

#798 fps upgrade fixes
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntitySubscriptions.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedEntityComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/SubscriptionSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/SpatialOSConnectionHandler.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
Labels: A: core, A: game-object-creation, A: transform-synchronization, size/M

#793 Feature/command sender fixes
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntitySubscriptions.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedEntityComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/SubscriptionSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/SpatialOSConnectionHandler.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
Labels: A: core, A: game-object-creation, A: tooling, A: transform-synchronization, size/L

#791 Fixed an error when linking a gameobject to an invalid entity
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntitySubscriptions.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedEntityComponent.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/SubscriptionSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/SpatialOSReceiveSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/SpatialOSConnectionHandler.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandSenderReceiverGenerator.tt
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
Labels: A: core, A: game-object-creation, A: tooling, A: transform-synchronization, size/L

#801 Fix tests in experimental branch
  test-project/Assets/EditmodeTests/Subscriptions/ReaderWriter/InjectionCriteriaTests.cs
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: player-lifecycle, A: playground, A: tooling, A: transform-synchronization, size/XS

#802 Update tutorial code snippet
  docs/projects/fps/tutorial.md
Labels: size/S

#764 Move ToC Entry
  docs/toc.md
Labels: A: maintenance, T: documentation, size/XS
