Repository spatialos/gdk-for-unity, pull requests merged in 2019-11, with the labels that each got.

#1210 Docs - worker sdk upgrade 14.2.1
  docs/reference/glossary.md
  docs/variable.properties
Labels: T: documentation, jira/no-ticket, size/XS

#1208 Worker sdk upgrade
  CHANGELOG.md
  ci/shared-ci.pinned
  init.ps1
  init.sh
  spatialos.json
  workers/unity/Packages/io.improbable.gdk.core/package.json
  workers/unity/Packages/io.improbable.gdk.mobile/package.json
  workers/unity/Packages/io.improbable.worker.sdk.mobile/package.json
  workers/unity/Packages/io.improbable.worker.sdk/.sdk.version
  workers/unity/Packages/io.improbable.worker.sdk/package.json
Labels: A: core, A: maintenance, A: mobile, jira/no-ticket, size/S

#1183 Mobile SDK import settings fix + CodeGen casing
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/Android/arm64/libimprobable_worker.so.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/Android/armv7/libimprobable_worker.so.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/Android/x86/libimprobable_worker.so.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/arm/libimprobable_worker_static.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/x86_64/libimprobable_worker_static.a.meta
Labels: A: tooling, jira/no-ticket, size/L

#1211 Events no longer trigger component updates
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentDiffDeserializer.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Templates/ComponentDiffDeserializerGenerator.tt
Labels: A: core, A: game-object-creation, A: maintenance, A: mobile, A: tooling, A: transform-synchronization, jira/no-ticket, size/M

#1184 Mobile reconnection doc
  docs/toc.md
  docs/workflows/reconnection-logic.md
Labels: T: documentation, jira/no-ticket, size/M

#1212 Change default network type to ModularUDP with Compression
  CHANGELOG.md
  workers/unity/Assets/Playground/Scripts/Worker/ClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/MobileClientWorkerConnector.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Labels: A: core, A: playground, jira/no-ticket, size/S

#1215 FPS docs update
  docs/assets/health-pickups-tutorial/inspect-health.jpg
  docs/assets/health-pickups-tutorial/inspect-health.png
  docs/projects/fps/get-started/build-workers.md
  docs/projects/fps/get-started/upload-launch.md
  docs/projects/fps/tutorial.md
Labels: T: documentation, jira/no-ticket, size/S

#1217 Expose `IsConnected` in WorkerSystem
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Systems/WorkerSystem.cs
Labels: A: core, jira/UTY, size/XS

#1218 Use WorkerSystem.IsConnected instead of finding the WorkerConne…
  docs/workflows/reconnection-logic.md
Labels: T: documentation, jira/no-ticket, size/S

#1219 Deployment Launcher editor performance improvement
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
Labels: jira/no-ticket, size/S

#1220 CORE-1340 Change locator port 444 -> 443
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Config/RuntimeConfig.cs
Labels: A: core, jira/CORE, size/XS

#1222 Resolving type/command/event name clashes
  CHANGELOG.md
  test-project/Assets/.schema/illegal.schema
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityCommandDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityComponentDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityEventDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityTypeDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: playground, A: tooling, jira/UTY, size/M
