Repository spatialos/gdk-for-unity, pull requests merged in 2019-04, with the labels that each got.

#883 Remove old doc page
  docs/modules/player-lifecycle-feature-module.md
  docs/reference/glossary.md
  docs/reference/workflows/ecs/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/world-component-commands-requests-responses.md
Labels: T: documentation, size/L

#886 Fast forward docs-next
  docs/modules/player-lifecycle-feature-module.md
  docs/reference/glossary.md
  docs/reference/workflows/ecs/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/world-component-commands-requests-responses.md
Labels: T: documentation, size/L

#885 Update and expand GameObject Creation feature module documentation
  docs/modules/core-and-feature-module-overview.md
  docs/modules/game-object-creation/custom-usage.md
  docs/modules/game-object-creation/overview.md
  docs/modules/game-object-creation/standard-usage.md
  docs/projects/fps/tutorial.md
  docs/reference/concepts/connection-flows.md
  docs/reference/concepts/entity-lifecycle.md
  docs/reference/glossary.md
  docs/reference/overview.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/index.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
  docs/reference/workflows/monobehaviour/linking/spatialos-entities.md
  docs/reference/workflows/monobehaviour/linking/workers.md
  docs/reference/workflows/which-workflow.md
  docs/toc.md
Labels: A: game-object-creation, T: documentation, size/XL

#884 adding mobile pre-alpha warning
  docs/reference/mobile/overview.md
Labels: T: documentation, size/XS

#889 Fix docs typo
  docs/modules/game-object-creation/custom-usage.md
  docs/modules/game-object-creation/standard-usage.md
Labels: T: documentation, size/XS

#890 Cherry picked docs-next
  docs/modules/core-and-feature-module-overview.md
  docs/modules/game-object-creation/custom-usage.md
  docs/modules/game-object-creation/overview.md
  docs/modules/game-object-creation/standard-usage.md
  docs/projects/fps/tutorial.md
  docs/reference/concepts/connection-flows.md
  docs/reference/concepts/entity-lifecycle.md
  docs/reference/glossary.md
  docs/reference/mobile/overview.md
  docs/reference/overview.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/index.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
  docs/reference/workflows/monobehaviour/linking/spatialos-entities.md
  docs/reference/workflows/monobehaviour/linking/workers.md
  docs/reference/workflows/which-workflow.md
  docs/toc.md
Labels: T: documentation, size/XL

#887 Update and expand Build System feature module documentation
  docs/modules/build-system/build-config.md
  docs/modules/build-system/cli.md
  docs/modules/build-system/editor-menu.md
  docs/modules/build-system/overview.md
  docs/modules/core-and-feature-module-overview.md
  docs/projects/myo/build.md
  docs/toc.md
Labels: A: build-system, T: documentation, size/M

#891 Cherry pick build system changes to docs next
  docs/modules/build-system/build-config.md
  docs/modules/build-system/cli.md
  docs/modules/build-system/editor-menu.md
  docs/modules/build-system/overview.md
  docs/modules/core-and-feature-module-overview.md
  docs/projects/myo/build.md
  docs/toc.md
Labels: T: documentation, size/M

#893 Fix xml docs for player lifecycle config
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
Labels: A: player-lifecycle, T: documentation, size/M

#654 QBI Helper v1
  CHANGELOG.md
  test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef
  test-project/Assets/EditmodeTests/Utility/ConstraintTests.cs
  test-project/Assets/EditmodeTests/Utility/ConstraintTests.cs.meta
  test-project/Assets/EditmodeTests/Utility/InterestQueryTests.cs
  test-project/Assets/EditmodeTests/Utility/InterestQueryTests.cs.meta
  test-project/Assets/EditmodeTests/Utility/InterestTemplateTests.cs
  test-project/Assets/EditmodeTests/Utility/InterestTemplateTests.cs.meta
  test-project/Packages/manifest.json
  workers/unity/Assets/Playground/Improbable.Playground.asmdef
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/Constraint.cs
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/Constraint.cs.meta
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/Improbable.Gdk.QueryBasedInterestHelper.asmdef
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/Improbable.Gdk.QueryBasedInterestHelper.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/InterestQuery.cs
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/InterestQuery.cs.meta
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/InterestTemplate.cs
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/InterestTemplate.cs.meta
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/package.json
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/package.json.meta
  workers/unity/Packages/manifest.json
Labels: A: other-feature-module, A: playground, T: feature, size/XXL

#892 Expand documentation for the transform synchronization feature module
  docs/assets/image-transform-feature-module-md-1.png
  docs/modules/core-and-feature-module-overview.md
  docs/modules/transform-feature-module.md
  docs/modules/transform-sync/how-it-works.md
  docs/modules/transform-sync/overview.md
  docs/modules/transform-sync/setup-transform.md
  docs/modules/transform-sync/strategies.md
  docs/toc.md
Labels: A: transform-synchronization, T: documentation, size/XL

#896 Update docs-next with #892
  docs/assets/image-transform-feature-module-md-1.png
  docs/modules/core-and-feature-module-overview.md
  docs/modules/transform-feature-module.md
  docs/modules/transform-sync/how-it-works.md
  docs/modules/transform-sync/overview.md
  docs/modules/transform-sync/setup-transform.md
  docs/modules/transform-sync/strategies.md
  docs/toc.md
Labels: T: documentation, size/XL

#869 Improve Player Lifecycle Docs
  docs/modules/core-and-feature-module-overview.md
  docs/modules/player-lifecycle-feature-module.md
  docs/modules/player-lifecycle/basic-player-creation.md
  docs/modules/player-lifecycle/custom-player-creation.md
  docs/modules/player-lifecycle/heartbeating.md
  docs/modules/player-lifecycle/overview.md
  docs/toc.md
Labels: A: player-lifecycle, T: documentation, size/XL

#888 Redirected process changes required for deployment launcher fixes
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/Result.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/Result.cs.meta
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Labels: A: build-system, A: core, A: mobile, A: tooling, size/XL

#898 Add worker flag reader
  CHANGELOG.md
  default_launch.json
  test-project/Assets/EditmodeTests/Subscriptions/ReaderWriter/InjectionCriteriaTests.cs
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Character.prefab
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerFlagTest.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerFlagTest.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/WorkerFlagCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/WorkerFlagCallbackManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorkerFlagSubscriptionManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorkerFlagSubscriptionManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/RequireLifecycleSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/WorkerFlagCallbackSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/WorkerFlagCallbackSystem.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/View/View.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/OpListConverter.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ViewDiff.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: A: core, A: playground, T: feature, size/XL

#901 Remove Redirect
  docs/content/get-started/get-started.md
Labels: T: documentation, size/XS

#904 Refresh code generator section (#897)
  docs/reference/concepts/code-generation.md
  docs/reference/concepts/entity-templates.md
  docs/toc.md
Labels: T: documentation, size/M

#902 QBI Helper docs
  docs/modules/core-and-feature-module-overview.md
  docs/modules/qbi-helper/examples.md
  docs/modules/qbi-helper/interest-query.md
  docs/modules/qbi-helper/interest-template.md
  docs/modules/qbi-helper/intro-to-qbi.md
  docs/modules/qbi-helper/overview.md
  docs/modules/transform-sync/strategies.md
  docs/toc.md
Labels: A: core, A: other-feature-module, T: documentation, size/XL

#905 Reactive components quickfix
  CHANGELOG.md
  cloud_launch.json
  default_launch.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: A: player-lifecycle, size/M

#907 Stop things freezing in FPS
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Labels: A: tooling, size/XS

#906 Update ReSharper2017.DotSettings
  ReSharper2017.DotSettings
Labels: size/XS

#900 Unity 2018.3.11 upgrade
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/ProjectSettings.asset
  workers/unity/ProjectSettings/ProjectVersion.txt
Labels: size/S

#911 Update Unity version in docs
  docs/fragments/machine-setup.md
Labels: T: documentation, size/XS

#912 Release 0.2.1 - Pre-Validation
  CHANGELOG.md
  packer.config.json
  test-project/Packages/com.improbable.gdk.dependencytest/package.json
  test-project/Packages/com.improbable.gdk.dependencytestchild/package.json
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/package.json
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: A: build-system, A: core, A: game-object-creation, A: mobile, A: player-lifecycle, A: tooling, A: transform-synchronization, size/L

#915 Update Unity Editor hash
  ci/UnityEditorHash.txt
Labels: A: maintenance, size/XS

#916 Fix event race
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffStorage.cs
  test-project/Packages/manifest.json
  test-project/ProjectSettings/ProjectVersion.txt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffStorageGenerator.tt
Labels: A: tooling, size/S

#910 Safe Callbacks
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs
Labels: A: core, T: bug, size/M

#909 Add support for win x86 builds
  CHANGELOG.md
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerFlagTest.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/Plugins/PluginPostprocessor.cs
Labels: A: build-system, A: playground, A: tooling, size/S

#917 Worker SDK 13.7.1 Upgrade
  CHANGELOG.md
  spatialos.json
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularData.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/SomeEnum.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/SomeType.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/TypeName.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/RandomDataType.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentCommandPayloads.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/FirstEventPayload.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/SecondEventPayload.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsCommandPayloads.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/Empty.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/FirstEventPayload.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentCommandPayloads.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandRequest.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondCommandResponse.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/SecondEventPayload.cs
  workers/unity/Assets/Resources.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEnumContent.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  workers/unity/Packages/com.improbable.gdk.tools/.DownloadCoreSdk/Program.cs
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
  workers/unity/ProjectSettings/GraphicsSettings.asset
  workers/unity/ProjectSettings/ProjectSettings.asset
Labels: A: core, A: playground, A: tooling, size/M

#918 Meta file case sensitive fix
  workers/unity/Packages/com.improbable.gdk.core/Editor/UIStateManager.cs.meta
Labels: A: core, size/XS

#914 Add user friendly error when failing to find build config
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: A: build-system, T: feature, size/S

#919 Refreshed connection flows section
  docs/reference/concepts/connection-flows.md
Labels: T: documentation, size/M

#920 Refresh concepts/entity-template
  docs/reference/concepts/entity-templates.md
Labels: T: documentation, size/M

#921 Buildkite Fix
  .buildkite/hooks/post-checkout
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/bootstrap.sh
Labels: A: maintenance, size/S

#924 Cherry pick #923 into docs-next
  docs/pricing-and-support/pricing.md
  docs/pricing-and-support/support.md
  docs/toc.md
Labels: T: documentation, size/S

#922 Load dev token asset by default
  .gitignore
  CHANGELOG.md
  workers/unity/Assets/.gitignore
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs
Labels: A: core, A: mobile, A: playground, A: tooling, size/M

#925 Fix Worker Entity + GameObject Link
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Systems/WorkerSystem.cs
Labels: A: core, size/XS
