Repository spatialos/gdk-for-unity, pull requests merged in 2019-08, with the labels that each got.

#1086 UTY-2181 Fix MonoBehaviourInspector throwing NRE
  workers/unity/Packages/io.improbable.gdk.debug/MonoBehaviourInspector.cs
Labels: jira/UTY, size/XS

#1085 Tidy up test utils package
  CHANGELOG.md
  test-project/Assets/EditmodeTests/DisableAutoCreationSystemsTests.cs
  test-project/Assets/EditmodeTests/DisableAutoCreationSystemsTests.cs.meta
  workers/unity/Assets/Plugins.meta
  workers/unity/Assets/Plugins/Editor.meta
  workers/unity/Assets/Plugins/_plugin
  workers/unity/Assets/Plugins/_plugin.meta
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/UpdateGroups.cs
  workers/unity/Packages/io.improbable.gdk.testutils/DisableAutoCreationSystemsTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.testutils/TestMonoBehaviour.cs
  workers/unity/Packages/io.improbable.gdk.testutils/TestMonoBehaviour.cs.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Tests.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Tests/Editmode/HybridGdkSystemTestBaseTests.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Tests/Editmode/Improbable.Gdk.TestUtils.EditmodeTests.asmdef
  workers/unity/Packages/io.improbable.gdk.testutils/WorkerOpFactory.cs
  workers/unity/Packages/io.improbable.gdk.testutils/WorkerOpFactory.cs.meta
Labels: A: game-object-creation, A: playground, jira/no-ticket, size/XL

#1087 Fix DefaultApplyLatestTransformSystem post-#1064
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
Labels: A: transform-synchronization, jira/no-ticket, size/XS

#1088 Add `SpatialDeploymentManager` to test utils package
  workers/unity/Packages/io.improbable.gdk.testutils/Editor.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Improbable.Gdk.TestUtils.Editor.asmdef
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Improbable.Gdk.TestUtils.Editor.asmdef.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/Improbable.Gdk.TestUtils.Editor.Tests.asmdef
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/Improbable.Gdk.TestUtils.Editor.Tests.asmdef.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialDeploymentManagerTests.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialDeploymentManagerTests.cs.meta
Labels: jira/no-ticket, size/XL

#1074 Refresh snapshots docs page
  docs/reference/concepts/snapshots.md
  docs/reference/overview.md
  docs/reference/workflows/overview.md
Labels: T: documentation, jira/no-ticket, size/M

#1089 Add debug feature module section + require inspector
  docs/assets/modules/debug/inspector.png
  docs/modules/debug/overview.md
  docs/modules/debug/require-inspector.md
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/M

#1091 Bump `current_version` variable
  docs/variable.properties
Labels: T: documentation, jira/no-ticket, size/XS

#1093 Fix ToC
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/XS

#1094 Cherry-pick #1093
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/XS

#1101 Add Scaler v2 to docs pipeline
  .buildkite/docs.steps.yaml
Labels: T: documentation, jira/no-ticket, size/XS

#1095 Add receptionist flow testing
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection.meta
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/ReceptionistFlowTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/ReceptionistFlowTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Improbable.Gdk.Core.EditmodeTests.asmdef
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
Labels: A: core, jira/no-ticket, size/L

#1096 Add `CommandLineConnectionFlowInitializer` Tests
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionFlowInitializerTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionFlowInitializerTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionFlowInitializers.cs
Labels: A: core, jira/no-ticket, size/L

#1102 Fix potential deadlock when using `RedirectedProcess.RunAsync()`
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/RedirectedProcess.cs
Labels: A: tooling, jira/no-ticket, size/XS

#1103 Add tests for `CommandLineConnectionParameterInitializer`
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionParametersInitializerTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionParametersInitializerTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionParameterInitializers.cs
Labels: A: core, jira/no-ticket, size/M

#1107 Feature/schema compiler error message
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: tooling, jira/no-ticket, size/XS

#1105 Refactor & Fixes to `AlphaLocatorFlow`
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionFlows.cs
Labels: A: core, jira/no-ticket, size/S

#1109 Add missed breaking change from #1105
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1104 Add `spot` and `SpatialdManager`
  CHANGELOG.md
  init.ps1
  init.sh
  workers/unity/Packages/io.improbable.gdk.testutils/.SpotShim/SpotShim/SpotShim/Program.cs
  workers/unity/Packages/io.improbable.gdk.testutils/.SpotShim/SpotShim/SpotShim/SpotShim.csproj
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialdManager.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialdManager.cs.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/Improbable.Gdk.TestUtils.Editor.Tests.asmdef
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialdManagerTests.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/Tests/SpatialdManagerTests.cs.meta
  workers/unity/Packages/io.improbable.worker.sdk/.npmignore
  workers/unity/Packages/io.improbable.worker.sdk/.spot.version
Labels: A: maintenance, jira/no-ticket, size/XL

#1108 `AlphaLocatorFlow` tests
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/AlphaLocatorFlowTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/AlphaLocatorFlowTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionFlows.cs
Labels: A: core, jira/no-ticket, size/M

#1110 Make Options readonly, fix tests
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Components/Option.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Components/OptionTests.cs
Labels: A: core, jira/no-ticket, size/M

#1098 Feature/custom snapshot launch
  CHANGELOG.md
  workers/unity/Assets/Plugins/Editor.meta
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
  workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
Labels: A: playground, A: tooling, jira/no-ticket, size/M

#1113 opt-in reactive providers
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentProviders.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentProviders.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildProviders.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildProviders.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestProviders.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityProviders.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyProviders.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueProviders.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalProviders.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedProviders.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularProviders.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderContent.tt
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReferenceTypeProviderGenerator.tt
Labels: A: tooling, jira/no-ticket, size/XXL

#1111 Update readme
  README.md
Labels: jira/no-ticket, size/M

#1115 SendComponentSystem jobs improvement
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Systems/ComponentSendSystem.cs
Labels: A: core, jira/no-ticket, size/XS

#1118 Fix local launch on mac
  workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
Labels: A: tooling, jira/no-ticket, size/XS

#1114 Docs for `14.0.0` upgrade
  docs/projects/fps/tutorial.md
  docs/reference/concepts/connection-flows.md
  docs/reference/glossary.md
  docs/reference/workflows/monobehaviour/worker-connectors.md
  docs/variable.properties
Labels: T: documentation, jira/no-ticket, size/M

#1119 Docs/custom snapshot
  docs/reference/concepts/deployments.md
Labels: T: documentation, jira/no-ticket, size/XS

#1120 ENG-1429: Enable cross-site linting for unity docs.
  .toolsharerc
  ci/build-lint-preview.sh
Labels: A: maintenance, A: playground, T: documentation, do-not-merge/invalid-owners-file, jira/ENG, size/XS

#1124 Update prepare-project.md
  docs/modules/mobile/prepare-project.md
Labels: T: documentation, jira/no-ticket, size/XS

#1126 Update `current_version`
  docs/variable.properties
Labels: T: documentation, jira/no-ticket, size/XS

#1125 cherrypick 8090a13 (#1124)
  docs/modules/mobile/prepare-project.md
Labels: T: documentation, jira/no-ticket, size/XS

#1127 Cherry-pick #1126
  docs/variable.properties
Labels: T: documentation, jira/no-ticket, size/XS

#1129 Blank Project 101 (#1116)
  docs/assets/blank/tutorial/1/development-scene-hierarchy.png
  docs/assets/blank/tutorial/1/generating-code.png
  docs/assets/blank/tutorial/1/inspector-entities-hover.png
  docs/assets/blank/tutorial/1/inspector-entities-list.png
  docs/assets/blank/tutorial/1/inspector-workers-list-hover-client.png
  docs/assets/blank/tutorial/1/inspector-workers-list.png
  docs/assets/blank/tutorial/1/no-more-client.png
  docs/assets/blank/tutorial/1/scenes-list.png
  docs/assets/blank/tutorial/1/stop-worker-button.png
  docs/assets/blank/tutorial/1/stop-worker-window.png
  docs/assets/concepts/authority-areas.png
  docs/assets/concepts/client-workers.png
  docs/assets/concepts/component-details.png
  docs/assets/concepts/deployment.png
  docs/assets/concepts/interest-areas.gif
  docs/assets/concepts/layers-load-balancing.png
  docs/assets/concepts/trad-client-server.png
  docs/assets/concepts/workers-machines.png
  docs/assets/concepts/workers-world.png
  docs/assets/gdk-architecture-2.png
  docs/projects/blank/tutorial/1/player-lifecycle.md
  docs/projects/blank/tutorial/1/project-walkthrough.md
  docs/projects/blank/tutorial/1/spatialos.md
  docs/projects/blank/tutorial/1/summary.md
  docs/projects/blank/tutorial/1/what-it-does.md
  docs/projects/blank/tutorial/overview.md
  docs/projects/myo/setup/schema.md
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/XL

#1128 Print `PlayerConnection` port in SpatialOS console
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Utility/CommandLineUtility.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Labels: A: core, jira/UTY, size/M

#1131 UTY-2091: Fix crash on recursive options
  CHANGELOG.md
  init.ps1
  init.sh
  test-project/Assets/.schema/empty.schema
  test-project/Assets/.schema/test.schema
  test-project/Assets/Generated/Source/improbable/testschema/TypeA.cs
  test-project/Assets/Generated/Source/improbable/testschema/TypeB.cs
  test-project/Assets/Generated/Source/improbable/testschema/TypeC.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/Resources/exhaustive_bundle.json
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Tests/Model/DetailsStoreTests.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityFieldDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityTypeDetails.cs
Labels: A: tooling, jira/UTY, size/XXL

#1132 Add warning about recursive schema options
  docs/reference/concepts/code-generation.md
Labels: T: documentation, jira/no-ticket, size/XS

#1133 Port Forwarding UI
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/MenuPriorities.cs
  workers/unity/Packages/io.improbable.gdk.tools/PortForwardingWindow.cs
  workers/unity/Packages/io.improbable.gdk.tools/PortForwardingWindow.cs.meta
Labels: A: tooling, jira/no-ticket, size/L

#1130 Remote profiling docs
  docs/assets/workflows/remote-profiling-build-config.png
  docs/assets/workflows/remote-profiling-window-success.png
  docs/assets/workflows/remote-profiling-window.png
  docs/modules/core-and-feature-module-overview.md
  docs/modules/debug/require-inspector.md
  docs/modules/game-object-creation/custom-usage.md
  docs/modules/game-object-creation/standard-usage.md
  docs/modules/mobile/prepare-project.md
  docs/modules/player-lifecycle/basic-player-creation.md
  docs/modules/transform-sync/setup-transform.md
  docs/projects/blank/overview.md
  docs/projects/fps/tutorial.md
  docs/projects/myo/build.md
  docs/reference/concepts/worker.md
  docs/reference/glossary.md
  docs/reference/overview.md
  docs/reference/troubleshooting.md
  docs/toc.md
  docs/workflows/ecs/concepts/entity-contracts.md
  docs/workflows/ecs/concepts/system-update-order.md
  docs/workflows/ecs/concepts/temporary-components.md
  docs/workflows/ecs/interaction/authority.md
  docs/workflows/ecs/interaction/component-commands.md
  docs/workflows/ecs/interaction/component-data.md
  docs/workflows/ecs/interaction/events.md
  docs/workflows/ecs/interaction/reactive-components/entity-contracts.md
  docs/workflows/ecs/interaction/reactive-components/overview.md
  docs/workflows/ecs/interaction/world-commands.md
  docs/workflows/ecs/worker-entity.md
  docs/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/workflows/monobehaviour/interaction/reader-writers/index.md
  docs/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
  docs/workflows/monobehaviour/worker-connectors.md
  docs/workflows/overview.md
  docs/workflows/remote-profiling.md
Labels: T: documentation, jira/no-ticket, size/XL

#1137 Link to WorldCommands.EntityQuery.Request request
  docs/modules/debug/require-inspector.md
  docs/projects/fps/tutorial.md
  docs/toc.md
  docs/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
  docs/workflows/monobehaviour/interaction/reader-writers/overview.md
  docs/workflows/overview.md
Labels: T: documentation, jira/no-ticket, size/S
