Repository spatialos/gdk-for-unity, pull requests merged in 2019-10, with the labels that each got.

#1182 Update Windows Buildkite
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: jira/no-ticket, size/XS

#1188 Fix publish packages
  ci/publish_packages.sh
Labels: A: maintenance, jira/no-ticket, size/XS

#1189 Codegen line endings
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
Labels: A: tooling, jira/no-ticket, size/XS

#1194 Choose emulator/device to launch android app on + refactor mobile launcher
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidLaunchUtils.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/DeviceLaunchConfig.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/DeviceLaunchConfig.cs.meta
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLaunchConfig.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLaunchUtils.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLauncherWindow.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/iOSLaunchUtils.cs
Labels: A: mobile, jira/no-ticket, size/XL

#1197 Shrink local worker names for local development
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Worker/WorkerConnector.cs
Labels: A: core, jira/no-ticket, size/XS

#1198 Remove reactive components from docs
  docs/reference/glossary.md
  docs/toc.md
  docs/workflows/ecs/concepts/system-update-order.md
  docs/workflows/ecs/interaction/reactive-components/entity-contracts.md
  docs/workflows/ecs/interaction/reactive-components/overview.md
Labels: T: documentation, jira/no-ticket, size/M

#1199 Update mobile launch docs
  docs/modules/mobile/cloud-deploy.md
  docs/modules/mobile/local-deploy.md
Labels: T: documentation, jira/no-ticket, size/S

#1196 Codegen Split: GameObject Creation
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/Parts/UnityCommandSenderReceiverGeneratorPart.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/Parts/UnityComponentReaderWriterGeneratorPart.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Templates/UnityCommandSenderReceiverGenerator.tt
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Templates/UnityComponentReaderWriterGenerator.tt
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/package.json
Labels: A: core, A: game-object-creation, A: tooling, A: transform-synchronization, jira/no-ticket, size/M

#1201 TransformSync codegen partials
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/.codegen/Partials/Improbable.Gdk.TransformSynchronization.CompressedQuaternion
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/.codegen/Partials/Improbable.Gdk.TransformSynchronization.FixedPointVector3
Labels: A: transform-synchronization, jira/no-ticket, size/XS

#1204 Add OWNERS file
  OWNERS
Labels: jira/no-ticket, size/XS

#1205 Fix command response key leak
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/Systems/CommandCallbackSystem.cs
Labels: A: core, jira/no-ticket, size/XS

#1206 Quick code snippets fixes
  docs/projects/fps/tutorial.md
  docs/workflows/monobehaviour/interaction/commands/component-commands.md
Labels: T: documentation, jira/no-ticket, size/S

#1207 Inherited required test
  test-project/Assets/EditmodeTests/Subscriptions/InjectionCriteriaTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/RequiredSubscriptionsInfo.cs
Labels: A: core, jira/no-ticket, size/S
