Repository spatialos/gdk-for-unity, pull requests merged in 2019-05, with the labels that each got.

#926 Add more links to API docs
  docs/modules/core-and-feature-module-overview.md
  docs/modules/game-object-creation/custom-usage.md
  docs/modules/player-lifecycle/basic-player-creation.md
  docs/modules/player-lifecycle/heartbeating.md
  docs/modules/player-lifecycle/overview.md
  docs/modules/qbi-helper/overview.md
  docs/modules/transform-sync/how-it-works.md
  docs/modules/transform-sync/overview.md
  docs/modules/transform-sync/setup-transform.md
  docs/modules/transform-sync/strategies.md
  docs/projects/fps/get-started/build-workers.md
  docs/projects/fps/tutorial.md
  docs/reference/concepts/entity-lifecycle.md
  docs/reference/concepts/entity-templates.md
  docs/reference/concepts/logging.md
  docs/reference/mobile/android/cloud-deploy.md
  docs/reference/mobile/android/local-deploy.md
  docs/reference/mobile/ios/cloud-deploy.md
  docs/reference/mobile/ios/local-deploy.md
  docs/reference/workflows/ecs/entity-contracts.md
  docs/reference/workflows/ecs/interaction/authority.md
  docs/reference/workflows/ecs/interaction/commands/component-commands.md
  docs/reference/workflows/ecs/interaction/commands/world-commands.md
  docs/reference/workflows/ecs/interaction/component-updates.md
  docs/reference/workflows/ecs/interaction/events.md
  docs/reference/workflows/ecs/reactive-components.md
  docs/reference/workflows/ecs/temporary-components.md
  docs/reference/workflows/ecs/worker-entity.md
  docs/reference/workflows/monobehaviour/creating-workers.md
  docs/reference/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/events.md
Labels: T: documentation, size/XXL

#928 Assorted typo fixes in docs
  docs/modules/transform-sync/setup-transform.md
Labels: T: documentation, size/XS

#927 ENG-1276: enable all bk output to get logged, not just command
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: size/XS

#930 Rewrite 'which workflow' page
  docs/contributions/unity-gdk-coding-standards.md
  docs/index.md
  docs/modules/core-and-feature-module-overview.md
  docs/modules/game-object-creation/standard-usage.md
  docs/modules/player-lifecycle/basic-player-creation.md
  docs/modules/player-lifecycle/custom-player-creation.md
  docs/modules/player-lifecycle/heartbeating.md
  docs/modules/qbi-helper/intro-to-qbi.md
  docs/modules/transform-sync/strategies.md
  docs/projects/blank/overview.md
  docs/projects/fps/get-started/get-playing.md
  docs/projects/fps/get-started/view-game-world.md
  docs/projects/fps/overview.md
  docs/projects/fps/tutorial.md
  docs/projects/myo/build.md
  docs/projects/myo/setup.md
  docs/projects/overview.md
  docs/reference/concepts/code-generation.md
  docs/reference/concepts/connection-flows.md
  docs/reference/concepts/deployments.md
  docs/reference/concepts/entity-lifecycle.md
  docs/reference/concepts/logging.md
  docs/reference/concepts/snapshots.md
  docs/reference/concepts/worker.md
  docs/reference/glossary.md
  docs/reference/mobile/android/cloud-deploy.md
  docs/reference/mobile/android/local-deploy.md
  docs/reference/mobile/android/run-client.md
  docs/reference/mobile/android/setup.md
  docs/reference/mobile/ios/cloud-deploy.md
  docs/reference/mobile/ios/local-deploy.md
  docs/reference/mobile/ios/run-client.md
  docs/reference/mobile/ios/setup.md
  docs/reference/mobile/overview.md
  docs/reference/overview.md
  docs/reference/workflows/ecs/entity-contracts.md
  docs/reference/workflows/ecs/interaction/authority.md
  docs/reference/workflows/ecs/interaction/commands/component-commands.md
  docs/reference/workflows/ecs/interaction/component-updates.md
  docs/reference/workflows/ecs/interaction/events.md
  docs/reference/workflows/ecs/reactive-components.md
  docs/reference/workflows/ecs/system-update-order.md
  docs/reference/workflows/ecs/temporary-components.md
  docs/reference/workflows/ecs/worker-entity.md
  docs/reference/workflows/monobehaviour/creating-workers.md
  docs/reference/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/index.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
  docs/reference/workflows/overview.md
  docs/reference/workflows/which-workflow.md
  docs/toc.md
  docs/welcome.md
Labels: T: documentation, size/XL

#932 Fix link to machine setup.
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
Labels: A: tooling, size/XS

#934 Adding check for valid entity
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
Labels: A: core, size/XS

#933 Update dotnet core sdk version + link
  docs/fragments/machine-setup.md
Labels: T: documentation, size/S

#938 Deployment Launcher Feature Module
  CHANGELOG.md
  workers/unity/Assets/Playground/Config/DeploymentLauncherConfig.asset
  workers/unity/Assets/Playground/Config/DeploymentLauncherConfig.asset.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/List.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Stop.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/DeploymentLauncher.csproj
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Ipc.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Options.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Program.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/.DeploymentLauncher/README.md
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Assembly.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Assembly.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Authentication.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Authentication.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Deployment.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/Deployment.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/WrappedTask.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Commands/WrappedTask.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncherConfig.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncherConfig.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Improbable.Gdk.DeploymentLauncher.asmdef
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Improbable.Gdk.DeploymentLauncher.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Ipc.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/Ipc.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/TaskManager.cs
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/TaskManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/package.json
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/package.json.meta
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/GraphicsSettings.asset
Labels: A: playground, size/XXL

#937 Mobile docs update
  docs/modules/core-and-feature-module-overview.md
  docs/modules/mobile/cloud-deploy.md
  docs/modules/mobile/local-deploy.md
  docs/modules/mobile/overview.md
  docs/modules/mobile/prepare-project.md
  docs/modules/mobile/run-client.md
  docs/modules/mobile/setup-android.md
  docs/modules/mobile/setup-ios.md
  docs/reference/concepts/connection-flows.md
  docs/reference/mobile/android/cloud-deploy.md
  docs/reference/mobile/android/local-deploy.md
  docs/reference/mobile/android/run-client.md
  docs/reference/mobile/android/setup.md
  docs/reference/mobile/ios/cloud-deploy.md
  docs/reference/mobile/ios/local-deploy.md
  docs/reference/mobile/ios/run-client.md
  docs/reference/mobile/ios/setup.md
  docs/reference/mobile/overview.md
  docs/reference/workflows/monobehaviour/creating-workers.md
  docs/toc.md
Labels: T: documentation, size/XXL

#940 updating tutorial
  docs/assets/health-pickups-tutorial/health-bar-enable.gif
  docs/projects/fps/tutorial.md
Labels: T: documentation, size/M

#943 Typo in player lifecycle module doc
  docs/modules/player-lifecycle/basic-player-creation.md
Labels: T: documentation, size/XS

#931 DOC-1068 - Branding update. New screenshots and index page header.
  docs/assets/fps/by-yourself.png
  docs/assets/fps/enemies.png
  docs/assets/fps/fps-starter-enemies.png
  docs/assets/fps/fps-starter-headline.png
  docs/assets/fps/headline.png
  docs/assets/spatialos-gdkforunity-header.png
  docs/index.md
  docs/projects/fps/get-started/get-playing.md
  docs/projects/fps/get-started/get-started.md
  docs/projects/fps/overview.md
Labels: T: documentation, size/XS

#941 Deployment Launcher docs
  docs/assets/deployment-window.png
  docs/assets/full-dpl-launcher-window.png
  docs/assets/modules/deployment-launcher/assembly-upload.png
  docs/assets/modules/deployment-launcher/choose-launch-config.png
  docs/assets/modules/deployment-launcher/deployment-configurations-label.png
  docs/assets/modules/deployment-launcher/dpl-configs-sim.png
  docs/assets/modules/deployment-launcher/dpl-configs.png
  docs/assets/modules/deployment-launcher/manage-deployments-empty.png
  docs/assets/modules/deployment-launcher/manage-deployments.png
  docs/assets/modules/deployment-launcher/refresh-button.png
  docs/assets/modules/deployment-launcher/remove-simplayer-dpl-config.png
  docs/assets/modules/deployment-launcher/stop-deployments-choice.png
  docs/assets/upload-assembly.png
  docs/modules/deployment-launcher/launch-deployments.md
  docs/modules/deployment-launcher/manage-deployments.md
  docs/modules/deployment-launcher/overview.md
  docs/modules/deployment-launcher/upload-assemblies.md
  docs/projects/fps/get-started/upload-launch.md
  docs/toc.md
Labels: T: documentation, size/XL

#946 Add deployment launcher to feature module overview
  docs/modules/core-and-feature-module-overview.md
Labels: T: documentation, size/XS

#942 Release 0.2.2
  CHANGELOG.md
  README.md
  ci/generate-docs.sh
  packer.config.json
  spatialos_gdk_for_unity_header.png
  test-project/Packages/com.improbable.gdk.dependencytest/package.json
  test-project/Packages/com.improbable.gdk.dependencytestchild/package.json
  test-project/Packages/com.improbable.gdk.dependencytestgrandchild/package.json
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.deploymentlauncher/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/DefaultMobileWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.querybasedinteresthelper/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: mobile, A: player-lifecycle, A: tooling, A: transform-synchronization, size/M

#948 Import DAT file using relative path
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs
Labels: A: tooling, size/XS

#947 0.2.2 docs fixes
  docs/modules/deployment-launcher/launch-deployments.md
  docs/modules/deployment-launcher/manage-deployments.md
  docs/modules/deployment-launcher/upload-assemblies.md
  docs/projects/fps/get-started/upload-launch.md
  docs/projects/myo/setup.md
  docs/reference/glossary.md
Labels: T: documentation, size/M

#949 changing url from develop to master
  docs/modules/mobile/prepare-project.md
Labels: T: documentation, size/XS

#950 Minor docs nits 0.2.2
  docs/projects/fps/get-started/upload-launch.md
Labels: T: documentation, size/XS

#951 Unity 2019.1.3f1 upgrade
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  CHANGELOG.md
  test-project/ProjectSettings/ProjectVersion.txt
  test-project/ProjectSettings/XRSettings.asset
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/XRSettings.asset
Labels: A: maintenance, T: enhancement, size/S

#952 Fixed world being disposed multiple times
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Utility/TaskUtility.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/TaskUtility.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
Labels: A: core, size/M
