Repository spatialos/gdk-for-unity, pull requests merged in 2019-07, with the labels that each got.

#1011 Remove test exception from playground
  CHANGELOG.md
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CubeSpawnerInputBehaviour.cs
Labels: A: playground, size/XS

#1014 add network and hardware specs
  docs/fragments/machine-setup.md
Labels: T: documentation, size/XS

#1013 Add `LinkedGameObjectMap` API
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/EntityGameObjectLinker.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedGameObjectMap.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/LinkedGameObjectMap.cs.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/LinkedGameObjectMapSubscriptionManager.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/LinkedGameObjectMapSubscriptionManager.cs.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/Improbable.Gdk.GameObjectCreation.EditmodeTests.asmdef.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/LinkedGameObjectMapSubscriptionTests.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/LinkedGameObjectMapSubscriptionTests.cs.meta
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/MockGameObjectCreator.cs
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/Tests/Editmode/MockGameObjectCreator.cs.meta
Labels: A: core, A: game-object-creation, T: feature, size/L

#1012 Split build target from build environment
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  CHANGELOG.md
  UPGRADE_GUIDE.md
  ci/build-test.sh
  ci/docs-lint.sh
  ci/launch.sh
  ci/shared-ci.pinned
  ci/test.sh
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: A: build-system, A: maintenance, jira/no-ticket, size/L

#1015 Fix NPM CI
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/bootstrap.sh
  test-project/Packages/manifest.json
Labels: A: maintenance, jira/no-ticket, size/S

#1028 Disable premerge for docs branches
  .buildkite/premerge.definition.yaml
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: jira/no-ticket, size/XS

#1029 cherry-pick linting fixes
  docs/modules/core-and-feature-module-overview.md
  docs/projects/blank/overview.md
  docs/projects/fps/get-started/get-started.md
  docs/projects/fps/overview.md
  docs/reference/glossary.md
Labels: T: documentation, jira/no-ticket, size/S

#1027 Fix `PlayerLifecycleHelper.IsOwningWorker`
  CHANGELOG.md
  test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef
  test-project/Assets/EditmodeTests/PlayerLifecycle.meta
  test-project/Assets/EditmodeTests/PlayerLifecycle/PlayerLifecycleHelperTests.cs
  test-project/Assets/EditmodeTests/PlayerLifecycle/PlayerLifecycleHelperTests.cs.meta
  test-project/Packages/manifest.json
  workers/unity/Packages/io.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
Labels: A: player-lifecycle, jira/no-ticket, size/M

#1016 Requireable WorkerId
  CHANGELOG.md
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Character.prefab
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerIdTest.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerIdTest.cs.meta
  workers/unity/Assets/Plugins.meta
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorkerIdSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorkerIdSubscriptionManager.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Subscriptions/StandardSubscriptionTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Subscriptions/WorkerIdEquatableTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Subscriptions/WorkerIdEquatableTests.cs.meta
  workers/unity/ProjectSettings/QualitySettings.asset
Labels: A: core, A: playground, jira/no-ticket, size/L

#1033 Remove docs-related steps from non-docs pipeline
  .buildkite/premerge.steps.yaml
  ci/docs-build-verification.sh
Labels: A: maintenance, jira/no-ticket, size/M

#1036 Stop linux schema compiler overriding mac one
  init.ps1
  init.sh
Labels: jira/no-ticket, size/XS

#1038 Set the correct worker scenes in the buildconfig
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
Labels: A: playground, jira/no-ticket, size/XS

#1039 Fix deployment launch
  ci/launch.sh
  ci/shared-ci.pinned
Labels: A: maintenance, jira/no-ticket, size/S

#1040 Fix xcode paths
  CHANGELOG.md
  workers/unity/Packages/io.improbable.worker.sdk.mobile/BuildPostProcessXCode.cs
  workers/unity/Packages/io.improbable.worker.sdk.mobile/BuildPostProcessXCode.cs.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Improbable.Worker.Sdk.Mobile.asmdef
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Improbable.Worker.Sdk.Mobile.asmdef.meta
Labels: jira/no-ticket, size/L

#1042 Fix mac symlinks
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: build-system, A: core, A: game-object-creation, A: mobile, A: player-lifecycle, A: tooling, A: transform-synchronization, jira/no-ticket, size/S

#1045 Fix mobile package version dependency
  workers/unity/Packages/io.improbable.gdk.mobile/package.json
Labels: A: mobile, jira/no-ticket, size/XS

#1031 Upgrade docs for NPM
  docs/.hiddendocs
  docs/modules/build-system/overview.md
  docs/modules/deployment-launcher/overview.md
  docs/modules/game-object-creation/overview.md
  docs/modules/game-object-creation/standard-usage.md
  docs/modules/mobile/overview.md
  docs/modules/player-lifecycle/overview.md
  docs/modules/qbi-helper/overview.md
  docs/modules/transform-sync/overview.md
  docs/projects/fps/get-started/build-workers.md
  docs/projects/fps/get-started/get-playing.md
  docs/projects/fps/get-started/get-started.md
  docs/projects/fps/get-started/set-up.md
  docs/projects/myo/setup.md
  docs/reference/glossary.md
  docs/toc.md
  docs/variable.properties
Labels: T: documentation, jira/no-ticket, size/L

#1030 Docs lint/build/upload/publish pipeline
  .buildkite/docs.definition.yaml
  .buildkite/docs.steps.yaml
  .toolsharerc
  ci/bootstrap.sh
  ci/build-upload-docs.sh
  ci/docker/docs-linter.Dockerfile
  ci/lint-docs.sh
  ci/shared-ci.pinned
  ci/tag-docs.sh
  ci/tools.sh
Labels: T: documentation, jira/no-ticket, size/XL

#1048 Exit docs release if not on docs-current
  ci/tag-docs.sh
Labels: T: documentation, jira/no-ticket, size/XS

#1049 Add `SpatialOSEntity.TryGetComponent`
  CHANGELOG.md
  UPGRADE_GUIDE.md
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectCreatorFromMetadata.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/SpatialOSEntity.cs
Labels: A: game-object-creation, T: enhancement, jira/no-ticket, size/M

#1050 Replace GetExistingManager with GetExistingSystem
  docs/modules/player-lifecycle/custom-player-creation.md
  docs/reference/concepts/logging.md
Labels: T: documentation, jira/no-ticket, size/XS

#1051 replacing GetExistingManager with GetExistingSystem (#1050)
  docs/modules/player-lifecycle/custom-player-creation.md
  docs/reference/concepts/logging.md
Labels: T: documentation, jira/no-ticket, size/XS

#1055 Docs for Worker SDK 13.8.2 changes
  .github/CONTRIBUTING.md
  docs/index.md
  docs/modules/deployment-launcher/launch-deployments.md
  docs/modules/deployment-launcher/manage-deployments.md
  docs/modules/deployment-launcher/upload-assemblies.md
  docs/modules/mobile/cloud-deploy.md
  docs/modules/mobile/overview.md
  docs/modules/mobile/prepare-project.md
  docs/modules/player-lifecycle/heartbeating.md
  docs/modules/qbi-helper/intro-to-qbi.md
  docs/pricing-and-support/pricing.md
  docs/pricing-and-support/support.md
  docs/projects/blank/overview.md
  docs/projects/fps/get-started/upload-launch.md
  docs/projects/fps/get-started/view-game-world.md
  docs/projects/fps/tutorial.md
  docs/projects/myo/setup.md
  docs/reference/concepts/code-generation.md
  docs/reference/concepts/connection-flows.md
  docs/reference/concepts/deployments.md
  docs/reference/concepts/entity-templates.md
  docs/reference/concepts/snapshots.md
  docs/reference/concepts/worker.md
  docs/reference/glossary.md
  docs/reference/overview.md
  docs/reference/workflows/ecs/interaction/authority.md
  docs/reference/workflows/ecs/interaction/component-commands.md
  docs/reference/workflows/ecs/interaction/events.md
  docs/reference/workflows/ecs/interaction/reactive-components/overview.md
  docs/reference/workflows/ecs/interaction/world-commands.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/index.md
  docs/reference/workflows/monobehaviour/worker-connectors.md
  docs/toc.md
  docs/variable.properties
  docs/welcome.md
Labels: T: documentation, jira/no-ticket, size/XL

#1054 Add page on how to add schema source dir
  docs/assets/blank/schema/add-schema-source-after.png
  docs/assets/blank/schema/add-schema-source-before.png
  docs/assets/blank/schema/select-tools-config.png
  docs/projects/blank/setup/schema.md
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/M

#1060 Reactive components docs updates
  docs/reference/workflows/ecs/interaction/reactive-components/overview.md
Labels: T: documentation, jira/no-ticket, size/XS

#1058 UTY-1914: Refresh logging docs section
  docs/reference/concepts/logging.md
  docs/toc.md
Labels: T: documentation, jira/UTY, size/L

#1061 Lay groundwork for serialization overrides
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityTypeContent.tt
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Tests/Model/DetailsStoreTests.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGenerator.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/CodeGeneratorOptions.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/Details/UnityTypeDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: tooling, jira/no-ticket, size/M

#1065 Tidy up Buildkite logs
  ci/bootstrap.sh
  ci/docs-lint.sh
  ci/launch.sh
  ci/shared-ci.pinned
  ci/test.sh
Labels: A: maintenance, jira/no-ticket, size/M

#1066 Add page on how to add schema source dir (#1054)
  docs/assets/blank/schema/add-schema-source-after.png
  docs/assets/blank/schema/add-schema-source-before.png
  docs/assets/blank/schema/select-tools-config.png
  docs/projects/blank/setup/schema.md
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/M

#1063 More type conversion methods
  CHANGELOG.md
  UPGRADE_GUIDE.md
  test-project/Assets/EditmodeTests/Conversions.meta
  test-project/Assets/EditmodeTests/Conversions/CoordinatesTests.cs
  test-project/Assets/EditmodeTests/Conversions/CoordinatesTests.cs.meta
  test-project/Assets/EditmodeTests/Conversions/EdgeLengthTests.cs
  test-project/Assets/EditmodeTests/Conversions/EdgeLengthTests.cs.meta
  test-project/Assets/EditmodeTests/Improbable.Gdk.EditModeTests.asmdef
  test-project/Assets/EditmodeTests/Operators.meta
  test-project/Assets/EditmodeTests/Operators/CompressedQuaternionTests.cs
  test-project/Assets/EditmodeTests/Operators/CompressedQuaternionTests.cs.meta
  test-project/Assets/EditmodeTests/Operators/CoordinatesTests.cs
  test-project/Assets/EditmodeTests/Operators/CoordinatesTests.cs.meta
  test-project/Assets/EditmodeTests/Operators/EdgeLengthTests.cs
  test-project/Assets/EditmodeTests/Operators/EdgeLengthTests.cs.meta
  test-project/Assets/EditmodeTests/Operators/FixedPointVector3Tests.cs
  test-project/Assets/EditmodeTests/Operators/FixedPointVector3Tests.cs.meta
  test-project/Packages/manifest.json
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/QueryBasedInterestUtils.cs
  workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/QueryBasedInterestUtils.cs.meta
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/GdkCodeGenerator.csproj
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.Coordinates
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.EdgeLength
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.Gdk.TransformSynchronization.CompressedQuaternion
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Partials/Improbable.Gdk.TransformSynchronization.FixedPointVector3
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DirectTransformUpdateSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/RateLimitedPositionSendSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/RateLimitedTransformSendSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformUtils.cs
Labels: A: playground, A: tooling, A: transform-synchronization, jira/no-ticket, size/XXL

#1062 Glossary refresh
  docs/modules/core-and-feature-module-overview.md
  docs/projects/fps/get-started/set-up.md
  docs/projects/fps/get-started/upload-launch.md
  docs/reference/concepts/worker.md
  docs/reference/glossary.md
Labels: T: documentation, jira/no-ticket, size/XXL

#1067 Type conversions docs
  docs/modules/transform-sync/utilities.md
  docs/reference/concepts/code-generation.md
  docs/toc.md
Labels: T: documentation, jira/no-ticket, size/M

#1069 Fix code snippet
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
Labels: T: documentation, jira/no-ticket, size/XS

#1070 Fix code snippet (#1069)
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
Labels: T: documentation, jira/no-ticket, size/XS

#1072 Update build system cli docs
  docs/modules/build-system/cli.md
Labels: T: documentation, jira/no-ticket, size/S

#1068 Coalesce build/lint/preview steps + emojis
  .buildkite/docs.steps.yaml
  ci/bootstrap.sh
  ci/build-lint-preview.sh
  ci/build-upload-docs.sh
  ci/docker/docs-linter.Dockerfile
  ci/shared-ci.pinned
  ci/tag-docs.sh
  ci/tools.sh
  docs/projects/blank/overview.md
  docs/projects/fps/tutorial.md
  docs/projects/myo/setup.md
  docs/reference/concepts/entity-templates.md
  docs/reference/glossary.md
  docs/reference/workflows/ecs/interaction/authority.md
  docs/reference/workflows/ecs/interaction/reactive-components/overview.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/index.md
Labels: T: documentation, jira/no-ticket, size/L

#1075 Exit if we get linting errors
  ci/build-lint-preview.sh
Labels: T: documentation, jira/no-ticket, size/XS

#1064 Add MVP implementation for Unity 2D support
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/AssemblyInfo.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/AssemblyInfo.cs.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/ITransformSync.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/ITransformSync.cs.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/RigidbodyTransformSync.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformImplementations/RigidbodyTransformSync.cs.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformUtils.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Improbable.Gdk.TransformSynchronization2D.asmdef
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Improbable.Gdk.TransformSynchronization2D.asmdef.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Rigidbody2DTransformSync.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/Rigidbody2DTransformSync.cs.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/TransformSynchronizationHelper2D.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/TransformSynchronizationHelper2D.cs.meta
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json.meta
  workers/unity/Packages/manifest.json
Labels: A: game-object-creation, A: transform-synchronization, jira/no-ticket, size/XXL

#1083 Remove leftover 13.7.1 references
  CHANGELOG.md
  spatialos.json
  workers/unity/Packages/io.improbable.gdk.core/package.json
  workers/unity/Packages/io.improbable.gdk.mobile/package.json
  workers/unity/Packages/io.improbable.gdk.tools/core-sdk.version
  workers/unity/Packages/io.improbable.gdk.tools/core-sdk.version.meta
Labels: A: core, A: mobile, A: tooling, jira/no-ticket, size/S
