Repository spatialos/gdk-for-unity, pull requests merged in 2019-03, with the labels that each got.

#803 More fixes found from the fps starter project upgrade
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/RequireLifecycleSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/EntitySystem.cs
  workers/unity/Packages/com.improbable.gdk.core/View/View.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: player-lifecycle, A: playground, A: tooling, A: transform-synchronization, size/M

#807 Get commands received by index
  workers/unity/Packages/com.improbable.gdk.core/Collections/ReceivedMessagesSpan.cs
  workers/unity/Packages/com.improbable.gdk.core/Commands/CommandComponents.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/CommandRequestCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CommandSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/DiffStorage.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorldCommandsReceivedStorage.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/CommandDiffStorageGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityCommandPayloadGenerator.tt
Labels: A: core, A: tooling, size/L

#808 Update the view when sending an update. Disable loopback
  workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentUpdateSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/View/View.cs
  workers/unity/Packages/com.improbable.gdk.core/View/ViewStorage.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/MessagesToSend.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ViewDiff.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentSenderGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ViewStorageGenerator.tt
Labels: A: core, A: tooling, size/M

#811 Feature/fix incorrect delete cube error
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/CubeSpawnerInputBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/DeleteCubeCommandReceiver.cs
Labels: A: playground, size/S

#812 Replaced uses of GetAssemblies with a reflection helper that caches r…
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/ComponentDatabase.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/AcknowledgeAuthorityLossSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CommandSenderComponentSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveCommandComponentSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Systems/SubscriptionSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/CleanTemporaryComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/EcsViewSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ReflectionUtility.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/ReflectionUtility.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/View/View.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ConnectionHandlers/CommandMetaData.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/MessagesToSend.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/OpListDeserializer.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/ViewDiff.cs
Labels: A: core, size/XL

#806 Add Application.isPlaying check to WorkerConnector
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
Labels: A: core, size/XS

#804 Improve Get Started and fix Add Your First Feature
  docs/assets/deployment-window.png
  docs/assets/worker-flags-modification.png
  docs/content/get-started/build-workers.md
  docs/content/get-started/get-playing.md
  docs/content/get-started/set-up.md
  docs/projects/fps/tutorial.md
Labels: T: documentation, size/M

#805 Build system: Android SDK check & active target switch
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: A: build-system, size/M

#813 Fix prefab processor
  CHANGELOG.md
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Character.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Cube.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Common/MobileConnectionSplashScreen.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Common/Spinner.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Level.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/UIGameObject.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/UnityGameLogic/Cube.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/AndroidClientWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/ClientWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/GameLogicWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/iOSClientWorker.prefab
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Editor/Prefabs/PrefabPreprocessor.cs
Labels: A: core, A: playground, size/XXL

#800 Add Snapshot Constructors
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Generators/Parts/UnityComponentDataGeneratorPart.cs
Labels: A: core, A: game-object-creation, A: player-lifecycle, A: playground, A: tooling, A: transform-synchronization, size/L

#809 Pass arbitrary data to CreatePlayerRequestType
  CHANGELOG.md
  schema/playground/player_creation_arguments.schema
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/ShouldRequestPlayerTag.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Components/ShouldRequestPlayerTag.cs.meta
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/player_creator.schema
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Labels: A: player-lifecycle, A: playground, T: enhancement, size/M

#816 Remove fastlane
  ci/build-ios.sh
Labels: A: maintenance, size/S

#735 Added menu item for DAT generation
  .gitignore
  CHANGELOG.md
  workers/unity/Assets/.gitignore
  workers/unity/Assets/Config/GdkToolsConfiguration.json
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs
  workers/unity/Packages/com.improbable.gdk.tools/DevAuthTokenUtils.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
  workers/unity/Packages/com.improbable.gdk.tools/GdkToolsConfigurationWindow.cs.meta
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/MenuPriorities.cs
Labels: A: mobile, A: playground, A: tooling, T: feature, size/L

#799 Add Required Build Flag
  CHANGELOG.md
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildConfigEditorStyle.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildEnvironmentConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/Configuration/WorkerBuildData.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: A: build-system, A: playground, T: feature, size/L

#771 Improved error visibility when code generation breaks.
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/dependencies/Improbable.TextTemplating/Improbable.TextTemplating.dll
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/Improbable.TextTemplating/TransformAllTask.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Labels: A: codegen, A: tooling, T: enhancement, size/L

#818 Worker SDK 13.6.2 Upgrade
  CHANGELOG.md
  spatialos.json
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Labels: A: core, A: mobile, A: tooling, size/S

#829 Large performance boost for ComponentSendSystem
  workers/unity/Packages/com.improbable.gdk.core/CodegenAdapters/IComponentReplicationHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentSenderGenerator.tt
Labels: A: core, A: tooling, size/S

#815 Clarify health pickups tutorial.
  docs/assets/health-pickups-tutorial/health-pickup-codegen.png
  docs/projects/fps/tutorial.md
Labels: T: documentation, size/XL

#832 Update tutorial.md
  docs/projects/fps/tutorial.md
Labels: size/XS

#830 A failed spawn player command is now retried again
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Labels: A: player-lifecycle, size/XS

#833 Clarify the prefab duplication workflow.
  docs/projects/fps/tutorial.md
Labels: size/XS

#834 Fix the order of steps for client launching and improve prefab duplication steps
  docs/projects/fps/tutorial.md
Labels: size/S

#828 Fix a race on component update loopbacks
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsViewStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentViewStorage.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ViewStorageGenerator.tt
Labels: A: tooling, T: bug, size/M

#827 Add generate api docs script
  ci/generate-docs.sh
Labels: A: maintenance, size/M

#826 Removed use of the EntityManager from updating ecs components
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityEcsViewManagerGenerator.tt
Labels: A: core, A: tooling, size/XS

#817 Remove the dispatcher
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.core/Dispatcher.cs
  workers/unity/Packages/com.improbable.gdk.core/Dispatcher.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
Labels: A: core, T: refactor, size/XXL

#824 Sort while deserialising
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsUpdateSender.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentUpdateSender.cs
  workers/unity/Packages/com.improbable.gdk.core/Collections/MessageList.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffStorageGenerator.tt
Labels: A: core, A: tooling, size/XXL

#823 Harvest android binaries to artifacts
  .buildkite/premerge.steps.yaml
Labels: size/XS

#836 Crash Workaround
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKeyEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValueEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptionalEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeatedEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingularEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponentEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/ConnectionEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponentEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommandsEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEventsEcsViewManager.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentComponentDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponentEcsViewManager.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/ComponentDiffDeserializerGenerator.tt
Labels: A: tooling, T: bug, size/L

#839 Feature/fix list insert
  workers/unity/Packages/com.improbable.gdk.core/Collections/MessageList.cs
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/Callbacks.cs
Labels: A: core, size/XS

#835 Reactive Systems now use concurrent jobs for chunk gathering
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/CodegenAdapters/AcknowledgeAuthorityLossHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/CodegenAdapters/ComponentCleanupHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/CodegenAdapters/IReactiveComponentReplicationHandler.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/AcknowledgeAuthorityLossSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReactiveComponentHandlersGenerator.tt
Labels: A: core, A: playground, A: tooling, T: enhancement, size/L

#842 Reactive small changes
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/AcknowledgeAuthorityLossSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/CleanReactiveComponentsSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/ReactiveComponents/Systems/ReactiveComponentSendSystem.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/ComponentSendSystem.cs
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: mobile, A: player-lifecycle, A: playground, A: tooling, A: transform-synchronization, size/M

#838 New BuildKite queue for update-rollups
  .buildkite/premerge.steps.yaml
Labels: size/XS

#846 Removed an old tt file that isn't used any more
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityReaderWriterGenerator.tt
Labels: A: tooling, size/L

#847 Remove serialization helpers from code
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
Labels: A: player-lifecycle, size/S

#845 Updated the tutorial for core 0.2
  docs/projects/fps/tutorial.md
Labels: T: documentation, size/S

#849 Change-log typo
  CHANGELOG.md
Labels: size/XS

#797 update deployment window picture + upload-launch doc
  docs/assets/deployment-window.png
  docs/content/get-started/upload-launch.md
Labels: T: documentation, size/S

#852 Added Laura's feedback to changelog
  CHANGELOG.md
Labels: size/S

#819 Core v2 docs update
  docs/assets/update-order.png
  docs/content/build.md
  docs/content/code-generator.md
  docs/content/connecting-to-spatialos.md
  docs/content/deploy.md
  docs/content/ecs/authority.md
  docs/content/ecs/component-data.md
  docs/content/ecs/component-generation.md
  docs/content/ecs/component-updates.md
  docs/content/ecs/custom-replication-system.md
  docs/content/ecs/entity-contracts.md
  docs/content/ecs/events.md
  docs/content/ecs/logging.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/ecs/system-update-order.md
  docs/content/ecs/world-commands.md
  docs/content/entity-templates.md
  docs/content/gameobject/api-workerconnector.md
  docs/content/gameobject/create-delete-spatialos-entities.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
  docs/content/gameobject/interact-spatialos-monobehaviours.md
  docs/content/gameobject/linking-spatialos-entities.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/gameobject/readers-writers.md
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/sending-receiving-events.md
  docs/content/gameobject/spatialoscomponent.md
  docs/content/gameobject/world-commands.md
  docs/content/glossary.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/set-up-new-project.md
  docs/content/troubleshooting.md
  docs/content/workers/api-worker-system.md
  docs/content/workers/api-worker.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
  docs/content/world-component-commands-requests-responses.md
  docs/toc.md
Labels: T: documentation, size/XXL

#820 Player lifecycle docs update
  docs/content/get-started/build-workers.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
Labels: T: documentation, size/M

#853 Add 4.7.1 developer pack to the rider setup
  docs/setup-and-installing.md
Labels: T: documentation, size/XS

#851 `0.2.0` release pre-validation
  CHANGELOG.md
  packer.config.json
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: A: build-system, A: core, A: game-object-creation, A: mobile, A: player-lifecycle, A: tooling, A: transform-synchronization, size/M

#854 0.2.0 docs live patch
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/world-commands.md
  docs/content/world-component-commands-requests-responses.md
  docs/projects/blank/overview.md
Labels: T: documentation, size/S

#857 Explicitly include toc
  docs/toc.md
Labels: T: documentation, size/L

#858 Update generate docs script to use new docs branches
  ci/generate-docs.sh
Labels: A: maintenance, T: refactor, size/XS

#862 Tooling PackageManager refactor
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Labels: A: tooling, T: refactor, size/M

#863 ENG-1281: trigger.sh is no longer necessary.
  .buildkite/trigger.sh
Labels: size/XS

#864 Bump BK queue ID
  .buildkite/release-qa.steps.yaml
Labels: T: bug, size/XS

#861 Cleanup get started pages
  docs/assets/overview-page-inspector.png
  docs/assets/overview-page-share.png
  docs/assets/overview-page-worker-flags.png
  docs/assets/overview-page.png
  docs/content/get-started/build-workers.md
  docs/content/get-started/get-playing.md
  docs/content/get-started/get-started.md
  docs/content/get-started/set-up.md
  docs/content/get-started/upload-launch.md
  docs/content/get-started/view-game-world.md
  docs/toc.md
Labels: T: documentation, T: refactor, size/XL

#865 Fix little typo
  docs/content/get-started/set-up.md
Labels: T: documentation, size/XS

#866 Health packs tutorial tweaks
  docs/projects/fps/tutorial.md
Labels: T: documentation, T: refactor, size/XL

#868 FPS tutorial fixes
  docs/projects/fps/tutorial.md
Labels: T: bug, T: documentation, size/XS

#867 Table of contents tweaks
  docs/content/connecting-to-spatialos.md
  docs/content/ecs/authority.md
  docs/content/ecs/component-generation.md
  docs/content/ecs/component-updates.md
  docs/content/ecs/events.md
  docs/content/ecs/logging.md
  docs/content/ecs/reactive-components.md
  docs/content/ecs/sending-receiving-component-commands.md
  docs/content/ecs/world-commands.md
  docs/content/entity-lifecycle.md
  docs/content/entity-templates.md
  docs/content/gameobject/create-delete-spatialos-entities.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
  docs/content/gameobject/interact-spatialos-monobehaviours.md
  docs/content/gameobject/linking-spatialos-entities.md
  docs/content/gameobject/linking-workers-gameobjects.md
  docs/content/gameobject/reading-and-writing-component-data.md
  docs/content/gameobject/sending-receiving-commands.md
  docs/content/gameobject/sending-receiving-events.md
  docs/content/get-started/build-workers.md
  docs/content/get-started/set-up.md
  docs/content/intro-workflows-spatialos-entities.md
  docs/content/mobile/android/ways-to-test.md
  docs/content/mobile/ios/ways-to-test.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/troubleshooting.md
  docs/content/workers/worker-entity.md
  docs/content/workers/workers-in-the-gdk.md
  docs/fragments/machine-setup.md
  docs/known-issues.md
  docs/machine-setup.md
  docs/toc.md
Labels: T: documentation, T: refactor, size/XL

#859 Player lifecycle improvements
  CHANGELOG.md
  snapshots/default.snapshot
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityTemplate.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Schema/player_creator.schema
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/HandleCreatePlayerRequestSystem.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Labels: A: core, A: player-lifecycle, A: playground, size/XL

#872 Fix package dependencies
  CHANGELOG.md
  README.md
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
Labels: A: core, A: player-lifecycle, T: bug, size/XS

#875 Forgot the deployment docs
  docs/projects/myo/build.md
  docs/reference/concepts/deployments.md
  docs/reference/concepts/snapshots.md
  docs/reference/glossary.md
  docs/toc.md
Labels: T: documentation, size/XS

#876 Hotfix
  docs/reference/concepts/code-generation.md
  docs/reference/concepts/connection-flows.md
  docs/reference/concepts/deployments.md
  docs/reference/concepts/entity-lifecycle.md
  docs/reference/concepts/entity-templates.md
  docs/reference/concepts/logging.md
  docs/reference/concepts/snapshots.md
  docs/reference/concepts/worker.md
  docs/reference/glossary.md
  docs/reference/mobile/android/cloud-deploy.md
  docs/reference/mobile/android/local-deploy.md
  docs/reference/mobile/android/run-client.md
  docs/reference/mobile/ios/cloud-deploy.md
  docs/reference/mobile/ios/local-deploy.md
  docs/reference/mobile/ios/run-client.md
  docs/reference/mobile/overview.md
  docs/reference/overview.md
  docs/reference/troubleshooting.md
  docs/reference/workflows/ecs/entity-contracts.md
  docs/reference/workflows/ecs/interaction/authority.md
  docs/reference/workflows/ecs/interaction/commands/component-commands.md
  docs/reference/workflows/ecs/interaction/commands/world-commands.md
  docs/reference/workflows/ecs/interaction/component-updates.md
  docs/reference/workflows/ecs/interaction/events.md
  docs/reference/workflows/ecs/reactive-components.md
  docs/reference/workflows/ecs/system-update-order.md
  docs/reference/workflows/ecs/temporary-components.md
  docs/reference/workflows/ecs/worker-entity.md
  docs/reference/workflows/monobehaviour/creating-workers.md
  docs/reference/workflows/monobehaviour/interaction/commands/component-commands.md
  docs/reference/workflows/monobehaviour/interaction/commands/create-delete-spatialos-entities.md
  docs/reference/workflows/monobehaviour/interaction/commands/world-commands.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/component-data-updates.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/events.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/index.md
  docs/reference/workflows/monobehaviour/interaction/reader-writers/lifecycle.md
  docs/reference/workflows/monobehaviour/linking/spatialos-entities.md
  docs/reference/workflows/monobehaviour/linking/workers.md
  docs/reference/workflows/which-workflow.md
  docs/reference/world-component-commands-requests-responses.md
Labels: T: documentation, size/XL

#873 Add callback to player creation
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Config/PlayerLifecycleConfig.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/Systems/PlayerCreation/SendCreatePlayerRequestSystem.cs
Labels: A: player-lifecycle, size/S

#878 Update README.md
  README.md
Labels: size/XS

#879 Add a redirect
  docs/content/get-started/get-started.md
Labels: T: documentation, size/XS

#880 Fast forward docs-next
  docs/content/get-started/get-started.md
Labels: T: documentation, size/XS

#881 Update troubleshooting documentation
  docs/reference/troubleshooting.md
Labels: T: documentation, size/M

#882 Cherry pick troubleshooting docs
  docs/reference/troubleshooting.md
Labels: T: documentation, size/M
