Repository spatialos/gdk-for-unity, pull requests merged in 2019-01, with the labels that each got.

#669 ensure chmod runs even with spaces in path (OSX)
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
Labels: size/XS

#629 Entity Template v2
  CHANGELOG.md
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableReaderTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs
  test-project/Assets/EditmodeTests/GameObjectRepresentation/Readers/NonBlittableWriterTests.cs.meta
  test-project/Assets/EditmodeTests/Utility.meta
  test-project/Assets/EditmodeTests/Utility/EntityTemplateTests.cs
  test-project/Assets/EditmodeTests/Utility/EntityTemplateTests.cs.meta
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveBlittableSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/NestedComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/alternateschemasyntax/Connection.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/blittabletypes/BlittableComponent.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFields.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithCommands.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/componentswithnofields/ComponentWithNoFieldsWithEvents.cs
  test-project/Assets/Generated/Source/improbable/gdk/tests/nonblittabletypes/NonBlittableComponent.cs
  workers/unity/Assets/Playground/Config/CubeTemplate.cs
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
  workers/unity/Packages/com.improbable.gdk.core/Dynamic/DynamicSnapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs
  workers/unity/Packages/com.improbable.gdk.core/Tests/Editmode/Utility/EntityBuilderTest.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityBuilder.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityQuerySnapshot.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/EntityTemplate.cs
  workers/unity/Packages/com.improbable.gdk.core/Utility/Snapshot.cs
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/PlayerLifecycleHelper.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityComponentDataGenerator.tt
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/TransformSynchronizationHelper.cs
Labels: size/XXL

#671 Update PR template
  .github/pull_request_template.md
Labels: size/XS

#674 Small additions to getting started
  docs/content/build.md
  docs/content/get-started/build-workers.md
  docs/content/get-started/open-project.md
  docs/content/get-started/upload-launch.md
Labels: C: documentation, size/M

#660 anonymous auth for mobile
  CHANGELOG.md
  spatialos.json
  workers/unity/Assets/Playground/Resources/Prefabs/Common/MobileConnectionSplashScreen.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/AndroidClientWorker.prefab
  workers/unity/Assets/Playground/Resources/Prefabs/Worker/iOSClientWorker.prefab
  workers/unity/Assets/Playground/Scenes/AndroidClientScene.unity
  workers/unity/Assets/Playground/Scenes/iOSClientScene.unity
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/IMobileConnectionController.cs
  workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/AuthenticationFailedException.cs
  workers/unity/Packages/com.improbable.gdk.core/Exceptions/AuthenticationFailedException.cs.meta
  workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Android/Utility/LaunchArguments.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Labels: A: mobile, T: feature, size/XXL

#680 Removed link
  README.md
Labels: size/XS

#684 Fixed bug where worker type was read from command line
  workers/unity/Packages/com.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/com.improbable.gdk.core/Worker/DefaultWorkerConnector.cs
Labels: A: core, T: bug, size/XS

#685 Fix mobile client read access to PlayerTemplate
  workers/unity/Assets/Playground/Config/CubeTemplate.cs
  workers/unity/Assets/Playground/Config/PlayerTemplate.cs
  workers/unity/Assets/Playground/Editor/SnapshotGenerator/SnapshotGenerator.cs
Labels: A: playground, T: bug, size/XS

#653 UTY-1503: Pull across parts of the old CodeGeneration library.
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/FileSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/FileWrapper.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/IFile.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/FileHandling/IFileSystem.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/CodegenJob.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Jobs/JobRunner.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Model/BuiltInSchemaTypes.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/CodeGeneration/Tests/Model/SchemaBundleV1/JsonParsingTests.cs
Labels: A: codegen, T: refactor, size/XL

#688 Docs: Update roadmap links to Github
  docs/content/mobile/overview.md
  docs/toc.md
Labels: A: maintenance, T: documentation, size/XS

#689 Upgrade to stable Worker SDK version
  CHANGELOG.md
  spatialos.json
  workers/unity/Packages/com.improbable.gdk.tools/core-sdk.version
Labels: A: core, T: enhancement, size/XS

#690 toc formatting
  docs/toc.md
Labels: size/XS

#692 2018.3 Upgrade
  CHANGELOG.md
  ci/UnityEditorHash.txt
  test-project/Packages/manifest.json
  test-project/ProjectSettings/ProjectVersion.txt
  test-project/ProjectSettings/VFXManager.asset
  workers/unity/Packages/com.improbable.gdk.core/Worker/Worker.cs
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/manifest.json
  workers/unity/ProjectSettings/GraphicsSettings.asset
  workers/unity/ProjectSettings/ProjectSettings.asset
  workers/unity/ProjectSettings/ProjectVersion.txt
  workers/unity/ProjectSettings/QualitySettings.asset
  workers/unity/ProjectSettings/VFXManager.asset
Labels: A: core, A: maintenance, T: enhancement, size/L

#693 Switching to KCP on mobile worker + use small connection timeout
  mobile_launch.json
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
Labels: size/S

#683 Fix underflow memory allocation crash in transform sync.
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/Systems/InterpolateTransformSystem.cs
Labels: A: transform-synchronization, T: bug, size/S

#696 Docs - Update SpatialOS & Unity version in tutorial/setup
  docs/content/get-started/set-up.md
  docs/content/get-started/upload-launch.md
  docs/setup-and-installing.md
Labels: A: maintenance, T: documentation, size/S

#695 UTY-1627: Fix Codegen Nullref
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/src/Generation/Model/UnitySchemaFile.cs
Labels: A: codegen, T: bug, size/S

#698 Update unity version in package.json
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: A: maintenance, T: enhancement, size/S

#686 [UTY-1613] Gracefully handle disconnect in Playground
  CHANGELOG.md
  workers/unity/Assets/Playground/Scripts/Camera/InitCameraSystem.cs
  workers/unity/Assets/Playground/Scripts/UI/ConnectionScreenController.cs
  workers/unity/Assets/Playground/Scripts/UI/InitUISystem.cs
  workers/unity/Assets/Playground/Scripts/Worker/AndroidClientWorkerConnector.cs
  workers/unity/Assets/Playground/Scripts/Worker/iOSClientWorkerConnector.cs
Labels: A: playground, T: enhancement, size/S

#700 Add Packer Config
  ci/pack.sh
  packer.config.json
Labels: A: maintenance, T: feature, size/S

#682 Entity Template Documentation Updates
  docs/content/api-entity-builder.md
  docs/content/entity-templates.md
  docs/content/gameobject/create-delete-spatialos-entities.md
  docs/content/glossary.md
  docs/content/modules/core-and-feature-module-overview.md
  docs/content/modules/player-lifecycle-feature-module.md
  docs/content/modules/transform-feature-module.md
  docs/projects/fps/tutorial.md
  docs/toc.md
Labels: A: core, T: documentation, T: refactor, size/L

#702 Build client for cloud in CI
  ci/build-test.sh
Labels: A: maintenance, T: bug, size/XS

#704 Add CI Launch Script
  ci/upload-launch.sh
Labels: A: maintenance, T: feature, size/S

#706 Build System Tweaks
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.tools/.CodeGenerator/GdkCodeGenerator/Templates/UnityWorkerMenuGenerator.tt
Labels: A: build-system, T: enhancement, size/M

#705 Release 0.1.4 Prep
  CHANGELOG.md
  packer.config.json
  workers/unity/Packages/com.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/com.improbable.gdk.core/package.json
  workers/unity/Packages/com.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/com.improbable.gdk.mobile/package.json
  workers/unity/Packages/com.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/com.improbable.gdk.testutils/package.json
  workers/unity/Packages/com.improbable.gdk.tools/package.json
  workers/unity/Packages/com.improbable.gdk.transformsynchronization/package.json
Labels: A: maintenance, size/M

#667 Local deployment docs for local deployment with ADB
  docs/content/mobile/android/local-deploy.md
  docs/content/mobile/android/ways-to-test.md
Labels: A: mobile, T: documentation, size/M

#707 Removed the concept of a temporarily removed entity
  workers/unity/Packages/com.improbable.gdk.core/Subscriptions/CalllbackManagers/EntityRemovedCallbackManager.cs
  workers/unity/Packages/com.improbable.gdk.core/Systems/EntitySystem.cs
Labels: A: core, T: bug, size/S

#712 The mobile cloud docs
  docs/content/connecting-to-spatialos.md
  docs/content/gameobject/creating-workers-with-workerconnector.md
  docs/content/mobile/android/cloud-deploy.md
  docs/content/mobile/ios/cloud-deploy.md
  docs/content/mobile/overview.md
  docs/toc.md
Labels: size/XL

#710 Updating docs for Release 0.1.4
  docs/content/get-started/upload-launch.md
  docs/content/glossary.md
  docs/known-issues.md
  docs/projects/fps/tutorial.md
Labels: T: documentation, size/M

#713 fixing table
  docs/content/get-started/set-up.md
Labels: size/XS

#709 Fix ADB throwing an error if your project path has spaces in it
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
Labels: A: mobile, T: bug, size/XS

#716 Fix Package Traversal Exception
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.tools/Common.cs
Labels: A: codegen, T: bug, size/XS

#718 Fix Docs Branch Verification
  ci/docs-build-verification.sh
Labels: A: maintenance, T: bug, size/XS

#717 Update roadmap link in readme
  README.md
Labels: A: maintenance, T: documentation, size/XS

#719 Update copyright notice in README from 2018 to 2019
  README.md
Labels: size/XS

#708 BuildKite CI
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/premerge.definition.yaml
  .buildkite/premerge.steps.yaml
  .buildkite/trigger.sh
  ci/build-test.sh
Labels: A: maintenance, T: feature, size/M

#720 Add License Badge
  README.md
Labels: A: maintenance, T: documentation, size/XS

#721 Build Badge! More Badges!
  README.md
Labels: A: maintenance, T: documentation, size/XS

#722 Update Buildkite Default Branch
  .buildkite/premerge.definition.yaml
Labels: size/XS

#701 Rework RedirectProccess to have Builder API
  CHANGELOG.md
  workers/unity/Packages/com.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Editor/LaunchMenu.cs
  workers/unity/Packages/com.improbable.gdk.tools/DownloadCoreSdk.cs
  workers/unity/Packages/com.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/com.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/com.improbable.gdk.tools/RedirectedProcess.cs
Labels: A: tooling, T: refactor, size/XL

#724 Small changes to worker connector
  workers/unity/Packages/com.improbable.gdk.core/Worker/WorkerConnector.cs
  workers/unity/Packages/com.improbable.gdk.mobile/Worker/MobileWorkerConnector.cs
Labels: size/XS

#725 Correct name
  docs/content/troubleshooting.md
Labels: size/XS

#726 Setup Docs Bypass for Buildkite
  .buildkite/premerge.steps.yaml
  ci/build-test.sh
  ci/docs-build-verification.sh
Labels: A: maintenance, T: feature, size/M
