Repository spatialos/gdk-for-unity, pull requests merged in 2020-02, with the labels that each got.

#1265 Copy `libc++_shared.so` for Android builds
  CHANGELOG.md
  UPGRADE_GUIDE.md
  workers/unity/Packages/io.improbable.worker.sdk.mobile/CopyLibcpp.cs
  workers/unity/Packages/io.improbable.worker.sdk.mobile/CopyLibcpp.cs.meta
Labels: jira/no-ticket, size/M

#1266 Redirect schema compiler output to the codegen log
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Utils/SystemTools.cs
Labels: A: tooling, jira/no-ticket, size/XS

#1267 Build deployment launcher in CI
  .buildkite/premerge.steps.yaml
  ci/build-deployment-launcher.sh
Labels: A: maintenance, jira/no-ticket, size/S

#1268 [WRK-1840] Change Worker SDK packages used for iOS
  CHANGELOG.md
  init.ps1
  init.sh
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/iOSLaunchUtils.cs
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/arm/libRakNetLibStatic.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/arm/libimprobable_worker.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/arm/libssl.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/arm/libz.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/x86_64/libRakNetLibStatic.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/x86_64/libimprobable_worker.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/x86_64/libssl.a.meta
  workers/unity/Packages/io.improbable.worker.sdk.mobile/Plugins/Improbable/Core/iOS/x86_64/libz.a.meta
Labels: A: mobile, jira/WRK, size/XXL

#1269 CI iOS build support
  CHANGELOG.md
  init.sh
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Util/CommandlineParser.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/WorkerBuilder.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidUtils.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidUtils.cs.meta
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLauncherWindow.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/iOSUtils.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/iOSUtils.cs.meta
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
Labels: A: build-system, A: mobile, jira/no-ticket, size/M

#1274 Upgrade Worker SDK to 14.4.1
  CHANGELOG.md
  spatialos.json
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/MobileLauncherWindow.cs
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
  workers/unity/Packages/io.improbable.worker.sdk/.sdk.version
Labels: A: mobile, A: tooling, jira/no-ticket, size/XS

#1278 Document targetiOSSdk flag
  docs/modules/build-system/cli.md
  docs/workflows/ecs/concepts/system-update-order.md
Labels: T: documentation, jira/no-ticket, size/S

#1279 Fix code finding the NDK root directory
  workers/unity/Packages/io.improbable.worker.sdk.mobile/CopyLibcpp.cs
Labels: jira/no-ticket, size/S

#1280 Revert "Release 0.3.3 - Pre-Validation"
  CHANGELOG.md
  packer.config.json
  test-project/Packages/io.improbable.gdk.dependencytest/package.json
  test-project/Packages/io.improbable.gdk.dependencytestchild/package.json
  test-project/Packages/io.improbable.gdk.dependencytestgrandchild/package.json
  test-project/Packages/io.improbable.worker.sdk.testschema/package.json
  workers/unity/Packages/io.improbable.gdk.buildsystem/package.json
  workers/unity/Packages/io.improbable.gdk.core/package.json
  workers/unity/Packages/io.improbable.gdk.debug/package.json
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/package.json
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/package.json
  workers/unity/Packages/io.improbable.gdk.mobile/package.json
  workers/unity/Packages/io.improbable.gdk.playerlifecycle/package.json
  workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/package.json
  workers/unity/Packages/io.improbable.gdk.testutils/package.json
  workers/unity/Packages/io.improbable.gdk.tools/package.json
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/package.json
  workers/unity/Packages/io.improbable.gdk.transformsynchronization2d/package.json
  workers/unity/Packages/io.improbable.worker.sdk.mobile/package.json
  workers/unity/Packages/io.improbable.worker.sdk/package.json
Labels: A: build-system, A: core, A: game-object-creation, A: mobile, A: player-lifecycle, A: tooling, A: transform-synchronization, jira/no-ticket, size/M

#1281 Fix CopyTemplate for downloaded package.
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: tooling, jira/no-ticket, size/XS

#1285 Fix typo in iOS target sdk section
  docs/modules/build-system/cli.md
Labels: T: documentation, jira/no-ticket, size/XS

#1286 Cherry pick #1285 into docs-next
  docs/modules/build-system/cli.md
Labels: T: documentation, jira/no-ticket, size/XS

#1271 [1/5] Quick codegen tidy up
  test-project/Assets/Config/GdkToolsConfiguration.json
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffDeserializerGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandMetaDataStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffDeserializerGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/MetaclassGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityCommandPayloadGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentSenderGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEcsViewManagerGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEnumContent.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEventGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityReferenceTypeProviderGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityTypeContent.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ViewStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityCommandSenderReceiverGenerator.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityComponentReaderWriterGenerator.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobRunner.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Bundle.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/Details.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsUtils.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ListFieldType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/MapFieldType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/OptionFieldType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/SingularFieldType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/PropertyDetails/UnityCommandDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/PropertyDetails/UnityEventDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/PropertyDetails/UnityFieldDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/GeneratorInputDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityComponentDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityEnumDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityTypeDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityCommandDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityComponentDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityEnumDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/UnityEventDetails.cs
Labels: A: build-system, A: core, A: game-object-creation, A: tooling, jira/no-ticket, size/XXL

#1273 [2/5] Prepare generators for new CodegenJob
  test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/Generators/TestProject/ModularCodegenTestGenerator.cs
  test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/Generators/BuildSystem/UnityWorkerMenuGenerator.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffDeserializerGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandDiffStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/CommandMetaDataStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffDeserializerGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/MetaclassGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityCommandPayloadGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentSenderGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEcsViewManagerGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEnumContent.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEnumGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityEventGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityReferenceTypeProviderGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityTypeGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ViewStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityCommandSenderReceiverGenerator.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityComponentReaderWriterGenerator.cs
Labels: A: build-system, A: core, A: game-object-creation, A: tooling, jira/no-ticket, size/XL

#1275 [3/5] New CodegenJob model
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/CodeWriter.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobRunner.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobTarget.cs
Labels: A: tooling, jira/no-ticket, size/L

#1276 [4/5] Port modules to new CodegenJob model
  test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Jobs/CodegenJobTests.cs
Labels: A: build-system, A: core, A: game-object-creation, A: tooling, jira/no-ticket, size/XL

#1277 [5/5] Cleanup codegen
  CHANGELOG.md
  test-project/Packages/io.improbable.gdk.dependencytest/.codegen/Source/TestCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/WorkerGenerationJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/CoreCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/GameObjectCodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGen/EntryPoint.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/CodegenJob.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Jobs/JobRunner.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Jobs/CodegenJobTests.cs
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: build-system, A: core, A: game-object-creation, A: tooling, jira/no-ticket, size/L

#1289 Add runtime version override
  CHANGELOG.md
  workers/unity/Assets/Config/GdkToolsConfiguration.json
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Options.cs
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
  workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
Labels: A: playground, A: tooling, jira/no-ticket, size/M

#1291 Change zip download references to auto generated zips
  docs/projects/blank/tutorial/1/project-walkthrough.md
  docs/projects/fps/get-started/set-up.md
Labels: T: documentation, jira/no-ticket, size/XS

#1292 Cherry pick #1291
  ci/shared-ci.pinned
  docs/projects/blank/tutorial/1/project-walkthrough.md
  docs/projects/fps/get-started/set-up.md
Labels: T: documentation, jira/no-ticket, size/XS

#1293 Remove packer config
  packer.config.json
Labels: jira/no-ticket, size/S

#1294 Codegen bugfixes
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/GenerateCode.cs
Labels: A: tooling, jira/no-ticket, size/M

#1296 Fix bug where mobile launcher wouldn't find Android devices with hyphens in their product name
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/Generators/BuildSystem/BuildSystemAssemblyGenerator.cs
  workers/unity/Packages/io.improbable.gdk.mobile/Editor/AndroidUtils.cs
Labels: A: build-system, A: mobile, jira/UTY, size/S

#1295 Add requireables <-> unlink tests
  CHANGELOG.md
  test-project/Assets/.schema/commands.schema
  test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs
  test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs.meta
Labels: jira/no-ticket, size/M

#1270 MacOS buildkite for real
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/premerge.steps.yaml
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialdManager.cs
Labels: A: mobile, jira/no-ticket, size/M

#1290 Simplify components, step 1
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameNameComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentDiffStorage.cs
  test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponentComponentDiffStorage.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/EntityId.cs
  workers/unity/Packages/io.improbable.gdk.core/View/DiffComponentStorage.cs
  workers/unity/Packages/io.improbable.gdk.core/View/DiffComponentStorage.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Worker/DiffStorage.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/MessagesToSend.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/ViewDiff.cs
Labels: A: core, jira/no-ticket, size/XXL

#1298 Events also update entities!
  CHANGELOG.md
  test-project/Assets/EditmodeTests/Core.meta
  test-project/Assets/EditmodeTests/Core/ComponentDiffStorageTests.cs
  test-project/Assets/EditmodeTests/Core/ComponentDiffStorageTests.cs.meta
  test-project/Assets/EditmodeTests/DisableAutoCreationSystemsTests.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentDiffStorage.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/ComponentDiffStorageGenerator.cs
Labels: A: core, jira/no-ticket, size/L

#1297 Requireable constraint tweaks & bugfixing
  CHANGELOG.md
  test-project/Assets/EditmodeTests/Subscriptions/RequireablesDisableTests.cs
  test-project/Assets/EditmodeTests/Subscriptions/RequireablesDisableTests.cs.meta
  test-project/Assets/EditmodeTests/Subscriptions/RequireablesUnlinkTests.cs.meta
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameNameComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponentComponentReaderWriter.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/CommandSenderReceiverSubscriptionManagerBase.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/RequiredSubscriptionsInjector.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityComponentReaderWriterGenerator.cs
Labels: A: core, A: game-object-creation, jira/no-ticket, size/XL

#1299 Golden pinned runtime version
  CHANGELOG.md
  ci/launch.sh
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Commands/Create.cs
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/.DeploymentLauncher/Options.cs
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentConfigurations.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
  workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/io.improbable.gdk.tools/runtime.pinned
  workers/unity/Packages/io.improbable.gdk.tools/runtime.pinned.meta
Labels: A: maintenance, A: tooling, jira/no-ticket, size/M

#1301 Enable SpatialD tests on MacOS
  .buildkite/premerge.steps.yaml
  ci/test.sh
Labels: A: core, A: maintenance, jira/no-ticket, size/S

#1300 Simplify Readers and Writers
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponentComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestChildComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchildComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameNameComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntityComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKeyComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValueComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptionalComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeatedComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingularComponentReaderWriter.cs
  test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponentComponentReaderWriter.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/CommandSenderReceiverSubscriptionManagerBase.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/IRequireable.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/IRequireable.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/Reader.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/Reader.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/ReaderSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/ReaderSubscriptionManager.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/EntitySubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorkerFlagSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorkerIdSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorldCommands.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/StandardSubscriptionManagers/WorldSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/SubscriptionManagerBase.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/WriterSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/WriterSubscriptionManager.cs.meta
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/.codegen/Source/Generators/GameObjectCreation/UnityComponentReaderWriterGenerator.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/LinkedGameObjectMapSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialdManager.cs
  workers/unity/Packages/io.improbable.gdk.tools/RedirectedProcess.cs
Labels: A: core, A: game-object-creation, A: tooling, jira/no-ticket, size/XXL

#1302 Display runtime version in deployment launcher
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindowStyle.cs
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindowStyle.cs.meta
Labels: jira/no-ticket, size/L

#1303 Docs for runtime version in deployment launcher
  docs/assets/modules/deployment-launcher/edit-runtime-version-button.png
  docs/modules/deployment-launcher/overview.md
Labels: T: documentation, jira/no-ticket, size/XS

#1306 Add linting
  .buildkite/premerge.steps.yaml
  .editorconfig
  ci/bootstrap.sh
  ci/get-shared-ci.sh
  ci/lint.sh
  ci/shared-ci.pinned
  workers/unity/Assets/Generated/AssemblyInfo.cs
  workers/unity/Assets/Playground/Scripts/Cubes/ColorTranslationUtil.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/LaunchableBehaviour.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/SpawnCubeCommandReceiver.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/UpdateSpinnerColor.cs
  workers/unity/Assets/Playground/Scripts/MonoBehaviours/WorkerFlagTest.cs
  workers/unity/Assets/Playground/Scripts/Worker/GameLogicWorkerConnector.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfig.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/WorkerChoicePopup.cs
  workers/unity/Packages/io.improbable.gdk.core/Attributes/DisableAutoRegisterAttribute.cs
  workers/unity/Packages/io.improbable.gdk.core/Components/ISnapshottable.cs
  workers/unity/Packages/io.improbable.gdk.core/EntityId.cs
  workers/unity/Packages/io.improbable.gdk.core/Exceptions/InvalidSpatialEntityStateException.cs
  workers/unity/Packages/io.improbable.gdk.core/Exceptions/UnknownComponentIdException.cs
  workers/unity/Packages/io.improbable.gdk.core/Exceptions/UnknownRequestIdException.cs
  workers/unity/Packages/io.improbable.gdk.core/SchemaObjectExtensions.cs
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/ReaderSubscriptionManager.cs
  workers/unity/Packages/io.improbable.gdk.core/Systems/WorkerDisconnectCallbackSystem.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Logging/LoggingTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Systems/SpatialOSSendSystemTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Utility/Snapshot.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/SerializedMessagesToSend.cs
  workers/unity/Packages/io.improbable.gdk.debug/MonoBehaviourInspector.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/Tests/Editmode/LinkedGameObjectMapSubscriptionTests.cs
  workers/unity/Packages/io.improbable.gdk.testutils/.SpotShim/SpotShim/SpotShim/Program.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialDeploymentManager.cs
  workers/unity/Packages/io.improbable.gdk.testutils/Editor/SpatialdManager.cs
  workers/unity/Packages/io.improbable.gdk.testutils/TestLogDispatcher.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/.editorconfig
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationWindow.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/DeferredUpdateTransform.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/GetTransformFromGameObjectTag.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/InterpolationConfig.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/LastPositionSentData.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/LastTransformSentData.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/ManageKinematicOnAuthorityChangeTag.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/RateLimitedSendConfig.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/TicksSinceLastTransformUpdate.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/TransformToSend.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Components/TransformToSet.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/MonoBehaviours/TransformSynchronization.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/ScriptableObjects/ReceiveStrategies/DirectReceiveStrategy.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/ScriptableObjects/ReceiveStrategies/InterpolationReceiveStrategy.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/ScriptableObjects/SendStrategies/RateLimitedSendStrategy.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/ScriptableObjects/TransformSynchronizationReceiveStrategy.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/ScriptableObjects/TransformSynchronizationSendStrategy.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultApplyLatestTransformSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/DefaultUpdateLatestTransformSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/GetTransformValueToSetSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/ResetForAuthorityGainedSystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/Systems/SetKinematicFromAuthoritySystem.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/TransformUtils.cs
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: playground, A: tooling, A: transform-synchronization, jira/no-ticket, size/L
