Repository spatialos/gdk-for-unity, pull requests merged in 2020-07, with the labels that each got.

#1411 Scripting Implementation option in Build config UI
  CHANGELOG.md
  UPGRADE_GUIDE.md
  init.ps1
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditorStyle.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs
Labels: A: build-system, A: playground, jira/no-ticket, size/M

#1409 UTY 2088: Set external ip from cli
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Config/RuntimeConfig.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Connection/CommandLineConnectionParametersInitializerTests.cs
  workers/unity/Packages/io.improbable.gdk.core/Tests/Editmode/Utility/CommandLineUtilityTest.cs
  workers/unity/Packages/io.improbable.gdk.core/Utility/CommandLineUtility.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/ConnectionParameterInitializers.cs
Labels: A: core, jira/UTY, size/M

#1412 UTY-1970: invalid enum definition
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityEnumDetails.cs
Labels: A: maintenance, A: tooling, jira/UTY, size/S

#1413 Add Allow Debug option to Build Configuration UI
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
Labels: A: build-system, jira/no-ticket, size/M

#1414 UTY-2644: shorten build string in sonar
  ci/sonar-scanner.sh
Labels: A: maintenance, jira/UTY, size/XS

#1415 Merge testing/sonarcloud CI steps
  .buildkite/premerge.steps.yaml
  ci/sonar-scanner.sh
  ci/test.sh
Labels: A: maintenance, jira/no-ticket, size/M

#1416 Limit perftest targets + package dependency fix
  CHANGELOG.md
  ci/perf-test.sh
  ci/perftest-configs.json
  workers/unity/Packages/io.improbable.gdk.testutils/package.json
  workers/unity/Packages/manifest.json
Labels: A: maintenance, jira/no-ticket, size/M

#1419 UTY-2607: update linux queue
  .buildkite/generate-docs.steps.yaml
  .buildkite/premerge.steps.yaml
Labels: A: build-system, A: core, A: maintenance, A: playground, A: tooling, jira/UTY, size/XS

#1418 Update buildkite artifact path to only use forward slash
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/launch.sh
Labels: A: maintenance, jira/no-ticket, size/XS

#1422 UTY-2626: Update spatialos json
  spatialos.json
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: player-lifecycle, A: playground, A: tooling, jira/UTY, size/XS

#1424 UTY-2643: fix codegen indentation
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Text.cs
Labels: A: build-system, A: core, A: game-object-creation, A: maintenance, A: player-lifecycle, A: playground, A: tooling, jira/UTY, size/XS

#1421 Remove Windows x86 support in build configuration
  CHANGELOG.md
  workers/unity/Assets/Playground/Config/BuildConfiguration.asset
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildEnvironmentConfig.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildTargetConfig.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Util/BuildSupportChecker.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/Util/CommandlineParser.cs
Labels: A: build-system, A: playground, jira/no-ticket, size/M

#1423 UTY-2640: Add component info
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/ComponentVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/GeneratorInputDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityComponentDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityEnumDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityTypeDetails.cs
Labels: A: tooling, jira/UTY, size/M

#1417 UTY-2641: hide empty collections
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/ComponentVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/HideCollectionEvent.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/HideCollectionEvent.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/OptionVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedListView.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedMapView.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/VisualElementConcealerTests.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/VisualElementConcealerTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/VisualElementConcealer.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/VisualElementConcealer.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityDetail.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/PropertyDetails/UnityFieldDetails.cs
Labels: A: playground, A: tooling, jira/UTY, size/L

#1426 UTY-2657: set max ci agents
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
Labels: jira/UTY, size/XS

#1429 Fix bug where CommandSender would not reenable after being disabled
  CHANGELOG.md
  workers/unity/Assets/Tests/EditmodeTests/Correctness/Subscriptions/RequireablesReenableTests.cs
  workers/unity/Assets/Tests/EditmodeTests/Correctness/Subscriptions/RequireablesReenableTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Subscriptions/CommandSenderReceiverSubscriptionManagerBase.cs
Labels: A: core, A: playground, jira/no-ticket, size/M

#1427 Support multiple annotations on method/type/enum blocks in Code Writer API
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scope.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Abstract/ScopeBlock.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Annotations.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/EnumBlock.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/MethodBlock.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/TypeBlock.cs
Labels: A: tooling, jira/no-ticket, size/M

#1428 UTY-2504: Nullable command response
  CHANGELOG.md
  workers/unity/Assets/Playground/Scripts/Player/PlayerCommandsSystem.cs
  workers/unity/Packages/io.improbable.gdk.core/Commands/CommandDiffStorageBase.cs
  workers/unity/Packages/io.improbable.gdk.core/Systems/CommandSystem.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/DiffStorage.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/WorldCommandsReceivedStorage.cs
Labels: A: core, A: playground, jira/UTY, size/M

#1425 Prevent worker builds with compiler errors in Unity Editor
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.buildsystem/.codegen/Source/Generators/BuildSystem/UnityWorkerMenuGenerator.cs
  workers/unity/Packages/io.improbable.gdk.buildsystem/WorkerBuilder.cs
Labels: A: build-system, jira/no-ticket, size/XS

#1434 Update Worker SDK version to 14.7.0
  CHANGELOG.md
  spatialos.json
  workers/unity/Packages/io.improbable.worker.sdk/.sdk.version
Labels: jira/no-ticket, size/XS

#1433 Move pr1428 changelog entry from 0.3.8 to unreleased
  CHANGELOG.md
Labels: jira/no-ticket, size/XS

#1432 UTY-2659: set different entt list version
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityList.cs
Labels: jira/UTY, size/XS

#1435 Correctly skip builds which are not marked as required
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildContext.cs
Labels: A: build-system, jira/no-ticket, size/XS

#1438 Fix the `PrefabPreprocessor`
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Representation/Editor/PrefabPreprocessor.cs
Labels: A: core, jira/UTY, size/XS

#1441 Fix Android support check
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.buildsystem/Configuration/BuildConfigEditor.cs
Labels: A: build-system, jira/UTY, size/S

#1440 Event Tracing API C# Bindings
  CHANGELOG.md
  workers/unity/Packages/io.improbable.worker.sdk/CEventTrace.cs
  workers/unity/Packages/io.improbable.worker.sdk/CEventTrace.cs.meta
  workers/unity/Packages/io.improbable.worker.sdk/CIO.cs
  workers/unity/Packages/io.improbable.worker.sdk/CIO.cs.meta
  workers/unity/Packages/io.improbable.worker.sdk/Constants.cs
  workers/unity/Packages/io.improbable.worker.sdk/Constants.cs.meta
  workers/unity/Packages/io.improbable.worker.sdk/Improbable.Worker.Sdk.asmdef
  workers/unity/Packages/io.improbable.worker.sdk/Improbable.Worker.Sdk.asmdef.meta
Labels: jira/no-ticket, size/XXL

#1437 UTY-2508: enable command tests
  CHANGELOG.md
  workers/unity/Assets/Tests/EditmodeTests/Correctness/Core/CommandReceivedResponseTests.cs
  workers/unity/Assets/Tests/EditmodeTests/Correctness/Core/CommandReceivedResponseTests.cs.meta
  workers/unity/Assets/Tests/EditmodeTests/Correctness/Subscriptions/CommandTests.cs
  workers/unity/Assets/Tests/EditmodeTests/Correctness/Subscriptions/CommandTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/MetaclassGenerator.cs
  workers/unity/Packages/io.improbable.gdk.core/Commands/ICommandMetaclass.cs
  workers/unity/Packages/io.improbable.gdk.core/Commands/IOutgoingCommandHandler.cs
  workers/unity/Packages/io.improbable.gdk.core/Commands/IOutgoingCommandHandler.cs.meta
  workers/unity/Packages/io.improbable.gdk.core/Dynamic/ComponentDatabase.cs
  workers/unity/Packages/io.improbable.gdk.core/Systems/CommandSystem.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs
  workers/unity/Packages/io.improbable.gdk.core/Worker/ConnectionHandlers/MockConnectionHandler.cs.meta
  workers/unity/Packages/io.improbable.gdk.testutils/MockWorld.cs
Labels: A: build-system, A: core, A: playground, A: tooling, jira/UTY, size/XL

#1442 Fix MacOS local launch errors when there are spaces in paths
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
Labels: A: tooling, jira/no-ticket, size/S
