Repository spatialos/gdk-for-unity, pull requests merged in 2020-06, with the labels that each got.

#1377 Enable Accelerator
  .buildkite/premerge.steps.yaml
  .buildkite/release-qa.steps.yaml
  ci/shared-ci.pinned
  ci/sonar-scanner.sh
  ci/test.sh
Labels: A: maintenance, jira/no-ticket, size/M

#1378 fix Dirtybits bit shift
  CHANGELOG.md
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentComponent.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponent.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentCommandDiffDeserializer.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentCommandMetaDataStorage.cs
  test-project/Assets/Generated/Source/improbable/dependentschema/DependentDataComponentCommandPayloads.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTest.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestChild.cs
  test-project/Assets/Generated/Source/improbable/tests/DependencyTestGrandchild.cs
  test-project/Assets/Generated/Source/improbable/testschema/ComponentUsingNestedTypeSameName.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveEntity.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapKey.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveMapValue.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveOptional.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveRepeated.cs
  test-project/Assets/Generated/Source/improbable/testschema/ExhaustiveSingular.cs
  test-project/Assets/Generated/Source/improbable/testschema/RecursiveComponent.cs
  workers/unity/Packages/io.improbable.gdk.core/.codegen/Source/Generators/Core/UnityComponentDataGenerator.cs
Labels: A: core, jira/no-ticket, size/M

#1380 Add codegen tests for name clashes
  CHANGELOG.md
  test-project/Assets/.schema/illegal.schema
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeGenerationLib.csproj
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/DetailsStore.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/NameClashingSchema/clash_command_in_component.schema
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/NameClashingSchema/clash_enum_in_type.schema
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/NameClashingSchema/clash_event_in_component.schema
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/NameClashingSchema/clash_type_in_type.schema
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/NameClashingTests.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/SchemaBundleV1/JsonParsingTests.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/SchemaBundleV1/Resources/clash_command_in_component.json
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/SchemaBundleV1/Resources/clash_enum_in_type.json
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/SchemaBundleV1/Resources/clash_event_in_component.json
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Tests/Model/SchemaBundleV1/Resources/clash_type_in_type.json
Labels: A: tooling, jira/no-ticket, size/XL

#1381 Update shared ci pin
  ci/shared-ci.pinned
Labels: A: maintenance, jira/no-ticket, size/XS

#1382 Add worker details to worker inspector
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/View/View.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerDetail.uxml
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerDetail.uxml.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uxml
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Dark.uss
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Dark.uss.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Light.uss
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Light.uss.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/WorkerDetail.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/WorkerDetail.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/WorkerInspectorWindow.cs
Labels: A: core, jira/no-ticket, size/L

#1384 New Buildkite instrumentation format
  ci/bootstrap.sh
  ci/build-deployment-launcher.sh
  ci/get-shared-ci.sh
  ci/launch.sh
  ci/lint.sh
  ci/publish_packages.sh
  ci/shared-ci.pinned
  ci/sonar-scanner.sh
  ci/test.sh
Labels: A: maintenance, jira/no-ticket, size/L

#1389 Disable MacOS Agents temporarily due to broken agents
  .buildkite/premerge.steps.yaml
Labels: jira/no-ticket, size/M

#1388 Bugfix/asmdef guid
  workers/unity/Packages/io.improbable.gdk.core/Editor/Improbable.Gdk.Core.Editor.asmdef
  workers/unity/Packages/io.improbable.gdk.debug/Tests/Editmode/Improbable.Gdk.Debug.EditmodeTests.asmdef
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Improbable.Gdk.Debug.WorkerInspector.Codegen.asmdef
Labels: A: core, jira/no-ticket, size/S

#1387 Render primitive schema data & enums in the worker inspector
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/DebugAssemblyGenerator.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/Abstract/ScopeBody.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/CodeWriter/Scopes/TypeBlock.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/SingularFieldType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/PropertyDetails/UnityFieldDetails.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Utils/Formatting.cs
Labels: A: tooling, jira/no-ticket, size/L

#1391 Add rendering support for user-defined types
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/ComponentVisualElementJob.cs
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/TypeVisualElementGenerator.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Dark.uss
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow_Light.uss
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ContainedType.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityTypeDetails.cs
Labels: A: tooling, jira/no-ticket, size/XL

#1392 Add Option<T> rendering to the Worker Inspector
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Improbable.Gdk.Debug.WorkerInspector.Codegen.asmdef
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/OptionVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/OptionVisualElement.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/OptionFieldType.cs
Labels: A: tooling, jira/no-ticket, size/L

#1385 Icons in the Worker Inspector
  CHANGELOG.md
  schema/playground/color.schema
  schema/playground/launcher.schema
  schema/playground/player_input.schema
  workers/unity/Packages/io.improbable.gdk.core/.schema/improbable/gdk/editor/worker_inspector.schema
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/ComponentVisualElementGenerator.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/ComponentVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
  workers/unity/Packages/io.improbable.gdk.gameobjectcreation/GameObjectInitializationSystem.cs
  workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/InterestQuery.cs
  workers/unity/Packages/io.improbable.gdk.querybasedinteresthelper/InterestTemplate.cs
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/TypeDetails/UnityComponentDetails.cs
  workers/unity/Packages/io.improbable.gdk.transformsynchronization/.schema/improbable/gdk/transform_synchronization/transform_internal.schema
Labels: A: core, A: game-object-creation, A: playground, A: tooling, A: transform-synchronization, jira/no-ticket, size/M

#1396 Add list support to Worker Inspector
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/AssemblyInfo.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/AssemblyInfo.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedListView.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedListView.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/SchemaTypeVisualElement.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/Improbable.Gdk.Debug.WorkerInspector.Codegen.EditmodeTests.asmdef
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/Improbable.Gdk.Debug.WorkerInspector.Codegen.EditmodeTests.asmdef.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/PaginatedListViewTests.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/Tests/PaginatedListViewTests.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/PaginatedListView.uxml
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/PaginatedListView.uxml.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/ListFieldType.cs
Labels: A: tooling, jira/no-ticket, size/XL

#1401 Add entity type rendering to Worker Inspector
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.core/Utility/EntitySnapshot.cs
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
Labels: A: core, jira/no-ticket, size/L

#1403 Add map support to the Worker Inspector and fix performance bug
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.debug/.codegen/Source/Generators/DebugExtensions/FieldTypeHandler.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedMapView.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Codegen/PaginatedMapView.cs.meta
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/EntityDetail.cs
  workers/unity/Packages/io.improbable.gdk.debug/WorkerInspector/Templates/WorkerInspectorWindow.uss
  workers/unity/Packages/io.improbable.gdk.tools/.CodeGenTemplate/CodeGenerationLib/Model/Details/FieldTypes/MapFieldType.cs
Labels: A: tooling, jira/no-ticket, size/L

#1407 [UTY-2631] Add new menu item to open inspector v2
  CHANGELOG.md
  init.ps1
  workers/unity/Packages/io.improbable.gdk.tools/LocalLaunch.cs
  workers/unity/Packages/io.improbable.gdk.tools/MenuPriorities.cs
Labels: A: tooling, jira/UTY, size/S

#1406 Push packages to the China registry.
  ci/publish_packages.sh
Labels: A: maintenance, jira/no-ticket, size/XS

#1408 Port Gdk Tools Configuration to Unity Project Settings
  CHANGELOG.md
  workers/unity/Packages/io.improbable.gdk.deploymentlauncher/DeploymentLauncherWindow.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfiguration.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationProvider.cs
  workers/unity/Packages/io.improbable.gdk.tools/GdkToolsConfigurationProvider.cs.meta
Labels: A: tooling, jira/no-ticket, size/M
